#!/usr/bin/env bash
# Hard-go: shadow-lower real stdlib cc_io_error.cch vs production.
# Normalizes guard style, define order/whitespace, field comments, case indent.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SRC="$ROOT/cc/include/ccc/cc_io_error.cch"
PROD="$ROOT/out/include/ccc/cc_io_error.h"
SHADOW_SH="$ROOT/examples/serdes/c/shadow_lower.sh"
TMP="${TMPDIR:-/tmp}/cc_serdes_io_error_$$"
mkdir -p "$TMP"

if [[ ! -f "$PROD" ]]; then
  echo "FAIL: missing production $PROD (build headers first)"
  exit 1
fi

"$SHADOW_SH" "$SRC" -o "$TMP/cc_io_error.shadow.h"

python3 - "$TMP/cc_io_error.shadow.h" "$PROD" "$TMP" <<'PY'
import pathlib, re, sys
sh_path, pr_path, tmp = map(pathlib.Path, sys.argv[1:4])

def join_continued(text: str) -> str:
    lines = text.splitlines()
    out, buf = [], ""
    for ln in lines:
        buf = (buf + ln) if buf else ln
        if buf.rstrip().endswith("\\"):
            buf = buf.rstrip()[:-1] + " "
            continue
        out.append(buf)
        buf = ""
    if buf:
        out.append(buf)
    return "\n".join(out) + "\n"

def norm(text: str, *, shadow: bool) -> str:
    text = join_continued(re.sub(r"/\*.*?\*/", "", text, flags=re.S))
    lines, defs = [], []
    for ln in text.splitlines():
        s = ln.rstrip()
        if shadow and s.startswith("/* generated by"):
            continue
        if s == "#pragma once":
            continue
        if re.match(r"#ifndef\s+CC_IO_ERROR_H\b", s):
            continue
        if re.match(r"#define\s+CC_IO_ERROR_H\b", s):
            continue
        if s.startswith("#endif") and ("CC_IO_ERROR" in s or s == "#endif"):
            continue
        if re.match(r"\s*#line\s", s):
            continue
        if shadow and s == "#include <stddef.h>":
            continue
        if not s.strip():
            continue
        if s.startswith("#define "):
            defs.append(re.sub(r"\s+", " ", s).strip())
            continue
        if re.match(r"\s*(case\b|default\s*:)", s):
            s = "        " + s.lstrip()
        s = re.sub(r"\s+;", ";", s)
        lines.append(s.rstrip())
    head = [s for s in lines if s.startswith("#include ")]
    body = [s for s in lines if not s.startswith("#include ")]
    return "\n".join(head + sorted(defs) + body) + "\n"

ns = norm(sh_path.read_text(), shadow=True)
np = norm(pr_path.read_text(), shadow=False)
(tmp / "shadow.norm.h").write_text(ns)
(tmp / "prod.norm.h").write_text(np)
if ns != np:
    print("FAIL: normalized shadow vs production cc_io_error.h surface differs")
    import subprocess
    subprocess.run(["diff", "-u", str(tmp / "prod.norm.h"), str(tmp / "shadow.norm.h")])
    sys.exit(1)
print("diff_stdlib_io_error: normalized C surface matches production")
PY

cat > "$TMP/use.c" <<'EOF'
#include "cc_io_error.h"
int main(void) {
    CCIoError e = cc_io_from_errno(ENOENT);
    (void)cc_io_error_str(e);
    (void)cc_io_error(CC_ERR_IO);
    return e.os_code == ENOENT ? 0 : 1;
}
EOF
cp "$TMP/cc_io_error.shadow.h" "$TMP/cc_io_error.h"
cc -std=c11 -I"$TMP" -I"$ROOT/out/include" -c "$TMP/use.c" -o "$TMP/use.o"
echo "diff_stdlib_io_error: host cc -c OK"
cp "$TMP/cc_io_error.shadow.h" "$ROOT/examples/serdes/c/shadow/cc_io_error.h.golden"
rm -rf "$TMP"
