#!/usr/bin/env bash
# Hard-go follow-on: shadow-lower real stdlib cc_chan_handle.cch vs production.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SRC="$ROOT/cc/include/ccc/cc_chan_handle.cch"
PROD="$ROOT/out/include/ccc/cc_chan_handle.h"
SHADOW_SH="$ROOT/examples/serdes/c/shadow_lower.sh"
TMP="${TMPDIR:-/tmp}/cc_serdes_chan_handle_$$"
mkdir -p "$TMP"

if [[ ! -f "$PROD" ]]; then
  echo "FAIL: missing production $PROD (build headers first)"
  exit 1
fi

"$SHADOW_SH" "$SRC" -o "$TMP/cc_chan_handle.shadow.h"

python3 - "$TMP/cc_chan_handle.shadow.h" "$PROD" "$TMP" <<'PY'
import pathlib, re, sys
sh_path, pr_path, tmp = map(pathlib.Path, sys.argv[1:4])

def strip_nested_ifndef(text: str) -> str:
    """Drop stub guards #ifndef __X / #define __X / #endif; keep bodies."""
    lines = text.splitlines()
    out = []
    i = 0
    while i < len(lines):
        s = lines[i]
        m = re.match(r"#ifndef\s+(__[A-Z0-9_]+)\b", s)
        if m:
            name = m.group(1)
            i += 1
            if i < len(lines) and re.match(rf"#define\s+{re.escape(name)}\b", lines[i]):
                i += 1
            depth = 1
            while i < len(lines) and depth:
                if re.match(r"#if(n?def)?\b", lines[i]):
                    depth += 1
                elif re.match(r"#endif\b", lines[i]):
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                if depth:
                    out.append(lines[i])
                    i += 1
            continue
        out.append(s)
        i += 1
    return "\n".join(out) + "\n"

def norm(text: str, *, shadow: bool) -> str:
    text = strip_nested_ifndef(text)
    out = []
    for ln in text.splitlines():
        s = ln.rstrip()
        if shadow and s.startswith("/* generated by"):
            continue
        if s == "#pragma once":
            continue
        if re.match(r"#ifndef\s+CC_CHAN_HANDLE_H\b", s):
            continue
        if re.match(r"#define\s+CC_CHAN_HANDLE_H\b", s):
            continue
        if s.startswith("#endif") and ("CC_CHAN_HANDLE" in s or s == "#endif"):
            continue
        if re.match(r"\s*#line\s", s):
            continue
        if shadow and s == "#include <stddef.h>":
            continue
        # EOF note after last decl — shadow has no trailing-trivia emit yet.
        if "ordered_recv is defined" in s:
            continue
        out.append(s)
    flat = []
    blank = False
    for s in out:
        if not s.strip():
            if not blank:
                flat.append("")
            blank = True
        else:
            flat.append(s)
            blank = False
    while flat and not flat[0].strip():
        flat.pop(0)
    while flat and not flat[-1].strip():
        flat.pop()
    return "\n".join(flat) + "\n"

ns = norm(sh_path.read_text(), shadow=True)
np = norm(pr_path.read_text(), shadow=False)
(tmp / "shadow.norm.h").write_text(ns)
(tmp / "prod.norm.h").write_text(np)
if ns != np:
    print("FAIL: normalized shadow vs production cc_chan_handle.h surface differs")
    import subprocess
    subprocess.run(["diff", "-u", str(tmp / "prod.norm.h"), str(tmp / "shadow.norm.h")])
    sys.exit(1)
print("diff_stdlib_chan_handle: normalized C surface matches production")
PY

cat > "$TMP/use.c" <<'EOF'
#include "cc_chan_handle.h"
int main(void) {
    CCChanTx tx;
    CCChanRx rx;
    (void)tx.raw;
    (void)rx.raw;
    return 0;
}
EOF
cp "$TMP/cc_chan_handle.shadow.h" "$TMP/cc_chan_handle.h"
cc -std=c11 -I"$TMP" -I"$ROOT/out/include" -c "$TMP/use.c" -o "$TMP/use.o"
echo "diff_stdlib_chan_handle: host cc -c OK"
cp "$TMP/cc_chan_handle.shadow.h" "$ROOT/examples/serdes/c/shadow/cc_chan_handle.h.golden"
rm -rf "$TMP"
