#line 1 "cc/lower/index.cch"
#pragma once
#line 1 "cc/lower/index.cch"
/* Declaration index: what the lowerer knows about names, from declarations.
 *
 * Built from the unit itself and every `.cch` it includes (each parsed in
 * header mode with the same parser, once per canonical path), from
 * `@typehooks` registrations, `*_DECL_UFCS(Name)` registrations, and the
 * declarations that file-scope macro invocations and generic factories
 * produce (their `#define` bodies and `@emit` templates are expanded here
 * and parsed as synthetic header units). It answers the questions the
 * lowerings ask, so no lowering carries a table of names:
 *   - is `f` a function, what does it return, is that a Result, of what?
 *   - is `T` a type, a typedef of what, a struct with which fields?
 *   - which method does `x.m()` resolve to for a receiver of type `T`
 *     (type hooks, header registrations, `Type_m`, `cc_<snake>_m`, faces)?
 *   - what is `T`'s destroy hook?
 *   - which argument of `f` is its arena?
 *   - may a call to `f` be discarded (`T?>(E)`)?
 *   - which Result specs must this unit emit, and which come from headers?
 * Missing knowledge is a diagnostic at the use site, never a guess. There
 * is no table of stdlib type, function or method names here.
 *
 * Lifetimes: the index, the header units it parses and every name it
 * spells live in the arena `cc_index_new` is given, which outlives the
 * unit being lowered. */

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 24 "cc/lower/index.cch"

#line 24 "cc/lower/index.cch"
#ifndef CC_LOWER_INDEX_CCH
#define CC_LOWER_INDEX_CCH

#include "parse.h"
#line 26 "cc/lower/index.cch"


#include <ccc/std/map.h>
#line 27 "cc/lower/index.cch"



#ifndef CC_HEADER_VEC_CCVec_CCSlice
#define CC_HEADER_VEC_CCVec_CCSlice
/* generic CCVec_CCSlice */

#ifdef CC_HAS_CCSLICE_CCSlice
CC_VEC_DECL_ARENA_TSLICE(CCSlice, CCVec_CCSlice, CCSlice_CCSlice)
#else
CC_VEC_DECL_ARENA(CCSlice, CCVec_CCSlice)
#endif
static inline CCVec_CCSlice cc__CCVec_CCSlice_new(CCArena __a) {
    return CCVec_CCSlice_init(__a, 0);
}
#define CCVec_CCSlice_new(ar) cc__CCVec_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CCSlice (serdes) */
static const cc_type_info __cc_ti_CCVec_CCSlice = { .name = "CCVec_CCSlice", .mangled = "CCVec_CCSlice", .id = 0, .size = (uint32_t)(sizeof(CCVec_CCSlice)), .align = (uint32_t)(_Alignof(CCVec_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CCSlice(void) {
    cc_type_info_register(&__cc_ti_CCVec_CCSlice);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcField
#define CC_HEADER_VEC_CCVec_CcField
/* generic CCVec_CcField */

#ifdef CC_HAS_CCSLICE_CcField
CC_VEC_DECL_ARENA_TSLICE(CcField, CCVec_CcField, CCSlice_CcField)
#else
CC_VEC_DECL_ARENA(CcField, CCVec_CcField)
#endif
static inline CCVec_CcField cc__CCVec_CcField_new(CCArena __a) {
    return CCVec_CcField_init(__a, 0);
}
#define CCVec_CcField_new(ar) cc__CCVec_CcField_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcField (serdes) */
static const cc_type_info __cc_ti_CCVec_CcField = { .name = "CCVec_CcField", .mangled = "CCVec_CcField", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcField)), .align = (uint32_t)(_Alignof(CCVec_CcField)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcField(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcField);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcEnumerator
#define CC_HEADER_VEC_CCVec_CcEnumerator
/* generic CCVec_CcEnumerator */

#ifdef CC_HAS_CCSLICE_CcEnumerator
CC_VEC_DECL_ARENA_TSLICE(CcEnumerator, CCVec_CcEnumerator, CCSlice_CcEnumerator)
#else
CC_VEC_DECL_ARENA(CcEnumerator, CCVec_CcEnumerator)
#endif
static inline CCVec_CcEnumerator cc__CCVec_CcEnumerator_new(CCArena __a) {
    return CCVec_CcEnumerator_init(__a, 0);
}
#define CCVec_CcEnumerator_new(ar) cc__CCVec_CcEnumerator_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcEnumerator (serdes) */
static const cc_type_info __cc_ti_CCVec_CcEnumerator = { .name = "CCVec_CcEnumerator", .mangled = "CCVec_CcEnumerator", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcEnumerator)), .align = (uint32_t)(_Alignof(CCVec_CcEnumerator)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcEnumerator(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcEnumerator);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcHookEntry
#define CC_HEADER_VEC_CCVec_CcHookEntry
/* generic CCVec_CcHookEntry */

#ifdef CC_HAS_CCSLICE_CcHookEntry
CC_VEC_DECL_ARENA_TSLICE(CcHookEntry, CCVec_CcHookEntry, CCSlice_CcHookEntry)
#else
CC_VEC_DECL_ARENA(CcHookEntry, CCVec_CcHookEntry)
#endif
static inline CCVec_CcHookEntry cc__CCVec_CcHookEntry_new(CCArena __a) {
    return CCVec_CcHookEntry_init(__a, 0);
}
#define CCVec_CcHookEntry_new(ar) cc__CCVec_CcHookEntry_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcHookEntry (serdes) */
static const cc_type_info __cc_ti_CCVec_CcHookEntry = { .name = "CCVec_CcHookEntry", .mangled = "CCVec_CcHookEntry", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcHookEntry)), .align = (uint32_t)(_Alignof(CCVec_CcHookEntry)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcHookEntry(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcHookEntry);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcViewItem
#define CC_HEADER_VEC_CCVec_CcViewItem
/* generic CCVec_CcViewItem */

#ifdef CC_HAS_CCSLICE_CcViewItem
CC_VEC_DECL_ARENA_TSLICE(CcViewItem, CCVec_CcViewItem, CCSlice_CcViewItem)
#else
CC_VEC_DECL_ARENA(CcViewItem, CCVec_CcViewItem)
#endif
static inline CCVec_CcViewItem cc__CCVec_CcViewItem_new(CCArena __a) {
    return CCVec_CcViewItem_init(__a, 0);
}
#define CCVec_CcViewItem_new(ar) cc__CCVec_CcViewItem_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcViewItem (serdes) */
static const cc_type_info __cc_ti_CCVec_CcViewItem = { .name = "CCVec_CcViewItem", .mangled = "CCVec_CcViewItem", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcViewItem)), .align = (uint32_t)(_Alignof(CCVec_CcViewItem)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcViewItem(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcViewItem);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcDesignator
#define CC_HEADER_VEC_CCVec_CcDesignator
/* generic CCVec_CcDesignator */

#ifdef CC_HAS_CCSLICE_CcDesignator
CC_VEC_DECL_ARENA_TSLICE(CcDesignator, CCVec_CcDesignator, CCSlice_CcDesignator)
#else
CC_VEC_DECL_ARENA(CcDesignator, CCVec_CcDesignator)
#endif
static inline CCVec_CcDesignator cc__CCVec_CcDesignator_new(CCArena __a) {
    return CCVec_CcDesignator_init(__a, 0);
}
#define CCVec_CcDesignator_new(ar) cc__CCVec_CcDesignator_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDesignator (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDesignator = { .name = "CCVec_CcDesignator", .mangled = "CCVec_CcDesignator", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDesignator)), .align = (uint32_t)(_Alignof(CCVec_CcDesignator)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDesignator(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDesignator);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcUnitRef
#define CC_HEADER_VEC_CCVec_CcUnitRef
/* generic CCVec_CcUnitRef */

#ifdef CC_HAS_CCSLICE_CcUnitRef
CC_VEC_DECL_ARENA_TSLICE(CcUnitRef, CCVec_CcUnitRef, CCSlice_CcUnitRef)
#else
CC_VEC_DECL_ARENA(CcUnitRef, CCVec_CcUnitRef)
#endif
static inline CCVec_CcUnitRef cc__CCVec_CcUnitRef_new(CCArena __a) {
    return CCVec_CcUnitRef_init(__a, 0);
}
#define CCVec_CcUnitRef_new(ar) cc__CCVec_CcUnitRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcUnitRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcUnitRef = { .name = "CCVec_CcUnitRef", .mangled = "CCVec_CcUnitRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcUnitRef)), .align = (uint32_t)(_Alignof(CCVec_CcUnitRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcUnitRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcUnitRef);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_int
#define CC_HEADER_VEC_CCVec_int
/* generic CCVec_int */

#ifdef CC_HAS_CCSLICE_int
CC_VEC_DECL_ARENA_TSLICE(int, CCVec_int, CCSlice_int)
#else
CC_VEC_DECL_ARENA(int, CCVec_int)
#endif
static inline CCVec_int cc__CCVec_int_new(CCArena __a) {
    return CCVec_int_init(__a, 0);
}
#define CCVec_int_new(ar) cc__CCVec_int_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_int (serdes) */
static const cc_type_info __cc_ti_CCVec_int = { .name = "CCVec_int", .mangled = "CCVec_int", .id = 0, .size = (uint32_t)(sizeof(CCVec_int)), .align = (uint32_t)(_Alignof(CCVec_int)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_int(void) {
    cc_type_info_register(&__cc_ti_CCVec_int);
}
#endif
#line 29 "cc/lower/index.cch"
 /* a prototype parameter must spell the list through a typedef */
#line 29 "cc/lower/index.cch"

#include <ccc/cc_result.h>

#line 29 "cc/lower/index.cch"
 /* a prototype parameter must spell the list through a typedef */
#line 29 "cc/lower/index.cch"
typedef CCVec_CCSlice CcNameList; /* a prototype parameter must spell the list through a typedef */
typedef CCVec_CcField CcFieldList; /* likewise inside a @switch case body */
typedef CCVec_CcEnumerator CcEnumeratorList;
typedef CCVec_CcHookEntry CcHookEntryList;
typedef CCVec_CcViewItem CcViewItemList;
typedef CCVec_CcDesignator CcDesignatorList;
typedef CCVec_CcUnitRef CcUnitList;
typedef CCVec_int CcIntList;

/* Internal records of the implementation, declared here so their list
 * instances are named where the extractor sees them. */
typedef struct CcIncludeRef {
    CCSlice path;
    bool quoted;
    uint32_t tok; /* the PP token, for the diagnostic position */
} CcIncludeRef;

#ifndef CC_HEADER_VEC_CCVec_CcIncludeRef
#define CC_HEADER_VEC_CCVec_CcIncludeRef
/* generic CCVec_CcIncludeRef */

#ifdef CC_HAS_CCSLICE_CcIncludeRef
CC_VEC_DECL_ARENA_TSLICE(CcIncludeRef, CCVec_CcIncludeRef, CCSlice_CcIncludeRef)
#else
CC_VEC_DECL_ARENA(CcIncludeRef, CCVec_CcIncludeRef)
#endif
static inline CCVec_CcIncludeRef cc__CCVec_CcIncludeRef_new(CCArena __a) {
    return CCVec_CcIncludeRef_init(__a, 0);
}
#define CCVec_CcIncludeRef_new(ar) cc__CCVec_CcIncludeRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcIncludeRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcIncludeRef = { .name = "CCVec_CcIncludeRef", .mangled = "CCVec_CcIncludeRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcIncludeRef)), .align = (uint32_t)(_Alignof(CCVec_CcIncludeRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcIncludeRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcIncludeRef);
}
#endif
#line 45 "cc/lower/index.cch"

#line 45 "cc/lower/index.cch"
typedef CCVec_CcIncludeRef CcIncludeRefList;
typedef struct CcSlotBind {
    CCSlice local;
    int arg;
} CcSlotBind;

#ifndef CC_HEADER_VEC_CCVec_CcSlotBind
#define CC_HEADER_VEC_CCVec_CcSlotBind
/* generic CCVec_CcSlotBind */

#ifdef CC_HAS_CCSLICE_CcSlotBind
CC_VEC_DECL_ARENA_TSLICE(CcSlotBind, CCVec_CcSlotBind, CCSlice_CcSlotBind)
#else
CC_VEC_DECL_ARENA(CcSlotBind, CCVec_CcSlotBind)
#endif
static inline CCVec_CcSlotBind cc__CCVec_CcSlotBind_new(CCArena __a) {
    return CCVec_CcSlotBind_init(__a, 0);
}
#define CCVec_CcSlotBind_new(ar) cc__CCVec_CcSlotBind_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcSlotBind (serdes) */
static const cc_type_info __cc_ti_CCVec_CcSlotBind = { .name = "CCVec_CcSlotBind", .mangled = "CCVec_CcSlotBind", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcSlotBind)), .align = (uint32_t)(_Alignof(CCVec_CcSlotBind)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcSlotBind(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcSlotBind);
}
#endif
#line 50 "cc/lower/index.cch"

#line 50 "cc/lower/index.cch"
typedef CCVec_CcSlotBind CcSlotBindList;

typedef enum CcSymKind {
#line 52 "cc/lower/index.cch"
    CC_SYM_FUNC = 1,
#line 52 "cc/lower/index.cch"
    CC_SYM_VAR,
#line 52 "cc/lower/index.cch"
    CC_SYM_TYPE,
#line 52 "cc/lower/index.cch"
    CC_SYM_ENUMERATOR,
#line 52 "cc/lower/index.cch"
    CC_SYM_MACRO
#line 52 "cc/lower/index.cch"
} CcSymKind;

typedef struct CcMacroDef CcMacroDef;
typedef struct CcSym CcSym;

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcSymptr_CcDiag_DEFINED
#define CCResult_CcSymptr_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcSymptr_CcDiag, CcSym *, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 56 "cc/lower/index.cch"

#line 56 "cc/lower/index.cch"
typedef struct CcHookReg CcHookReg;
typedef CcSym *CcSymRef;

#ifndef CC_HEADER_VEC_CCVec_CcSymRef
#define CC_HEADER_VEC_CCVec_CcSymRef
/* generic CCVec_CcSymRef */

#ifdef CC_HAS_CCSLICE_CcSymRef
CC_VEC_DECL_ARENA_TSLICE(CcSymRef, CCVec_CcSymRef, CCSlice_CcSymRef)
#else
CC_VEC_DECL_ARENA(CcSymRef, CCVec_CcSymRef)
#endif
static inline CCVec_CcSymRef cc__CCVec_CcSymRef_new(CCArena __a) {
    return CCVec_CcSymRef_init(__a, 0);
}
#define CCVec_CcSymRef_new(ar) cc__CCVec_CcSymRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcSymRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcSymRef = { .name = "CCVec_CcSymRef", .mangled = "CCVec_CcSymRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcSymRef)), .align = (uint32_t)(_Alignof(CCVec_CcSymRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcSymRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcSymRef);
}
#endif
#line 58 "cc/lower/index.cch"

#line 58 "cc/lower/index.cch"
typedef CCVec_CcSymRef CcSymList;
typedef CcMacroDef *CcMacroDefRef;
typedef CcHookReg *CcHookRegRef;

#ifndef CC_HEADER_VEC_CCVec_CcHookRegRef
#define CC_HEADER_VEC_CCVec_CcHookRegRef
/* generic CCVec_CcHookRegRef */

#ifdef CC_HAS_CCSLICE_CcHookRegRef
CC_VEC_DECL_ARENA_TSLICE(CcHookRegRef, CCVec_CcHookRegRef, CCSlice_CcHookRegRef)
#else
CC_VEC_DECL_ARENA(CcHookRegRef, CCVec_CcHookRegRef)
#endif
static inline CCVec_CcHookRegRef cc__CCVec_CcHookRegRef_new(CCArena __a) {
    return CCVec_CcHookRegRef_init(__a, 0);
}
#define CCVec_CcHookRegRef_new(ar) cc__CCVec_CcHookRegRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcHookRegRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcHookRegRef = { .name = "CCVec_CcHookRegRef", .mangled = "CCVec_CcHookRegRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcHookRegRef)), .align = (uint32_t)(_Alignof(CCVec_CcHookRegRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcHookRegRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcHookRegRef);
}
#endif
#line 61 "cc/lower/index.cch"

#line 61 "cc/lower/index.cch"
typedef CCVec_CcHookRegRef CcHookRegList;

/* A `#define`, as text: object-like or function-like, with its alternates
 * (the same name defined again under another `#if` branch). Bodies are
 * expanded for file-scope invocations so macro-made declarations
 * (CC_DECL_RESULT_SPEC, CC_DECL_SLICE, CC_MAP_DECL_ARENA ...) are indexed
 * like written ones. */
struct CcMacroDef {
    CCSlice name;
    bool function_like;
    bool variadic;
    CCVec_CCSlice params; /* function-like: parameter names */
    CCSlice body; /* body text, continuations joined, comments stripped; NUL-terminated */
    CcDecl *decl;
    CcUnit *unit;
    CcMacroDef *alt; /* next definition of the same name */
};

struct CcSym {
    CCSlice name;
    CcSymKind kind;
    CcDecl *decl; /* the declaring node, in this unit or a header unit */
    CcUnit *unit;
    CcType *type; /* function type / variable type / aliased type */
    bool is_header; /* declared by an included header (or a macro expansion of one) */
    bool is_definition; /* function with a body / struct with fields / macro with a body */
    CcMacroDef *macro; /* CC_SYM_MACRO: the parsed `#define` (all alternates) */
    CcSym *same_name; /* the symbol of another kind with this name, older first */
};

/* One rule read out of a `.ufcs` hook body: `if (method == "m") return
 * emit("callee")`, `case "m": return @slice("callee")`. */
typedef struct CcUfcsRule {
    CCSlice method;
    CCSlice callee;
    bool by_value; /* returned through cc_ufcs_emit_value* */
} CcUfcsRule;

#ifndef CC_HEADER_VEC_CCVec_CcUfcsRule
#define CC_HEADER_VEC_CCVec_CcUfcsRule
/* generic CCVec_CcUfcsRule */

#ifdef CC_HAS_CCSLICE_CcUfcsRule
CC_VEC_DECL_ARENA_TSLICE(CcUfcsRule, CCVec_CcUfcsRule, CCSlice_CcUfcsRule)
#else
CC_VEC_DECL_ARENA(CcUfcsRule, CCVec_CcUfcsRule)
#endif
static inline CCVec_CcUfcsRule cc__CCVec_CcUfcsRule_new(CCArena __a) {
    return CCVec_CcUfcsRule_init(__a, 0);
}
#define CCVec_CcUfcsRule_new(ar) cc__CCVec_CcUfcsRule_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcUfcsRule (serdes) */
static const cc_type_info __cc_ti_CCVec_CcUfcsRule = { .name = "CCVec_CcUfcsRule", .mangled = "CCVec_CcUfcsRule", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcUfcsRule)), .align = (uint32_t)(_Alignof(CCVec_CcUfcsRule)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcUfcsRule(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcUfcsRule);
}
#endif
#line 98 "cc/lower/index.cch"

#line 98 "cc/lower/index.cch"
typedef CCVec_CcUfcsRule CcUfcsRuleList;

/* A `@typehooks on Subject { ... }` registration. Subjects: an exact type
 * ("CCArena"), a pointer subject ("MyRes*"), a trailing-`*` family
 * ("Map_*"), or `*`. Empty slices mean "none". */
struct CcHookReg {
    CCSlice subject; /* as written */
    CCSlice base; /* subject without the trailing `*` (or `_*`) */
    bool any; /* `*` */
    bool family; /* `Base_*` */
    bool ptr; /* `Base*` */
    bool legacy; /* `cc_ufcs_register(pattern, fn)`: a `@typehooks` of the same subject wins */
    CcDecl *decl;
    CcUnit *unit;
    CCSlice create_fn; /* first create overload; "_new" style suffixes are kept as written */
    CCSlice create_fn2;
    CCSlice create_handler; /* `.create = cc_type_create_hook(fn)`: the handler that names the callee per site */
    void *create_callable; /* that handler, compiled */
    bool create_compile_tried; /* compiled once, or found not compilable; either way not again */
    CCSlice destroy_fn;
    CCSlice pre_destroy_fn;
    CCSlice ufcs_fn; /* handler name, or "<lambda>" */
    CcExpr *ufcs_value; /* the .ufcs expression */
    CCVec_CcUfcsRule rules; /* literal rules read from the handler body, latest first */
    CCSlice ufcs_prefix; /* `return concat("prefix_", method)`: composed callee prefix */
    bool ufcs_prefix_by_value;
    bool ufcs_rejects; /* default path returns the empty slice: no composition after the rules */
    bool ufcs_opaque; /* handler body could not be read as rules (computed names) */
    void *ufcs_callable; /* an opaque handler, compiled: called per site */
    bool ufcs_compile_tried; /* compiled once, or found not compilable; either way not again */
    bool has_len;
#line 128 "cc/lower/index.cch"
    bool has_access;
#line 128 "cc/lower/index.cch"
    bool has_cast;
#line 128 "cc/lower/index.cch"
    bool has_niche;
#line 128 "cc/lower/index.cch"
    bool has_sink;
    CCSlice cast_fn; /* .cast handler: the function a destination mints through */
    CCSlice len_kind; /* .len hook: "field" or "call", naming len_name */
    CCSlice len_name;
    CCSlice access_kind; /* .access hook: "load" or "call", naming access_name */
    CCSlice access_name;
    uint32_t niche_size;
#line 138 "cc/lower/index.cch"
    uint32_t niche_align;
    uint32_t niche_off;
    uint32_t niche_width;
    uint64_t niche_sentinel;
    CCSlice sink_fn; /* .ufcs_sink callee: unresolved methods lower to sink(&recv, "m", n, args...) */
    CCSlice sink_arg; /* the macro each argument is passed through, when the registration named one */
};

/* One entry of a type's method set. `callee` is the C function; `recv_by_ptr`
 * says whether the receiver is passed as `&recv`. `source` says where the
 * mapping came from, `origin` where it was read, for diagnostics. */
typedef struct CcMethod {
    CCSlice method;
    CCSlice callee;
    bool recv_by_ptr;
    CCSlice source; /* "typehooks", "DECL_UFCS", "Type_method", "cc_snake_method", "snake_method", "Result", "bare_name", "ufcs_sink" */
    CCSlice origin; /* the hook, registration or declaration site */
    CCSlice recv_path; /* `as:` faces walked to reach the callee's object, dot-joined ("file", "a.file"); empty when the receiver is it */
    CcSym *sym; /* the callee's declaration */
    CCSlice sink_arg; /* "ufcs_sink" only: the per-argument macro the registration named */
} CcMethod;

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcMethodptr_CcDiag_DEFINED
#define CCResult_CcMethodptr_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcMethodptr_CcDiag, CcMethod *, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 159 "cc/lower/index.cch"

#line 159 "cc/lower/index.cch"
typedef CcMethod *CcMethodRef;

#ifndef CC_HEADER_VEC_CCVec_CcMethodRef
#define CC_HEADER_VEC_CCVec_CcMethodRef
/* generic CCVec_CcMethodRef */

#ifdef CC_HAS_CCSLICE_CcMethodRef
CC_VEC_DECL_ARENA_TSLICE(CcMethodRef, CCVec_CcMethodRef, CCSlice_CcMethodRef)
#else
CC_VEC_DECL_ARENA(CcMethodRef, CCVec_CcMethodRef)
#endif
static inline CCVec_CcMethodRef cc__CCVec_CcMethodRef_new(CCArena __a) {
    return CCVec_CcMethodRef_init(__a, 0);
}
#define CCVec_CcMethodRef_new(ar) cc__CCVec_CcMethodRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcMethodRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcMethodRef = { .name = "CCVec_CcMethodRef", .mangled = "CCVec_CcMethodRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcMethodRef)), .align = (uint32_t)(_Alignof(CCVec_CcMethodRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcMethodRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcMethodRef);
}
#endif
#line 160 "cc/lower/index.cch"

#line 160 "cc/lower/index.cch"
typedef CCVec_CcMethodRef CcMethodList;

typedef struct CcTypeInfo {
    CCSlice name; /* canonical: "CCString", "Map_int_int", "CCResult_int_CCError" */
    CcSym *sym;
    CCVec_CcMethodRef methods; /* resolved so far (cache) */
    CCSlice destroy_fn; /* @typehooks .destroy; empty when none */
    CCSlice create_fn;
    CCSlice pre_destroy_fn;
    CcHookReg *hooks; /* the narrowest @typehooks registration that matches, or NULL */
    CcHookReg *create_hook; /* the narrowest registration whose `.create` is a handler, or NULL */
    CCSlice family; /* generic family for an instance ("Map" for Map_int_int); empty otherwise */
    CcTypeList targs; /* the instance's type arguments */
    CCSlice ufcs_registered_by; /* "CC_MAP_DECL_UFCS" when a *_DECL_UFCS(Name) names this type */
    bool instantiated; /* the family factory / spec macro has been expanded for it */
    bool is_result; /* CCResult_T_E */
    CcType *result_value;
    CcType *result_err;
    bool result_optional;
    bool result_from_header; /* spec declared by a header: do not re-emit */
    CcUnit *result_decl_unit; /* the unit whose CC_DECL_RESULT_SPEC declared it, or NULL */
    uint32_t result_decl_line;
} CcTypeInfo;

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcTypeInfoptr_CcDiag_DEFINED
#define CCResult_CcTypeInfoptr_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcTypeInfoptr_CcDiag, CcTypeInfo *, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 183 "cc/lower/index.cch"

#line 183 "cc/lower/index.cch"
typedef CcTypeInfo *CcTypeInfoRef;

#ifndef CC_HEADER_VEC_CCVec_CcTypeInfoRef
#define CC_HEADER_VEC_CCVec_CcTypeInfoRef
/* generic CCVec_CcTypeInfoRef */

#ifdef CC_HAS_CCSLICE_CcTypeInfoRef
CC_VEC_DECL_ARENA_TSLICE(CcTypeInfoRef, CCVec_CcTypeInfoRef, CCSlice_CcTypeInfoRef)
#else
CC_VEC_DECL_ARENA(CcTypeInfoRef, CCVec_CcTypeInfoRef)
#endif
static inline CCVec_CcTypeInfoRef cc__CCVec_CcTypeInfoRef_new(CCArena __a) {
    return CCVec_CcTypeInfoRef_init(__a, 0);
}
#define CCVec_CcTypeInfoRef_new(ar) cc__CCVec_CcTypeInfoRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcTypeInfoRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcTypeInfoRef = { .name = "CCVec_CcTypeInfoRef", .mangled = "CCVec_CcTypeInfoRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcTypeInfoRef)), .align = (uint32_t)(_Alignof(CCVec_CcTypeInfoRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcTypeInfoRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcTypeInfoRef);
}
#endif
#line 184 "cc/lower/index.cch"

#line 184 "cc/lower/index.cch"
typedef CCVec_CcTypeInfoRef CcTypeInfoList;

/* One unit's spelling of a Result box, as first written: whether the ok
 * type carried `const`, and where. Qualifiers are not part of the box, so
 * a later spelling that disagrees is told so, once. */
typedef struct CcResultQual {
    CCSlice name; /* the box: CCResult_<ok>_<err> */
    bool is_const;
    bool warned;
    CcUnit *unit;
    CcSpan span;
} CcResultQual;

#ifndef CC_HEADER_VEC_CCVec_CcResultQual
#define CC_HEADER_VEC_CCVec_CcResultQual
/* generic CCVec_CcResultQual */

#ifdef CC_HAS_CCSLICE_CcResultQual
CC_VEC_DECL_ARENA_TSLICE(CcResultQual, CCVec_CcResultQual, CCSlice_CcResultQual)
#else
CC_VEC_DECL_ARENA(CcResultQual, CCVec_CcResultQual)
#endif
static inline CCVec_CcResultQual cc__CCVec_CcResultQual_new(CCArena __a) {
    return CCVec_CcResultQual_init(__a, 0);
}
#define CCVec_CcResultQual_new(ar) cc__CCVec_CcResultQual_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcResultQual (serdes) */
static const cc_type_info __cc_ti_CCVec_CcResultQual = { .name = "CCVec_CcResultQual", .mangled = "CCVec_CcResultQual", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcResultQual)), .align = (uint32_t)(_Alignof(CCVec_CcResultQual)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcResultQual(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcResultQual);
}
#endif
#ifndef CC_HEADER_MAP_Map_CCSlice_CcSymRef
#define CC_HEADER_MAP_Map_CCSlice_CcSymRef
/* generic Map_CCSlice_CcSymRef */

#include <ccc/std/map.h>
#ifdef CC_MAP_HASH_CCSlice
#define Map_CCSlice_CcSymRef_key_hash CC_MAP_HASH_CCSlice
#define Map_CCSlice_CcSymRef_key_eq CC_MAP_EQ_CCSlice
#else
static size_t cc_map_key_hash_CCSlice(CCSlice);
static int cc_map_key_eq_CCSlice(CCSlice, CCSlice);
#define Map_CCSlice_CcSymRef_key_hash cc_map_key_hash_CCSlice
#define Map_CCSlice_CcSymRef_key_eq cc_map_key_eq_CCSlice
#endif
CC_MAP_DECL_ARENA(CCSlice, CcSymRef, Map_CCSlice_CcSymRef, Map_CCSlice_CcSymRef_key_hash, Map_CCSlice_CcSymRef_key_eq)
static inline Map_CCSlice_CcSymRef *cc__Map_CCSlice_CcSymRef_new(CCArena __a) {
    return Map_CCSlice_CcSymRef_init(__a);
}
#define Map_CCSlice_CcSymRef_new(ar) cc__Map_CCSlice_CcSymRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for Map_CCSlice_CcSymRef (serdes) */
static const cc_type_info __cc_ti_Map_CCSlice_CcSymRef = { .name = "Map_CCSlice_CcSymRef", .mangled = "Map_CCSlice_CcSymRef", .id = 0, .size = (uint32_t)(sizeof(Map_CCSlice_CcSymRef)), .align = (uint32_t)(_Alignof(Map_CCSlice_CcSymRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_Map_CCSlice_CcSymRef(void) {
    cc_type_info_register(&__cc_ti_Map_CCSlice_CcSymRef);
}
#endif
#ifndef CC_HEADER_MAP_Map_CCSlice_CcTypeInfoRef
#define CC_HEADER_MAP_Map_CCSlice_CcTypeInfoRef
/* generic Map_CCSlice_CcTypeInfoRef */

#include <ccc/std/map.h>
#ifdef CC_MAP_HASH_CCSlice
#define Map_CCSlice_CcTypeInfoRef_key_hash CC_MAP_HASH_CCSlice
#define Map_CCSlice_CcTypeInfoRef_key_eq CC_MAP_EQ_CCSlice
#else
static size_t cc_map_key_hash_CCSlice(CCSlice);
static int cc_map_key_eq_CCSlice(CCSlice, CCSlice);
#define Map_CCSlice_CcTypeInfoRef_key_hash cc_map_key_hash_CCSlice
#define Map_CCSlice_CcTypeInfoRef_key_eq cc_map_key_eq_CCSlice
#endif
CC_MAP_DECL_ARENA(CCSlice, CcTypeInfoRef, Map_CCSlice_CcTypeInfoRef, Map_CCSlice_CcTypeInfoRef_key_hash, Map_CCSlice_CcTypeInfoRef_key_eq)
static inline Map_CCSlice_CcTypeInfoRef *cc__Map_CCSlice_CcTypeInfoRef_new(CCArena __a) {
    return Map_CCSlice_CcTypeInfoRef_init(__a);
}
#define Map_CCSlice_CcTypeInfoRef_new(ar) cc__Map_CCSlice_CcTypeInfoRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for Map_CCSlice_CcTypeInfoRef (serdes) */
static const cc_type_info __cc_ti_Map_CCSlice_CcTypeInfoRef = { .name = "Map_CCSlice_CcTypeInfoRef", .mangled = "Map_CCSlice_CcTypeInfoRef", .id = 0, .size = (uint32_t)(sizeof(Map_CCSlice_CcTypeInfoRef)), .align = (uint32_t)(_Alignof(Map_CCSlice_CcTypeInfoRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_Map_CCSlice_CcTypeInfoRef(void) {
    cc_type_info_register(&__cc_ti_Map_CCSlice_CcTypeInfoRef);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcDeclRef
#define CC_HEADER_VEC_CCVec_CcDeclRef
/* generic CCVec_CcDeclRef */

#ifdef CC_HAS_CCSLICE_CcDeclRef
CC_VEC_DECL_ARENA_TSLICE(CcDeclRef, CCVec_CcDeclRef, CCSlice_CcDeclRef)
#else
CC_VEC_DECL_ARENA(CcDeclRef, CCVec_CcDeclRef)
#endif
static inline CCVec_CcDeclRef cc__CCVec_CcDeclRef_new(CCArena __a) {
    return CCVec_CcDeclRef_init(__a, 0);
}
#define CCVec_CcDeclRef_new(ar) cc__CCVec_CcDeclRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDeclRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDeclRef = { .name = "CCVec_CcDeclRef", .mangled = "CCVec_CcDeclRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDeclRef)), .align = (uint32_t)(_Alignof(CCVec_CcDeclRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDeclRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDeclRef);
}
#endif
#ifndef CC_HEADER_MAP_Map_uint64_t_CCSlice
#define CC_HEADER_MAP_Map_uint64_t_CCSlice
/* generic Map_uint64_t_CCSlice */

#include <ccc/std/map.h>
#ifdef CC_MAP_HASH_uint64_t
#define Map_uint64_t_CCSlice_key_hash CC_MAP_HASH_uint64_t
#define Map_uint64_t_CCSlice_key_eq CC_MAP_EQ_uint64_t
#else
static size_t cc_map_key_hash_uint64_t(...);
static int cc_map_key_eq_uint64_t(..., ...);
#define Map_uint64_t_CCSlice_key_hash cc_map_key_hash_uint64_t
#define Map_uint64_t_CCSlice_key_eq cc_map_key_eq_uint64_t
#endif
CC_MAP_DECL_ARENA(uint64_t, CCSlice, Map_uint64_t_CCSlice, Map_uint64_t_CCSlice_key_hash, Map_uint64_t_CCSlice_key_eq)
static inline Map_uint64_t_CCSlice *cc__Map_uint64_t_CCSlice_new(CCArena __a) {
    return Map_uint64_t_CCSlice_init(__a);
}
#define Map_uint64_t_CCSlice_new(ar) cc__Map_uint64_t_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for Map_uint64_t_CCSlice (serdes) */
static const cc_type_info __cc_ti_Map_uint64_t_CCSlice = { .name = "Map_uint64_t_CCSlice", .mangled = "Map_uint64_t_CCSlice", .id = 0, .size = (uint32_t)(sizeof(Map_uint64_t_CCSlice)), .align = (uint32_t)(_Alignof(Map_uint64_t_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_Map_uint64_t_CCSlice(void) {
    cc_type_info_register(&__cc_ti_Map_uint64_t_CCSlice);
}
#endif
#line 196 "cc/lower/index.cch"

#line 196 "cc/lower/index.cch"
typedef CCVec_CcResultQual CcResultQualList;

typedef struct CcIndex {
    CCArena arena;
    CcDiags *ds;
    CCVec_CcUnitRef units; /* the unit plus each header unit, include order */
    CCVec_int unit_is_header; /* parallel to units */
    Map_CCSlice_CcSymRef *sym_heads; /* name -> newest symbol of that name (chain: same_name) */
    Map_CCSlice_CcTypeInfoRef *type_map;
    CCVec_CcTypeInfoRef result_specs; /* first-use order */
    CcResultQualList result_quals; /* per box, the first spelling in a non-header unit */
#line 208 "cc/lower/index.cch"
    CCVec_CcSymRef syms; /* every symbol, in declaration order */
    CCVec_CcTypeInfoRef types; /* every type info, in creation order */
    CCVec_CcHookRegRef hooks; /* every @typehooks registration, in declaration order */
    CCVec_CcDeclRef factories; /* CC_GENERIC_FACTORY declarations */
    CCVec_CcUnitRef factory_units;
    CCVec_CcDeclRef variants; /* the variant declarations, in index order (a header's before its includer's) */
    CCVec_CcUnitRef variant_units;
    CCVec_CCSlice typedef_names; /* for the parser's known_types */
    CCVec_CCSlice loaded_paths; /* canonical paths of loaded headers */
    CCVec_CCSlice loading_paths; /* headers whose includes are being loaded (cycle guard) */
    Map_uint64_t_CCSlice *value_spellings; /* a value type argument node -> its source text */
    CCVec_CCSlice include_dirs; /* search path for <...> and "..." */
    CCSlice quote_dir; /* directory of the unit for "..." includes; empty when none */
#line 226 "cc/lower/index.cch"
    CCSlice peer_dir;
    CCVec_CCSlice peer_names;
    CCVec_CCSlice peer_paths;
    int expansion_depth; /* nesting of macro / factory expansions being indexed */
    uint32_t n_expansions;
    uint32_t n_expansion_errors; /* parse errors inside expansions (not reported as diagnostics) */
} CcIndex;

CcIndex *cc_index_new(CCVec_CCSlice include_dirs, CCSlice quote_dir, CcDiags *ds, CCArena a);

/* ix.add_unit(u, is_header): declarations only for headers. */
void CcIndex_add_unit(CcIndex *ix, CcUnit *u, bool is_header);
/* ix.load_includes(u, opts): resolve the `#include` lines naming `.cch`
 * files, parse each once, add them. System headers are not read: C names
 * the lowerer does not reason about stay C. A `.cch` that cannot be found
 * or read is an error at the include line. */
void CcIndex_load_includes(CcIndex *ix, CcUnit *u, CcParseOpts opts);
/* Same, from a lexed file that is not parsed yet: lets the driver load the
 * headers of a unit before parsing the unit itself, so the parser sees
 * every typedef name from the headers. */
void CcIndex_preload_includes(CcIndex *ix, const CcTape *tape, CcParseOpts opts);
/* ix.peer_face(dir, name): the `.cch` in `dir` that declares `name`, or an
 * empty slice when none does. */
CCSlice CcIndex_peer_face(CcIndex *ix, CCSlice dir, CCSlice name);
/* ix.known_types(): every typedef name the index knows, for CcParseOpts.known_types. */
CCVec_CCSlice CcIndex_known_types(CcIndex *ix);

/* Lookups. A miss is a Result error carrying the position-less reason;
 * the caller attaches the use site. */
CCResult_CcSymptr_CcDiag CcIndex_sym(CcIndex *ix, CCSlice name);
CCResult_CcTypeInfoptr_CcDiag CcIndex_type(CcIndex *ix, CCSlice canonical);
/* ix.type_get(canonical): the type info, created on first use (with its
 * hooks, family instantiation and registrations resolved). */
CcTypeInfo *CcIndex_type_get(CcIndex *ix, CCSlice canonical);
/* ix.canon(t): canonical spelling of a type node, into the index arena:
 * "int", "unsigned long", "struct Foo", "CCString", "CCResult_int_CCError",
 * "Map_int_int", "CCSlice" for char[:]. */
CCSlice CcIndex_canon(CcIndex *ix, const CcType *t);
/* How the receiver is written at the call site, for the bare-name tier.
 * CC_RECV_PTR: the receiver expression is a pointer; CC_RECV_CONST: what it
 * names is const. */
#define CC_RECV_PTR   1u
#define CC_RECV_CONST 2u
/* ix.method_recv(recv, name, shape, a): the method, or an error whose message
 * lists what was tried and what the type has, ready for the use site. */
CCResult_CcMethodptr_CcDiag CcIndex_method_recv(CcIndex *ix, CcTypeInfo *recv, CCSlice method, unsigned int recv_shape, CCArena a);
/* ix.methods_of(info): every method the type has, from every source, for
 * dumps and for the candidates list. */
CcMethodList CcIndex_methods_of(CcIndex *ix, CcTypeInfo *info);
/* ix.result(value, err, optional): register the spec and return its info;
 * the printer emits every entry not declared by a header, once. */
CcTypeInfo *CcIndex_result(CcIndex *ix, CcType *value, CcType *err, bool optional);
/* ix.arena_param(f): which parameter of `f` is its arena (attribute on the
 * declaration, or the trailing CCArena parameter); -1 when none. */
int CcIndex_arena_param(CcIndex *ix, CcSym *f);
/* ix.expand_call(u, sp): expand a function-like macro invocation
 * `NAME(args)` spanning `sp` in `u` with its `#define`; an empty slice when
 * NAME is not a known function-like macro. Lets a caller learn what a
 * statement-level macro (`cc_arena_stack(a, n)`) declares. */
CCSlice CcIndex_expand_call(CcIndex *ix, const CcUnit *u, CcSpan sp);
/* ix.snake(type_name): `cc_<snake>` spelling: "CCJsVal" -> "cc_js_val", "RedisConn" -> "redis_conn". */
CCSlice CcIndex_snake(CcIndex *ix, CCSlice type_name);
/* s.loc(): logical location of a symbol's declaration. */
CcLoc CcSym_loc(const CcSym *s);
/* s.noreturn(): does a call to this function never return (`_Noreturn`,
 * `noreturn` attribute, a macro that spells one)? */
bool CcSym_noreturn(const CcSym *s);


typedef CcIndex CcIndex_Restrict_Read;
#line 294 "cc/lower/index.cch"


#endif
