#line 1 "cc/lower/cclex.ccs"

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 1 "cc/lower/cclex.ccs"

#line 1 "cc/lower/cclex.ccs"
/* cclex: exercise the lexer on real files. Same modes and output as the
 * C11 tool (lex_test.c), so the two can be diffed.
 *
 *   cclex --roundtrip FILE...   every byte belongs to exactly one token; the
 *                               concatenation of lead + text must be the
 *                               file. Also rejects CC_TK_ERROR tokens and a
 *                               NUMBER containing `..`. Exit 1 on any failure.
 *   cclex --dump FILE           one token per line: `line:col kind text`
 *   cclex --loc FILE OFF        logical location of byte offset OFF */

#include "lower.h"
#line 10 "cc/lower/cclex.ccs"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#include <ccc/cc_result.h>

#line 16 "cc/lower/cclex.ccs"

#line 16 "cc/lower/cclex.ccs"
static const char *kind_name(CcTokKind k) {
    switch (k) {
        case CC_TK_EOF:
#line 18 "cc/lower/cclex.ccs"
            return "EOF";
        case CC_TK_IDENT:
#line 19 "cc/lower/cclex.ccs"
            return "IDENT";
        case CC_TK_AT_WORD:
#line 20 "cc/lower/cclex.ccs"
            return "AT_WORD";
        case CC_TK_AT:
#line 21 "cc/lower/cclex.ccs"
            return "AT";
        case CC_TK_NUMBER:
#line 22 "cc/lower/cclex.ccs"
            return "NUMBER";
        case CC_TK_CHAR:
#line 23 "cc/lower/cclex.ccs"
            return "CHAR";
        case CC_TK_STRING:
#line 24 "cc/lower/cclex.ccs"
            return "STRING";
        case CC_TK_TEMPLATE:
#line 25 "cc/lower/cclex.ccs"
            return "TEMPLATE";
        case CC_TK_PUNCT:
#line 26 "cc/lower/cclex.ccs"
            return "PUNCT";
        case CC_TK_PP:
#line 27 "cc/lower/cclex.ccs"
            return "PP";
        case CC_TK_ERROR:
#line 28 "cc/lower/cclex.ccs"
            return "ERROR";
    }
    return "?";
}

/* One lexed file: the tool's unit. */
typedef struct LexRun {
    CCSlice path;
    CCSlice src;
    CcDiags ds;
    CcTape tape;
    bool ok;
} LexRun;

static LexRun lex_path(const char *path_c, CCArena a) {
    LexRun run;
    run.path = cc_slice_cstr(path_c);
    run.src = cc_slice_empty();
    run.ds = CcDiags_new(a);
    run.ok = false;
    CCFile f;
#line 48 "cc/lower/cclex.ccs"
    {
#line 48 "cc/lower/cclex.ccs"
        __typeof__(cc_file_open(run.path)) __r = cc_file_open(run.path);
#line 48 "cc/lower/cclex.ccs"
        if (!__r.ok) {
#line 48 "cc/lower/cclex.ccs"
            CCIoError e = __r.u.error;
#line 48 "cc/lower/cclex.ccs"
            {
                fprintf(stderr, "cclex: %s: %s\n", path_c, cc_io_error_str(e));
                return run;
            }
#line 51 "cc/lower/cclex.ccs"
        }
#line 48 "cc/lower/cclex.ccs"
        f = __r.u.value;
#line 48 "cc/lower/cclex.ccs"
    }
#line 52 "cc/lower/cclex.ccs"
    {
#line 52 "cc/lower/cclex.ccs"
        __typeof__(cc_file_read_all(&f, a)) __r = cc_file_read_all(&f, a);
#line 52 "cc/lower/cclex.ccs"
        if (!__r.ok) {
#line 52 "cc/lower/cclex.ccs"
            __typeof__(__r.u.error) e = __r.u.error;
#line 52 "cc/lower/cclex.ccs"
            {
                cc_file_close(&f);
                fprintf(stderr, "cclex: %s: %s\n", path_c, cc_io_error_str(e));
                return run;
            }
#line 56 "cc/lower/cclex.ccs"
        }
#line 52 "cc/lower/cclex.ccs"
        run.src = __r.u.value;
#line 52 "cc/lower/cclex.ccs"
    }
#line 57 "cc/lower/cclex.ccs"
    cc_file_close(&f);
    run.tape = cc_lex(run.path, run.src, &run.ds, a);
    run.ok = true;
    return run;
}

/* The diag printer's source callback: this run's text for its own path. */
static CCSlice run_source(CCSlice path, void *ctx, bool *physical) {
    LexRun *run = (LexRun *)(ctx);
    *physical = true;
    if (CCSlice_eq(&path, run->path))
#line 67 "cc/lower/cclex.ccs"
        return run->src;
    return cc_slice_empty();
}

/* Escape a token's text so it fits on one output line. */
static void print_escaped(CCSlice text) {
    const unsigned char *s = (const unsigned char *)(text.ptr);
    for (size_t i = 0; i < text.len; i++) {
        unsigned char c = s[i];
        switch (c) {
            case '\n':
#line 77 "cc/lower/cclex.ccs"
                fputs("\\n", stdout);
#line 77 "cc/lower/cclex.ccs"
                break;
            case '\r':
#line 78 "cc/lower/cclex.ccs"
                fputs("\\r", stdout);
#line 78 "cc/lower/cclex.ccs"
                break;
            case '\t':
#line 79 "cc/lower/cclex.ccs"
                fputs("\\t", stdout);
#line 79 "cc/lower/cclex.ccs"
                break;
            case '\\':
#line 80 "cc/lower/cclex.ccs"
                fputs("\\\\", stdout);
#line 80 "cc/lower/cclex.ccs"
                break;
            default:
                if (c < 0x20 || c == 0x7f)
#line 82 "cc/lower/cclex.ccs"
                    printf("\\x%02x", c);
#line 82 "cc/lower/cclex.ccs"
                else
                    fputc(c, stdout);
        }
    }
}

static bool has_dotdot(CCSlice text) {
    const char *s = (const char *)(text.ptr);
    for (size_t i = 1; i < text.len; i++)
        if (s[i - 1] == '.' && s[i] == '.')
#line 91 "cc/lower/cclex.ccs"
            return true;
    return false;
}

static uint32_t offset_of(const LexRun *run, CCSlice s) {
    return (uint32_t)((const char *)(s.ptr) - (const char *)(run->src.ptr));
}

static bool check_tokens(LexRun *run, bool *had_error_tok) {
    CcTape *tp = &run->tape;
    uint32_t n = (uint32_t)(CCVec_CcToken_len(&tp->toks));
    uint32_t len = (uint32_t)(run->src.len);
    const char *path = (const char *)(run->path.ptr);
    bool ok = true;
    if (n == 0 || CCVec_CcToken_get_ptr(&tp->toks, n - 1)->kind != CC_TK_EOF) {
        printf("MISMATCH %s: token stream does not end in EOF\n", path);
        return false;
    }
    for (uint32_t i = 0; i < n; i++) {
        const CcToken *t = CCVec_CcToken_get_ptr(&tp->toks, i);
        uint32_t lead_off = offset_of(run, t->lead);
        uint32_t off = offset_of(run, t->text);
        uint32_t expect = 0;
        if (i > 0) {
            const CcToken *prev = CCVec_CcToken_get_ptr(&tp->toks, i - 1);
            expect = offset_of(run, prev->text) + (uint32_t)(prev->text.len);
        }
        if (lead_off != expect || lead_off + t->lead.len != off || off + t->text.len > len) {
            printf("MISMATCH %s at byte %u (token %u: lead %u+%u, text %u+%u)\n", path, (unsigned int)(expect), (unsigned int)(i), (unsigned int)(lead_off), (unsigned int)(t->lead.len), (unsigned int)(off), (unsigned int)(t->text.len));
#line 122 "cc/lower/cclex.ccs"
            return false;
        }
        if (t->kind == CC_TK_ERROR) {
            *had_error_tok = true;
            ok = false;
        }
        if (t->kind == CC_TK_NUMBER && has_dotdot(t->text)) {
            printf("BADNUM %s at byte %u: NUMBER text contains `..`: ", path, (unsigned int)(off));
            print_escaped(t->text);
            putchar('\n');
            ok = false;
        }
    }
    const CcToken *eof = CCVec_CcToken_get_ptr(&tp->toks, n - 1);
    if (offset_of(run, eof->text) != len || eof->text.len != 0) {
        printf("MISMATCH %s at byte %u: EOF token does not end at the file end (%u)\n", path, (unsigned int)(offset_of(run, eof->text)), (unsigned int)(len));
#line 139 "cc/lower/cclex.ccs"
        return false;
    }
    return ok;
}

static bool roundtrip(const char *path) {
    bool __cc_retval;
#line 145 "cc/lower/cclex.ccs"
    int __cc_defer_on_1 = 0;
#line 145 "cc/lower/cclex.ccs"
    CCArena a = cc_arena_heap(kilobytes(64));
#line 145 "cc/lower/cclex.ccs"
    __cc_defer_on_1 = 1;
    LexRun run = lex_path(path, a);
    if (!run.ok) {
#line 147 "cc/lower/cclex.ccs"
        __cc_retval = false;
#line 147 "cc/lower/cclex.ccs"
        goto __cc_cleanup;
#line 147 "cc/lower/cclex.ccs"
    }
    bool ok = true;
#line 148 "cc/lower/cclex.ccs"
    bool had_error_tok = false;
    CcTape *tp = &run.tape;
    CCString out = cc_string_new();
    {
#line 151 "cc/lower/cclex.ccs"
        size_t __cc_fn_0 = (tp->toks).len;
#line 151 "cc/lower/cclex.ccs"
        CcToken *__cc_fp_0 = (CcToken *)((tp->toks).data);
#line 151 "cc/lower/cclex.ccs"
        size_t __cc_fi_1;
#line 151 "cc/lower/cclex.ccs"
        for (__cc_fi_1 = 0; __cc_fi_1 < __cc_fn_0; ++__cc_fi_1) {
#line 151 "cc/lower/cclex.ccs"
            CcToken t = (__cc_fp_0)[__cc_fi_1];
#line 151 "cc/lower/cclex.ccs"
            {
                cc_string_push_slice(&out, t.lead, a);
                cc_string_push_slice(&out, t.text, a);
            }
#line 154 "cc/lower/cclex.ccs"
        }
#line 154 "cc/lower/cclex.ccs"
    }
    CCSlice got = cc_string_as_slice(&out);
    if (got.len != run.src.len || !CCSlice_eq(&got, run.src)) {
        const char *x = (const char *)(got.ptr);
        const char *y = (const char *)(run.src.ptr);
        size_t n = 0;
        while (n < got.len && n < run.src.len && x[n] == y[n])
#line 160 "cc/lower/cclex.ccs"
            n++;
        printf("MISMATCH %s at byte %zu\n", path, n);
        ok = false;
    } else if (!check_tokens(&run, &had_error_tok)) {
        ok = false;
    }
    if (had_error_tok)
#line 166 "cc/lower/cclex.ccs"
        printf("ERROR %s: stream contains CC_TK_ERROR tokens\n", path);
    if (CCVec_CcDiag_len(&run.ds.items)) {
        fflush(stdout);
        CcDiags_print(&run.ds, stderr, run_source, &run);
    }
    if (CcDiags_has_errors(&run.ds))
#line 171 "cc/lower/cclex.ccs"
        ok = false;
    if (ok)
#line 172 "cc/lower/cclex.ccs"
        printf("ok %s\n", path);
    {
#line 173 "cc/lower/cclex.ccs"
        __cc_retval = ok;
#line 173 "cc/lower/cclex.ccs"
        goto __cc_cleanup;
#line 173 "cc/lower/cclex.ccs"
    }
#line 173 "cc/lower/cclex.ccs"
    __cc_cleanup:;
#line 173 "cc/lower/cclex.ccs"
    {
#line 145 "cc/lower/cclex.ccs"
        if (__cc_defer_on_1) {
#line 145 "cc/lower/cclex.ccs"
            {
#line 145 "cc/lower/cclex.ccs"
                cc_arena_destroy(&a);
#line 145 "cc/lower/cclex.ccs"
            }
#line 145 "cc/lower/cclex.ccs"
        }
#line 173 "cc/lower/cclex.ccs"
        return __cc_retval;
#line 173 "cc/lower/cclex.ccs"
    }
}

static int dump(const char *path) {
    int __cc_retval;
#line 177 "cc/lower/cclex.ccs"
    int __cc_defer_on_1 = 0;
#line 177 "cc/lower/cclex.ccs"
    CCArena a = cc_arena_heap(kilobytes(64));
#line 177 "cc/lower/cclex.ccs"
    __cc_defer_on_1 = 1;
    LexRun run = lex_path(path, a);
    if (!run.ok) {
#line 179 "cc/lower/cclex.ccs"
        __cc_retval = 1;
#line 179 "cc/lower/cclex.ccs"
        goto __cc_cleanup;
#line 179 "cc/lower/cclex.ccs"
    }
    CcTape *tp = &run.tape;
    {
#line 181 "cc/lower/cclex.ccs"
        size_t __cc_fn_2 = (tp->toks).len;
#line 181 "cc/lower/cclex.ccs"
        CcToken *__cc_fp_2 = (CcToken *)((tp->toks).data);
#line 181 "cc/lower/cclex.ccs"
        size_t __cc_fi_3;
#line 181 "cc/lower/cclex.ccs"
        for (__cc_fi_3 = 0; __cc_fi_3 < __cc_fn_2; ++__cc_fi_3) {
#line 181 "cc/lower/cclex.ccs"
            CcToken t = (__cc_fp_2)[__cc_fi_3];
#line 181 "cc/lower/cclex.ccs"
            {
                printf("%u:%u %s", (unsigned int)(t.line), (unsigned int)(t.col), kind_name(t.kind));
                if (t.kind == CC_TK_PUNCT)
#line 183 "cc/lower/cclex.ccs"
                    printf("(%s)", cc__punct_text(t.punct));
                putchar(' ');
                print_escaped(t.text);
                putchar('\n');
            }
#line 187 "cc/lower/cclex.ccs"
        }
#line 187 "cc/lower/cclex.ccs"
    }
    {
#line 188 "cc/lower/cclex.ccs"
        size_t __cc_fn_4 = (tp->marks).len;
#line 188 "cc/lower/cclex.ccs"
        CcLineMark *__cc_fp_4 = (CcLineMark *)((tp->marks).data);
#line 188 "cc/lower/cclex.ccs"
        size_t __cc_fi_5;
#line 188 "cc/lower/cclex.ccs"
        for (__cc_fi_5 = 0; __cc_fi_5 < __cc_fn_4; ++__cc_fi_5) {
#line 188 "cc/lower/cclex.ccs"
            CcLineMark m = (__cc_fp_4)[__cc_fi_5];
#line 188 "cc/lower/cclex.ccs"
            {
                printf("mark off=%u phys=%u logical=%u path=", (unsigned int)(m.off), (unsigned int)(m.phys_line), (unsigned int)(m.logical_line));
#line 191 "cc/lower/cclex.ccs"
                if (m.path.len)
#line 191 "cc/lower/cclex.ccs"
                    fwrite(m.path.ptr, 1, m.path.len, stdout);
#line 191 "cc/lower/cclex.ccs"
                else
                    fputs("(file)", stdout);
                putchar('\n');
            }
#line 194 "cc/lower/cclex.ccs"
        }
#line 194 "cc/lower/cclex.ccs"
    }
    fflush(stdout);
    CcDiags_print(&run.ds, stderr, run_source, &run);
    {
#line 197 "cc/lower/cclex.ccs"
        __cc_retval = CcDiags_has_errors(&run.ds) ? 1 : 0;
#line 197 "cc/lower/cclex.ccs"
        goto __cc_cleanup;
#line 197 "cc/lower/cclex.ccs"
    }
#line 197 "cc/lower/cclex.ccs"
    __cc_cleanup:;
#line 197 "cc/lower/cclex.ccs"
    {
#line 177 "cc/lower/cclex.ccs"
        if (__cc_defer_on_1) {
#line 177 "cc/lower/cclex.ccs"
            {
#line 177 "cc/lower/cclex.ccs"
                cc_arena_destroy(&a);
#line 177 "cc/lower/cclex.ccs"
            }
#line 177 "cc/lower/cclex.ccs"
        }
#line 197 "cc/lower/cclex.ccs"
        return __cc_retval;
#line 197 "cc/lower/cclex.ccs"
    }
}

static int loc(const char *path, const char *off_text) {
    int __cc_retval;
#line 209 "cc/lower/cclex.ccs"
    int __cc_defer_on_1 = 0;
#line 201 "cc/lower/cclex.ccs"
    char *end;
    unsigned long off;
    errno = 0;
    off = strtoul(off_text, &end, 10);
    if (errno || *end || end == off_text) {
        fprintf(stderr, "cclex: bad offset '%s'\n", off_text);
        {
#line 207 "cc/lower/cclex.ccs"
            __cc_retval = 2;
#line 207 "cc/lower/cclex.ccs"
            goto __cc_cleanup;
#line 207 "cc/lower/cclex.ccs"
        }
    }
    CCArena a = cc_arena_heap(kilobytes(64));
#line 209 "cc/lower/cclex.ccs"
    __cc_defer_on_1 = 1;
    LexRun run = lex_path(path, a);
    if (!run.ok) {
#line 211 "cc/lower/cclex.ccs"
        __cc_retval = 1;
#line 211 "cc/lower/cclex.ccs"
        goto __cc_cleanup;
#line 211 "cc/lower/cclex.ccs"
    }
    if (off > run.src.len) {
        fprintf(stderr, "cclex: offset %lu past end of %s (%u bytes)\n", off, path, (unsigned int)(run.src.len));
        {
#line 214 "cc/lower/cclex.ccs"
            __cc_retval = 2;
#line 214 "cc/lower/cclex.ccs"
            goto __cc_cleanup;
#line 214 "cc/lower/cclex.ccs"
        }
    }
    CcLoc l = cc__tape_loc_of(&run.tape, (uint32_t)(off));
    printf("%.*s:%u:%u\n", (int)(l.path.len), (const char *)(l.path.ptr), (unsigned int)(l.line), (unsigned int)(l.col));
    CcDiags_print(&run.ds, stderr, run_source, &run);
    {
#line 219 "cc/lower/cclex.ccs"
        __cc_retval = 0;
#line 219 "cc/lower/cclex.ccs"
        goto __cc_cleanup;
#line 219 "cc/lower/cclex.ccs"
    }
#line 219 "cc/lower/cclex.ccs"
    __cc_cleanup:;
#line 219 "cc/lower/cclex.ccs"
    {
#line 209 "cc/lower/cclex.ccs"
        if (__cc_defer_on_1) {
#line 209 "cc/lower/cclex.ccs"
            {
#line 209 "cc/lower/cclex.ccs"
                cc_arena_destroy(&a);
#line 209 "cc/lower/cclex.ccs"
            }
#line 209 "cc/lower/cclex.ccs"
        }
#line 219 "cc/lower/cclex.ccs"
        return __cc_retval;
#line 219 "cc/lower/cclex.ccs"
    }
}

static int usage(void) {
    fprintf(stderr, "usage: cclex --roundtrip FILE...\n" "       cclex --dump FILE\n" "       cclex --loc FILE OFF\n");
#line 226 "cc/lower/cclex.ccs"
    return 2;
}

int main(int argc, char **argv) {
    if (argc < 3)
#line 230 "cc/lower/cclex.ccs"
        return usage();
    if (strcmp(argv[1], "--roundtrip") == 0) {
        int failed = 0;
        for (int i = 2; i < argc; i++)
            if (!roundtrip(argv[i]))
#line 234 "cc/lower/cclex.ccs"
                failed++;
        if (failed)
#line 235 "cc/lower/cclex.ccs"
            fprintf(stderr, "cclex: %d of %d files failed\n", failed, argc - 2);
        return failed ? 1 : 0;
    }
    if (strcmp(argv[1], "--dump") == 0 && argc == 3)
#line 238 "cc/lower/cclex.ccs"
        return dump(argv[2]);
    if (strcmp(argv[1], "--loc") == 0 && argc == 4)
#line 239 "cc/lower/cclex.ccs"
        return loc(argv[2], argv[3]);
    return usage();
}
