#!/usr/bin/env python3
"""Generate the func_* microbenchmark sources (CC py_module + nanobind).

Mirrors nanobind's func suite: every permutation of a fixed type list as a
trivial multi-arg add.  See README.md for the uint16_t → double substitution
(CC_PY_IN has no scalar unsigned-short arm).

    python3 perf/py_bind_micro/gen.py [--limit N]
"""
from __future__ import annotations

import argparse
import itertools
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
GEN = HERE / "generated"

# Six types → 720 permutations (same cardinality as nanobind's notebook).
# nanobind uses uint16_t; we use double so both sides share identical C types
# that py_module can marshal (see README).
TYPES = [
    ("int32_t", "int32_t"),
    ("uint32_t", "uint32_t"),
    ("int64_t", "int64_t"),
    ("uint64_t", "uint64_t"),
    ("float", "float"),
    ("double", "double"),
]
ARGS = ("a", "b", "c", "d", "e", "f")


def perms(limit: int | None):
    seq = list(itertools.permutations(TYPES))
    if limit is not None:
        seq = seq[: max(0, limit)]
    return seq


def emit_cc(path: Path, rows) -> None:
    lines = [
        "/* Generated by perf/py_bind_micro/gen.py — do not edit. */",
        "#include <ccc/script/py.cch>",
        "#include <stdint.h>",
        "",
        "typedef struct Bench { int _pad; } Bench;",
        "",
    ]
    for i, trow in enumerate(rows):
        params = ", ".join(f"{t[0]} {n}" for t, n in zip(trow, ARGS))
        # Promote through double so mixed signed/unsigned/float is well-defined.
        sum_expr = " + ".join(f"(double){n}" for n in ARGS)
        lines.append(
            f"static float Bench_test_{i:04d}(Bench *self, {params}) {{"
        )
        lines.append("    (void)self;")
        lines.append(f"    return (float)({sum_expr});")
        lines.append("}")
        lines.append("")
    lines += [
        "static const Bench seed = { 0 };",
        "",
        '@comptime cc_py_export("func_cc", "Bench", &seed);',
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_nanobind(path: Path, rows) -> None:
    lines = [
        "/* Generated by perf/py_bind_micro/gen.py — do not edit. */",
        "#include <nanobind/nanobind.h>",
        "#include <stdint.h>",
        "",
        "namespace nb = nanobind;",
        "",
        "NB_MODULE(func_nanobind, m) {",
    ]
    for i, trow in enumerate(rows):
        params = ", ".join(f"{t[0]} {n}" for t, n in zip(trow, ARGS))
        sum_expr = " + ".join(f"(double){n}" for n in ARGS)
        lines.append(
            f'    m.def("test_{i:04d}", []({params}) -> float {{'
        )
        lines.append(f"        return (float)({sum_expr});")
        lines.append("    });")
    lines += ["}", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--limit",
        type=int,
        default=None,
        help="cap permutations (default: all %d)" % (len(list(itertools.permutations(TYPES)))),
    )
    args = ap.parse_args(argv)
    rows = perms(args.limit)
    GEN.mkdir(parents=True, exist_ok=True)
    cc = GEN / "func_cc.ccs"
    nb = GEN / "func_nanobind.cpp"
    emit_cc(cc, rows)
    emit_nanobind(nb, rows)
    print(f"wrote {cc} ({len(rows)} methods)", file=sys.stderr)
    print(f"wrote {nb}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
