/*
 * Builtin @grammar engine dispatch + the `rules` engine (Rebol/Red PARSE-style
 * recognition grammar → specialized C).
 *
 * STATUS: v0 skeleton. This file currently proves the native source-to-source
 * pipe end to end — it parses the fenced body only enough to count named rules
 * and emits a real `Name` type plus a trivial operation, so a `.ccs` using
 * `@grammar(rules)` compiles and runs. The full dialect compiler (charset /
 * some|any|opt / to|thru / keep|collect / ordered choice, the FIRST-set,
 * stop-set, transform-purity and recursion analyses, and the specialized
 * emitter) grows in here next; its acceptance target is the hand-lowered golden
 * output in examples/serdes/json/json.h.
 */
#include "preprocess/grammar_engine.h"
#include "util/text.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Count top-level `name:` rule headers — a rule header is an identifier followed
 * by ':' at the start of a logical line (ignores ':' inside brackets/strings).
 * This is a stand-in signal until the real parser lands; it exercises reading
 * the body without yet modeling it. */
static int cc__rules_count(const char* body, size_t n) {
    int count = 0, line_start = 1, depth = 0;
    for (size_t i = 0; i < n; i++) {
        char c = body[i];
        if (c == '\n') { line_start = 1; continue; }
        if (c == ' ' || c == '\t' || c == '\r') continue;
        if (c == ';') { while (i < n && body[i] != '\n') i++; line_start = 1; continue; }
        if (c == '[') depth++;
        else if (c == ']') { if (depth) depth--; }
        if (line_start && depth == 0 && cc_is_ident_start(c)) {
            size_t j = i;
            while (j < n && cc_is_ident_char(body[j])) j++;
            size_t k = j;
            while (k < n && (body[k] == ' ' || body[k] == '\t')) k++;
            if (k < n && body[k] == ':') count++;
        }
        line_start = 0;
    }
    return count;
}

static char* cc__rules_emit(const char* name, const char* body, size_t body_len,
                            const char* file, int line, char* err, size_t err_sz) {
    (void)file;
    if (!name || !name[0]) {
        snprintf(err, err_sz, "@grammar(rules): missing declared Name");
        return NULL;
    }
    int nrules = cc__rules_count(body, body_len);
    if (nrules == 0) {
        snprintf(err, err_sz, "@grammar(rules) %s: no `name:` rule headers found in body", name);
        return NULL;
    }
    /* v0 emission: a real type + a trivial derived operation, enough to prove
     * the pipe. Replaced by the specialized parser/emitter next. */
    char* out = NULL; size_t len = 0, cap = 0;
    char buf[512];
    snprintf(buf, sizeof(buf),
        "/* generated by @grammar(rules) %s (line %d): %d rule(s) */\n"
        "typedef struct { int rule_count; } %s;\n"
        "static inline int %s_rule_count(void) { return %d; }\n",
        name, line, nrules, name, name, nrules);
    cc_sb_append_cstr(&out, &len, &cap, buf);
    cc_sb_append(&out, &len, &cap, "", 1);
    if (out) out[len - 1] = '\0';
    return out;
}

/* --- builtin engine table --- */
char* cc_grammar_builtin_emit(const char* engine,
                              const char* name,
                              const char* body, size_t body_len,
                              const char* file, int line,
                              char* err, size_t err_sz) {
    if (err && err_sz) err[0] = '\0';
    if (engine && strcmp(engine, "rules") == 0)
        return cc__rules_emit(name, body, body_len, file, line, err, err_sz);
    /* not a builtin: signal fall-through to the comptime-fn path */
    return NULL;
}
