#line 1 "cc/lower/parse.cch"
#pragma once
#line 1 "cc/lower/parse.cch"
/* Parser: tape → CcUnit.
 *
 * Recursive descent over the tape, C11 plus the Concurrent-C forms in
 * ast.cch. Errors are diagnostics on the sink with the token's position;
 * the parser recovers at the next `;` or `}` at the same depth so one file
 * reports every error. The unit is returned even with errors; the driver
 * refuses to lower a unit whose sink has errors.
 *
 * Lifetimes: the unit owns its arena; the caller frees the unit by freeing
 * the arena the unit was created in (`unit.arena`). */

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 11 "cc/lower/parse.cch"

#line 11 "cc/lower/parse.cch"
#ifndef CC_LOWER_PARSE_CCH
#define CC_LOWER_PARSE_CCH

#include "ast.h"
#line 13 "cc/lower/parse.cch"



#ifndef CC_HEADER_VEC_CCVec_CCSlice
#define CC_HEADER_VEC_CCVec_CCSlice
/* generic CCVec_CCSlice */

#ifdef CC_HAS_CCSLICE_CCSlice
CC_VEC_DECL_ARENA_TSLICE(CCSlice, CCVec_CCSlice, CCSlice_CCSlice)
#else
CC_VEC_DECL_ARENA(CCSlice, CCVec_CCSlice)
#endif
static inline CCVec_CCSlice cc__CCVec_CCSlice_new(CCArena __a) {
    return CCVec_CCSlice_init(__a, 0);
}
#define CCVec_CCSlice_new(ar) cc__CCVec_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CCSlice (serdes) */
static const cc_type_info __cc_ti_CCVec_CCSlice = { .name = "CCVec_CCSlice", .mangled = "CCVec_CCSlice", .id = 0, .size = (uint32_t)(sizeof(CCVec_CCSlice)), .align = (uint32_t)(_Alignof(CCVec_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CCSlice(void) {
    cc_type_info_register(&__cc_ti_CCVec_CCSlice);
}
#endif
#line 15 "cc/lower/parse.cch"

#line 15 "cc/lower/parse.cch"

#include <ccc/cc_result.h>

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcExprptr_CcDiag_DEFINED
#define CCResult_CcExprptr_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcExprptr_CcDiag, CcExpr *, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 15 "cc/lower/parse.cch"

#line 15 "cc/lower/parse.cch"
typedef enum CcUnitMode {
    CC_UNIT_SOURCE,
#line 16 "cc/lower/parse.cch"
    /* .ccs: declarations, definitions */
    CC_UNIT_HEADER,
#line 17 "cc/lower/parse.cch"
    /* .cch: declarations; bodies of static inline functions are parsed */
    CC_UNIT_SCRIPT /* .shcc: top-level statements allowed */
} CcUnitMode;

typedef struct CcParseOpts {
    CcUnitMode mode;
    CCVec_CCSlice known_types; /* typedef names from headers already indexed */
} CcParseOpts;

/* Parse `src` as `path`. The unit's arena is `a`; the tape is lexed into it. */
CcUnit *cc_parse_unit(CCSlice path, CCSlice src, CcParseOpts opts, CcDiags *ds, CCArena a);

/* One statement, parsed again out of the tape it was already lexed into,
 * starting at token `first`. The nodes are fresh -- a step that rewrites a
 * statement in place needs its own copy for each place the statement stands
 * -- and their spans index that same tape, so the copy spells and locates
 * exactly like the statement it was taken from. NULL when `first` is past
 * the end. */
CcStmt *cc_parse_stmt_at(CcUnit *u, uint32_t first, CcParseOpts opts, CcDiags *ds, CCArena a);

/* Parse one expression in isolation (a template slot, a `@comptime` value). */
CCResult_CcExprptr_CcDiag cc_parse_expr(CCSlice text, CcLoc at, CcUnit *u);

/* u.dump(out): an S-expression rendering with spans, for tests. */
void CcUnit_dump(const CcUnit *u, FILE *out);

/* A generic walk: `visit` is called on every node, parents first, with the
 * closure environment the caller captured. Returning false skips the
 * node's children. */
typedef struct CcVisitor {
    bool (*type)(CcType *t, void *env);
    bool (*expr)(CcExpr *e, void *env);
    bool (*stmt)(CcStmt *s, void *env);
    bool (*decl)(CcDecl *d, void *env);
    void *env;
} CcVisitor;
void CcUnit_walk(CcUnit *u, CcVisitor v);
void CcStmt_walk(CcStmt *s, CcVisitor v);
void CcExpr_walk(CcExpr *e, CcVisitor v);

#endif
