#line 1 "cc/lower/ast.cch"
#pragma once
#line 1 "cc/lower/ast.cch"
/* The AST: tagged data with one arm per kind.
 *
 * Every node is a small header (kind-independent facts: the span of tokens
 * it covers) around a `@variant` whose arms carry only what that kind has.
 * A pass reads a node with `@switch (n->k) { case .arm(x): ... }`, so a
 * kind a pass does not handle is a compile error in that pass, and a
 * field that does not belong to a kind cannot be read by mistake.
 *
 * Children are pointers into the unit's arena (recursive arms must be), and
 * lists are `Vec::[T]` in the same arena. Names are slices of the source
 * or of the arena; two names compare by content. Nothing here is freed
 * one node at a time: the unit's arena dies with the unit.
 *
 * Spans are token indices into the unit's tape, `[first, last]` inclusive;
 * a node the lowering creates copies the span of the node it replaces, so
 * the printer pins its lines to the user's line. */

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 17 "cc/lower/ast.cch"

#line 17 "cc/lower/ast.cch"
#ifndef CC_LOWER_AST_CCH
#define CC_LOWER_AST_CCH

#include "lex.h"
#line 19 "cc/lower/ast.cch"



#include <ccc/cc_result.h>

#line 21 "cc/lower/ast.cch"

#line 21 "cc/lower/ast.cch"
typedef struct CcExpr CcExpr;

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcExprptr_CcDiag_DEFINED
#define CCResult_CcExprptr_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcExprptr_CcDiag, CcExpr *, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 22 "cc/lower/ast.cch"

#line 22 "cc/lower/ast.cch"
typedef struct CcStmt CcStmt;
typedef struct CcDecl CcDecl;
typedef struct CcType CcType;
typedef struct CcInit CcInit;
typedef CcExpr *CcExprRef; /* CcExprList: a pointer element must be a typedef today */

#ifndef CC_HEADER_VEC_CCVec_CcExprRef
#define CC_HEADER_VEC_CCVec_CcExprRef
/* generic CCVec_CcExprRef */

#ifdef CC_HAS_CCSLICE_CcExprRef
CC_VEC_DECL_ARENA_TSLICE(CcExprRef, CCVec_CcExprRef, CCSlice_CcExprRef)
#else
CC_VEC_DECL_ARENA(CcExprRef, CCVec_CcExprRef)
#endif
static inline CCVec_CcExprRef cc__CCVec_CcExprRef_new(CCArena __a) {
    return CCVec_CcExprRef_init(__a, 0);
}
#define CCVec_CcExprRef_new(ar) cc__CCVec_CcExprRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcExprRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcExprRef = { .name = "CCVec_CcExprRef", .mangled = "CCVec_CcExprRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcExprRef)), .align = (uint32_t)(_Alignof(CCVec_CcExprRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcExprRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcExprRef);
}
#endif
#line 27 "cc/lower/ast.cch"

#line 27 "cc/lower/ast.cch"
typedef CcStmt *CcStmtRef;

#ifndef CC_HEADER_VEC_CCVec_CcStmtRef
#define CC_HEADER_VEC_CCVec_CcStmtRef
/* generic CCVec_CcStmtRef */

#ifdef CC_HAS_CCSLICE_CcStmtRef
CC_VEC_DECL_ARENA_TSLICE(CcStmtRef, CCVec_CcStmtRef, CCSlice_CcStmtRef)
#else
CC_VEC_DECL_ARENA(CcStmtRef, CCVec_CcStmtRef)
#endif
static inline CCVec_CcStmtRef cc__CCVec_CcStmtRef_new(CCArena __a) {
    return CCVec_CcStmtRef_init(__a, 0);
}
#define CCVec_CcStmtRef_new(ar) cc__CCVec_CcStmtRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcStmtRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcStmtRef = { .name = "CCVec_CcStmtRef", .mangled = "CCVec_CcStmtRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcStmtRef)), .align = (uint32_t)(_Alignof(CCVec_CcStmtRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcStmtRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcStmtRef);
}
#endif
#line 28 "cc/lower/ast.cch"

#line 28 "cc/lower/ast.cch"
typedef CcDecl *CcDeclRef;

#ifndef CC_HEADER_VEC_CCVec_CcDeclRef
#define CC_HEADER_VEC_CCVec_CcDeclRef
/* generic CCVec_CcDeclRef */

#ifdef CC_HAS_CCSLICE_CcDeclRef
CC_VEC_DECL_ARENA_TSLICE(CcDeclRef, CCVec_CcDeclRef, CCSlice_CcDeclRef)
#else
CC_VEC_DECL_ARENA(CcDeclRef, CCVec_CcDeclRef)
#endif
static inline CCVec_CcDeclRef cc__CCVec_CcDeclRef_new(CCArena __a) {
    return CCVec_CcDeclRef_init(__a, 0);
}
#define CCVec_CcDeclRef_new(ar) cc__CCVec_CcDeclRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDeclRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDeclRef = { .name = "CCVec_CcDeclRef", .mangled = "CCVec_CcDeclRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDeclRef)), .align = (uint32_t)(_Alignof(CCVec_CcDeclRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDeclRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDeclRef);
}
#endif
#line 29 "cc/lower/ast.cch"

#line 29 "cc/lower/ast.cch"
typedef CcType *CcTypeRef;

#ifndef CC_HEADER_VEC_CCVec_CcTypeRef
#define CC_HEADER_VEC_CCVec_CcTypeRef
/* generic CCVec_CcTypeRef */

#ifdef CC_HAS_CCSLICE_CcTypeRef
CC_VEC_DECL_ARENA_TSLICE(CcTypeRef, CCVec_CcTypeRef, CCSlice_CcTypeRef)
#else
CC_VEC_DECL_ARENA(CcTypeRef, CCVec_CcTypeRef)
#endif
static inline CCVec_CcTypeRef cc__CCVec_CcTypeRef_new(CCArena __a) {
    return CCVec_CcTypeRef_init(__a, 0);
}
#define CCVec_CcTypeRef_new(ar) cc__CCVec_CcTypeRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcTypeRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcTypeRef = { .name = "CCVec_CcTypeRef", .mangled = "CCVec_CcTypeRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcTypeRef)), .align = (uint32_t)(_Alignof(CCVec_CcTypeRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcTypeRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcTypeRef);
}
#endif
#line 30 "cc/lower/ast.cch"

#line 30 "cc/lower/ast.cch"
typedef CcInit *CcInitRef;

#ifndef CC_HEADER_VEC_CCVec_CcInitRef
#define CC_HEADER_VEC_CCVec_CcInitRef
/* generic CCVec_CcInitRef */

#ifdef CC_HAS_CCSLICE_CcInitRef
CC_VEC_DECL_ARENA_TSLICE(CcInitRef, CCVec_CcInitRef, CCSlice_CcInitRef)
#else
CC_VEC_DECL_ARENA(CcInitRef, CCVec_CcInitRef)
#endif
static inline CCVec_CcInitRef cc__CCVec_CcInitRef_new(CCArena __a) {
    return CCVec_CcInitRef_init(__a, 0);
}
#define CCVec_CcInitRef_new(ar) cc__CCVec_CcInitRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcInitRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CcInitRef = { .name = "CCVec_CcInitRef", .mangled = "CCVec_CcInitRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcInitRef)), .align = (uint32_t)(_Alignof(CCVec_CcInitRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcInitRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcInitRef);
}
#endif
#line 31 "cc/lower/ast.cch"

#line 31 "cc/lower/ast.cch"
typedef CCVec_CcExprRef CcExprList;
typedef CCVec_CcStmtRef CcStmtList;
typedef CCVec_CcDeclRef CcDeclList;
typedef CCVec_CcTypeRef CcTypeList;
typedef CCVec_CcInitRef CcInitList;

typedef struct CcSpan {
#line 37 "cc/lower/ast.cch"
    uint32_t first;
#line 37 "cc/lower/ast.cch"
    uint32_t last;
#line 37 "cc/lower/ast.cch"
} CcSpan;
CcSpan CcSpan_join(CcSpan a, CcSpan b); /* a.join(b) */
bool CcSpan_is_empty(CcSpan s);

/* ---- Specifiers, qualifiers, attributes ------------------------------ */

enum {
#line 43 "cc/lower/ast.cch"
    /* storage and function specifiers on a declaration: CcDecl.specs */
    CC_SPEC_STATIC = 1u << 0,
#line 44 "cc/lower/ast.cch"
    CC_SPEC_EXTERN = 1u << 1,
#line 44 "cc/lower/ast.cch"
    CC_SPEC_TYPEDEF = 1u << 2,
    CC_SPEC_INLINE = 1u << 3,
#line 45 "cc/lower/ast.cch"
    CC_SPEC_NORETURN = 1u << 4,
#line 45 "cc/lower/ast.cch"
    CC_SPEC_THREAD = 1u << 5,
    CC_SPEC_REGISTER = 1u << 6,
#line 46 "cc/lower/ast.cch"
    CC_SPEC_AUTO = 1u << 7,
    /* Concurrent-C function facts */
    CC_SPEC_ASYNC = 1u << 8,
#line 48 "cc/lower/ast.cch"
    CC_SPEC_BLOCKING = 1u << 9,
#line 48 "cc/lower/ast.cch"
    CC_SPEC_NONBLOCKING = 1u << 10,
    CC_SPEC_LATENCY_SENSITIVE = 1u << 11,
#line 49 "cc/lower/ast.cch"
    CC_SPEC_COMPTIME = 1u << 12
};
enum {
#line 51 "cc/lower/ast.cch"
    /* qualifiers on one level of a type: CcType.quals */
    CC_QUAL_CONST = 1u << 0,
#line 52 "cc/lower/ast.cch"
    CC_QUAL_VOLATILE = 1u << 1,
#line 52 "cc/lower/ast.cch"
    CC_QUAL_RESTRICT = 1u << 2,
#line 52 "cc/lower/ast.cch"
    CC_QUAL_ATOMIC = 1u << 3
};

/* `__attribute__((...))`, `[[...]]`, `_Alignas(...)`, `@typeview(Name)`,
 * and CC parameter attributes (`@arena`, `@print`, `@discardable`), kept as
 * name + verbatim argument tokens. */
typedef struct CcAttr {
    CcSpan span;
    CCSlice name;
    CCSlice value; /* the single identifier argument (`unused`, `packed`, a @tag name); empty otherwise */
    CcSpan args; /* the tokens inside the parentheses; empty when none */
} CcAttr;

#ifndef CC_HEADER_VEC_CCVec_CcAttr
#define CC_HEADER_VEC_CCVec_CcAttr
/* generic CCVec_CcAttr */

#ifdef CC_HAS_CCSLICE_CcAttr
CC_VEC_DECL_ARENA_TSLICE(CcAttr, CCVec_CcAttr, CCSlice_CcAttr)
#else
CC_VEC_DECL_ARENA(CcAttr, CCVec_CcAttr)
#endif
static inline CCVec_CcAttr cc__CCVec_CcAttr_new(CCArena __a) {
    return CCVec_CcAttr_init(__a, 0);
}
#define CCVec_CcAttr_new(ar) cc__CCVec_CcAttr_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcAttr (serdes) */
static const cc_type_info __cc_ti_CCVec_CcAttr = { .name = "CCVec_CcAttr", .mangled = "CCVec_CcAttr", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcAttr)), .align = (uint32_t)(_Alignof(CCVec_CcAttr)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcAttr(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcAttr);
}
#endif
#line 64 "cc/lower/ast.cch"
 /* a prototype parameter must spell the list through a typedef */
#line 64 "cc/lower/ast.cch"
typedef CCVec_CcAttr CcAttrList; /* a prototype parameter must spell the list through a typedef */

/* ---- Types ------------------------------------------------------------ */

typedef struct CcParam {
    CcSpan span;
    CcType *type; /* NULL for a bare-name (closure / identifier-list) parameter */
    CCSlice name; /* empty for an unnamed parameter */
    CCVec_CcAttr attrs;
    CcExpr *default_value; /* `int x = 1`, or NULL */
    bool is_pp; /* a preprocessor line inside the parameter list: pp_tok only */
    uint32_t pp_tok;
} CcParam;

#ifndef CC_HEADER_VEC_CCVec_CcParam
#define CC_HEADER_VEC_CCVec_CcParam
/* generic CCVec_CcParam */

#ifdef CC_HAS_CCSLICE_CcParam
CC_VEC_DECL_ARENA_TSLICE(CcParam, CCVec_CcParam, CCSlice_CcParam)
#else
CC_VEC_DECL_ARENA(CcParam, CCVec_CcParam)
#endif
static inline CCVec_CcParam cc__CCVec_CcParam_new(CCArena __a) {
    return CCVec_CcParam_init(__a, 0);
}
#define CCVec_CcParam_new(ar) cc__CCVec_CcParam_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcParam (serdes) */
static const cc_type_info __cc_ti_CCVec_CcParam = { .name = "CCVec_CcParam", .mangled = "CCVec_CcParam", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcParam)), .align = (uint32_t)(_Alignof(CCVec_CcParam)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcParam(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcParam);
}
#endif
#line 77 "cc/lower/ast.cch"

#line 77 "cc/lower/ast.cch"
typedef CCVec_CcParam CcParamList;

typedef struct CcField {
    CcSpan span;
    CcType *type;
    CCSlice name; /* empty for an anonymous member */
    CcExpr *bits; /* `: n` bit-field width, or NULL */
    CCVec_CcAttr attrs;
    bool is_pp; /* a preprocessor line inside the member list: pp_tok only */
    uint32_t pp_tok;
} CcField;


#ifndef CC_HEADER_VEC_CCVec_CcField
#define CC_HEADER_VEC_CCVec_CcField
/* generic CCVec_CcField */

#ifdef CC_HAS_CCSLICE_CcField
CC_VEC_DECL_ARENA_TSLICE(CcField, CCVec_CcField, CCSlice_CcField)
#else
CC_VEC_DECL_ARENA(CcField, CCVec_CcField)
#endif
static inline CCVec_CcField cc__CCVec_CcField_new(CCArena __a) {
    return CCVec_CcField_init(__a, 0);
}
#define CCVec_CcField_new(ar) cc__CCVec_CcField_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcField (serdes) */
static const cc_type_info __cc_ti_CCVec_CcField = { .name = "CCVec_CcField", .mangled = "CCVec_CcField", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcField)), .align = (uint32_t)(_Alignof(CCVec_CcField)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcField(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcField);
}
#endif
#line 89 "cc/lower/ast.cch"

#line 89 "cc/lower/ast.cch"
typedef struct CcEnumerator {
    CcSpan span;
    CCSlice name;
    CcExpr *value; /* `= v`, or NULL */
    CcStmt *comptime; /* a `@comptime for` / `@comptime if` in the list that emits enumerators */
    bool is_pp;
    uint32_t pp_tok;
} CcEnumerator;


#ifndef CC_HEADER_VEC_CCVec_CcEnumerator
#define CC_HEADER_VEC_CCVec_CcEnumerator
/* generic CCVec_CcEnumerator */

#ifdef CC_HAS_CCSLICE_CcEnumerator
CC_VEC_DECL_ARENA_TSLICE(CcEnumerator, CCVec_CcEnumerator, CCSlice_CcEnumerator)
#else
CC_VEC_DECL_ARENA(CcEnumerator, CCVec_CcEnumerator)
#endif
static inline CCVec_CcEnumerator cc__CCVec_CcEnumerator_new(CCArena __a) {
    return CCVec_CcEnumerator_init(__a, 0);
}
#define CCVec_CcEnumerator_new(ar) cc__CCVec_CcEnumerator_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcEnumerator (serdes) */
static const cc_type_info __cc_ti_CCVec_CcEnumerator = { .name = "CCVec_CcEnumerator", .mangled = "CCVec_CcEnumerator", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcEnumerator)), .align = (uint32_t)(_Alignof(CCVec_CcEnumerator)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcEnumerator(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcEnumerator);
}
#endif
#line 98 "cc/lower/ast.cch"

#line 98 "cc/lower/ast.cch"
typedef struct CcNamedType {
    CCSlice name; /* canonical spelling: "unsigned long", "struct Foo", "MyType" */
    bool struct_kw;
#line 100 "cc/lower/ast.cch"
    bool union_kw;
#line 100 "cc/lower/ast.cch"
    bool enum_kw;
} CcNamedType;
typedef struct CcPointerType {
#line 102 "cc/lower/ast.cch"
    CcType *pointee;
#line 102 "cc/lower/ast.cch"
} CcPointerType;
typedef struct CcArrayType {
    CcType *elem;
    CcExpr *size; /* NULL for `T[]` */
    bool is_static; /* `T[static n]` */
    bool is_star; /* `T[*]` */
} CcArrayType;
typedef struct CcFuncType {
    CcType *ret;
    CCVec_CcParam params;
    bool variadic;
    uint32_t variadic_tok; /* the `...` token when variadic */
    bool has_prototype; /* `(void)`/`(int)` vs `()` */
} CcFuncType;
typedef struct CcRecordType {
    CCSlice tag; /* empty for anonymous */
    CCVec_CcField fields;
    bool is_union;
    bool is_definition; /* `{ ... }` present */
} CcRecordType;
typedef struct CcEnumType {
    CCSlice tag;
    CCVec_CcEnumerator items;
    CcType *base; /* `enum E : T`, or NULL */
    bool is_definition;
} CcEnumType;
typedef struct CcTypeofType {
#line 128 "cc/lower/ast.cch"
    CcExpr *expr;
#line 128 "cc/lower/ast.cch"
    CcType *type;
#line 128 "cc/lower/ast.cch"
} CcTypeofType; /* one of the two */
typedef struct CcResultType {
    CcType *value;
    CcType *err;
    bool optional; /* `?>`: a call may be discarded */
} CcResultType;
typedef struct CcSliceType {
    CcType *elem;
    CcExpr *fixed; /* `T[n:]` */
    bool unique;
    bool sentinel;
} CcSliceType;
typedef struct CcChanType {
    CcType *elem;
    CcExpr *cap;
    CCSlice topology; /* "1:1", "N:1"; empty when unspecified */
    CCSlice policy; /* `T[~cap dir, Policy]`: the drop policy name; empty when none */
    CcInit *hooks; /* `T[~cap owned { hooks }]`, or NULL */
    char dir; /* '<' receive, '>' send, 0 both */
    bool ordered;
    bool sync; /* `sync`: a blocking channel */
    bool owned;
} CcChanType;
typedef struct CcGenericType {
    CCSlice family;
    CcTypeList args;
} CcGenericType;
typedef struct CcScopedType {
    CcType *inner;
} CcScopedType;
typedef struct CcValueType {
    CcExpr *expr;
} CcValueType;
typedef struct CcAutoType {
    CcExpr *src;
} CcAutoType;


typedef enum { CcTypeK_named, CcTypeK_pointer, CcTypeK_array, CcTypeK_func, CcTypeK_record, CcTypeK_enumt, CcTypeK_typeof_, CcTypeK_atomic, CcTypeK_result, CcTypeK_slice, CcTypeK_chan, CcTypeK_generic, CcTypeK_macro, CcTypeK_valarg, CcTypeK_scoped, CcTypeK_auto_ } CcTypeKKind;
typedef struct CcTypeK { CcTypeKKind kind; union { CcNamedType named; CcPointerType pointer; CcArrayType array; CcFuncType func; CcRecordType record; CcEnumType enumt; CcTypeofType typeof_; CcPointerType atomic; CcResultType result; CcSliceType slice; CcChanType chan; CcGenericType generic; CcGenericType macro; CcValueType valarg; CcScopedType scoped; CcAutoType auto_; } u; } CcTypeK;
#line 165 "cc/lower/ast.cch"

#line 183 "cc/lower/ast.cch"

struct CcType {
    CcSpan span;
    uint32_t quals; /* CC_QUAL_* on this level */
    CCVec_CcAttr attrs;
    CcTypeK k;
};

/* ---- Expressions ------------------------------------------------------ */

typedef enum CcOp {
    CC_OP_NONE = 0,
    CC_OP_ADD,
#line 195 "cc/lower/ast.cch"
    CC_OP_SUB,
#line 195 "cc/lower/ast.cch"
    CC_OP_MUL,
#line 195 "cc/lower/ast.cch"
    CC_OP_DIV,
#line 195 "cc/lower/ast.cch"
    CC_OP_MOD,
#line 195 "cc/lower/ast.cch"
    CC_OP_SHL,
#line 195 "cc/lower/ast.cch"
    CC_OP_SHR,
    CC_OP_LT,
#line 196 "cc/lower/ast.cch"
    CC_OP_GT,
#line 196 "cc/lower/ast.cch"
    CC_OP_LE,
#line 196 "cc/lower/ast.cch"
    CC_OP_GE,
#line 196 "cc/lower/ast.cch"
    CC_OP_EQ,
#line 196 "cc/lower/ast.cch"
    CC_OP_NE,
    CC_OP_AND,
#line 197 "cc/lower/ast.cch"
    CC_OP_XOR,
#line 197 "cc/lower/ast.cch"
    CC_OP_OR,
#line 197 "cc/lower/ast.cch"
    CC_OP_LAND,
#line 197 "cc/lower/ast.cch"
    CC_OP_LOR,
    CC_OP_NEG,
#line 198 "cc/lower/ast.cch"
    CC_OP_POS,
#line 198 "cc/lower/ast.cch"
    CC_OP_NOT,
#line 198 "cc/lower/ast.cch"
    CC_OP_BITNOT,
#line 198 "cc/lower/ast.cch"
    CC_OP_DEREF,
#line 198 "cc/lower/ast.cch"
    CC_OP_ADDR,
    CC_OP_PREINC,
#line 199 "cc/lower/ast.cch"
    CC_OP_PREDEC,
#line 199 "cc/lower/ast.cch"
    CC_OP_POSTINC,
#line 199 "cc/lower/ast.cch"
    CC_OP_POSTDEC,
#line 199 "cc/lower/ast.cch"
    CC_OP_SIZEOF,
#line 199 "cc/lower/ast.cch"
    CC_OP_ALIGNOF,
    CC_OP_ASSIGN,
#line 200 "cc/lower/ast.cch"
    CC_OP_ADD_ASSIGN,
#line 200 "cc/lower/ast.cch"
    CC_OP_SUB_ASSIGN,
#line 200 "cc/lower/ast.cch"
    CC_OP_MUL_ASSIGN,
#line 200 "cc/lower/ast.cch"
    CC_OP_DIV_ASSIGN,
    CC_OP_MOD_ASSIGN,
#line 201 "cc/lower/ast.cch"
    CC_OP_SHL_ASSIGN,
#line 201 "cc/lower/ast.cch"
    CC_OP_SHR_ASSIGN,
#line 201 "cc/lower/ast.cch"
    CC_OP_AND_ASSIGN,
#line 201 "cc/lower/ast.cch"
    CC_OP_XOR_ASSIGN,
    CC_OP_OR_ASSIGN
} CcOp;
CCSlice CcOp_spelling(CcOp op); /* "+", "<<=", "sizeof" */

typedef struct CcLiteral {
#line 206 "cc/lower/ast.cch"
    uint32_t tok;
#line 206 "cc/lower/ast.cch"
    uint32_t n_toks;
#line 206 "cc/lower/ast.cch"
} CcLiteral; /* NUMBER/CHAR; STRING: adjacent literals */
typedef struct CcUnary {
#line 207 "cc/lower/ast.cch"
    CcOp op;
#line 207 "cc/lower/ast.cch"
    CcExpr *a;
#line 207 "cc/lower/ast.cch"
} CcUnary;
typedef struct CcBinary {
#line 208 "cc/lower/ast.cch"
    CcOp op;
#line 208 "cc/lower/ast.cch"
    CcExpr *a;
#line 208 "cc/lower/ast.cch"
    CcExpr *b;
#line 208 "cc/lower/ast.cch"
} CcBinary; /* also assignment ops */
typedef struct CcTernary {
#line 209 "cc/lower/ast.cch"
    CcExpr *c;
#line 209 "cc/lower/ast.cch"
    CcExpr *a;
#line 209 "cc/lower/ast.cch"
    CcExpr *b;
#line 209 "cc/lower/ast.cch"
} CcTernary;
typedef struct CcCall {
#line 210 "cc/lower/ast.cch"
    CcExpr *callee;
#line 210 "cc/lower/ast.cch"
    CcExprList args;
#line 210 "cc/lower/ast.cch"
} CcCall;
typedef struct CcIndexExpr {
#line 211 "cc/lower/ast.cch"
    CcExpr *a;
#line 211 "cc/lower/ast.cch"
    CcExpr *i;
#line 211 "cc/lower/ast.cch"
} CcIndexExpr;
typedef struct CcMember {
#line 212 "cc/lower/ast.cch"
    CcExpr *a;
#line 212 "cc/lower/ast.cch"
    CCSlice name;
#line 212 "cc/lower/ast.cch"
    bool arrow;
#line 212 "cc/lower/ast.cch"
} CcMember;
typedef struct CcCast {
#line 213 "cc/lower/ast.cch"
    CcType *type;
#line 213 "cc/lower/ast.cch"
    CcExpr *a;
#line 213 "cc/lower/ast.cch"
} CcCast;
typedef struct CcSizeofType {
#line 214 "cc/lower/ast.cch"
    CcOp op;
#line 214 "cc/lower/ast.cch"
    CcType *type;
#line 214 "cc/lower/ast.cch"
} CcSizeofType; /* sizeof(T) / _Alignof(T) */
typedef struct CcCompound {
#line 215 "cc/lower/ast.cch"
    CcType *type;
#line 215 "cc/lower/ast.cch"
    CcInit *init;
#line 215 "cc/lower/ast.cch"
} CcCompound; /* (T){ ... } */
typedef struct CcGenericSelArm {
    CcSpan span;
#line 217 "cc/lower/ast.cch"
    CcType *type;
#line 217 "cc/lower/ast.cch"
    CcExpr *expr;
#line 217 "cc/lower/ast.cch"
    bool is_default;
    bool is_pp;
#line 218 "cc/lower/ast.cch"
    uint32_t pp_tok; /* a preprocessor line between arms: pp_tok only */
} CcGenericSelArm;

#ifndef CC_HEADER_VEC_CCVec_CcGenericSelArm
#define CC_HEADER_VEC_CCVec_CcGenericSelArm
/* generic CCVec_CcGenericSelArm */

#ifdef CC_HAS_CCSLICE_CcGenericSelArm
CC_VEC_DECL_ARENA_TSLICE(CcGenericSelArm, CCVec_CcGenericSelArm, CCSlice_CcGenericSelArm)
#else
CC_VEC_DECL_ARENA(CcGenericSelArm, CCVec_CcGenericSelArm)
#endif
static inline CCVec_CcGenericSelArm cc__CCVec_CcGenericSelArm_new(CCArena __a) {
    return CCVec_CcGenericSelArm_init(__a, 0);
}
#define CCVec_CcGenericSelArm_new(ar) cc__CCVec_CcGenericSelArm_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcGenericSelArm (serdes) */
static const cc_type_info __cc_ti_CCVec_CcGenericSelArm = { .name = "CCVec_CcGenericSelArm", .mangled = "CCVec_CcGenericSelArm", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcGenericSelArm)), .align = (uint32_t)(_Alignof(CCVec_CcGenericSelArm)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcGenericSelArm(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcGenericSelArm);
}
#endif
#line 220 "cc/lower/ast.cch"

#line 220 "cc/lower/ast.cch"
typedef struct CcGenericSel {
    CcExpr *control;
    CCVec_CcGenericSelArm arms;
    bool verbatim;
#line 226 "cc/lower/ast.cch"
    CcSpan args; /* the tokens of the association list, for that replay */
} CcGenericSel;
typedef struct CcStmtExpr {
#line 228 "cc/lower/ast.cch"
    CcStmt *block;
#line 228 "cc/lower/ast.cch"
} CcStmtExpr; /* ({ ... }) */
typedef struct CcComma {
#line 229 "cc/lower/ast.cch"
    CcExpr *a;
#line 229 "cc/lower/ast.cch"
    CcExpr *b;
#line 229 "cc/lower/ast.cch"
} CcComma;
/* Concurrent-C */
typedef struct CcUfcs {
    CcExpr *recv;
    CCSlice method;
    bool arrow;
    CcTypeList targs;
    CcExprList args;
} CcUfcs;
typedef struct CcTypeScoped {
    CcType *type;
    CCSlice fn;
    CcExprList args;
} CcTypeScoped;
typedef struct CcGenericFn {
    CCSlice name;
    CcTypeList targs;
    CcExprList args;
} CcGenericFn;
typedef struct CcUnwrap {
#line 248 "cc/lower/ast.cch"
    CcExpr *a;
#line 248 "cc/lower/ast.cch"
} CcUnwrap; /* e !> (handler is the @errhandler in scope) */
typedef struct CcUnwrapBody {
    CcExpr *a;
    CCSlice binder; /* empty when no `(err)` */
    CcStmt *body; /* a block or a single statement; must diverge in expression position */
} CcUnwrapBody;
typedef struct CcUnwrapOr {
    CcExpr *a;
    CCSlice binder;
    CcExpr *fallback;
} CcUnwrapOr;
typedef struct CcUnwrapDestroy {
    CcExpr *a;
    CcStmt *destroy_body; /* NULL: the type's destroy hook */
} CcUnwrapDestroy;
typedef struct CcTplPart {
    CcSpan span;
    CCSlice text; /* literal run: the bytes, escapes still as written */
    CcExpr *slot; /* NULL for a literal run */
    CCSlice tag; /* `$~tag{...}`; empty for `${...}` */
    bool is_verbatim; /* `${{ raw }}`: a literal run whose bytes carry no escapes */
    CcTape *tape; /* a slot's own tape: `slot` spans index it; NULL for a literal run */
} CcTplPart;

#ifndef CC_HEADER_VEC_CCVec_CcTplPart
#define CC_HEADER_VEC_CCVec_CcTplPart
/* generic CCVec_CcTplPart */

#ifdef CC_HAS_CCSLICE_CcTplPart
CC_VEC_DECL_ARENA_TSLICE(CcTplPart, CCVec_CcTplPart, CCSlice_CcTplPart)
#else
CC_VEC_DECL_ARENA(CcTplPart, CCVec_CcTplPart)
#endif
static inline CCVec_CcTplPart cc__CCVec_CcTplPart_new(CCArena __a) {
    return CCVec_CcTplPart_init(__a, 0);
}
#define CCVec_CcTplPart_new(ar) cc__CCVec_CcTplPart_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcTplPart (serdes) */
static const cc_type_info __cc_ti_CCVec_CcTplPart = { .name = "CCVec_CcTplPart", .mangled = "CCVec_CcTplPart", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcTplPart)), .align = (uint32_t)(_Alignof(CCVec_CcTplPart)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcTplPart(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcTplPart);
}
#endif
#line 271 "cc/lower/ast.cch"
 /* a prototype cannot spell `Vec::[T]*` today: see stress/break */
#line 271 "cc/lower/ast.cch"
typedef CCVec_CcTplPart CcTplPartList; /* a prototype cannot spell `Vec::[T]*` today: see stress/break */
typedef struct CcTemplate {
    CcExpr *policy; /* NULL when absent */
    CCVec_CcTplPart parts; /* empty for the direct form */
    CcExpr *direct; /* @string(expr, arena): the expression; NULL for the literal form */
    CcExpr *arena; /* the arena operand; a `scratch` node for @scratch; NULL for the bounded stack form */
} CcTemplate;
typedef struct CcSliceLit {
#line 278 "cc/lower/ast.cch"
    uint32_t tok;
#line 278 "cc/lower/ast.cch"
    uint32_t n_toks;
#line 278 "cc/lower/ast.cch"
} CcSliceLit; /* @slice("..." "..."): adjacent literals */
typedef struct CcScratch {
#line 279 "cc/lower/ast.cch"
    CcExpr *bytes;
#line 279 "cc/lower/ast.cch"
} CcScratch; /* @scratch / @scratch(N) */
typedef struct CcCapture {
    CcSpan span;
#line 281 "cc/lower/ast.cch"
    CCSlice name;
#line 281 "cc/lower/ast.cch"
    bool by_ref;
#line 281 "cc/lower/ast.cch"
    bool is_move;
    bool is_safe; /* `[@safe &x]` */
    CcExpr *init; /* `[p = &x]`: an init-capture, else NULL */
} CcCapture;

#ifndef CC_HEADER_VEC_CCVec_CcCapture
#define CC_HEADER_VEC_CCVec_CcCapture
/* generic CCVec_CcCapture */

#ifdef CC_HAS_CCSLICE_CcCapture
CC_VEC_DECL_ARENA_TSLICE(CcCapture, CCVec_CcCapture, CCSlice_CcCapture)
#else
CC_VEC_DECL_ARENA(CcCapture, CCVec_CcCapture)
#endif
static inline CCVec_CcCapture cc__CCVec_CcCapture_new(CCArena __a) {
    return CCVec_CcCapture_init(__a, 0);
}
#define CCVec_CcCapture_new(ar) cc__CCVec_CcCapture_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcCapture (serdes) */
static const cc_type_info __cc_ti_CCVec_CcCapture = { .name = "CCVec_CcCapture", .mangled = "CCVec_CcCapture", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcCapture)), .align = (uint32_t)(_Alignof(CCVec_CcCapture)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcCapture(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcCapture);
}
#endif
#line 285 "cc/lower/ast.cch"

#line 285 "cc/lower/ast.cch"
typedef struct CcClosure {
    CCVec_CcParam params;
    CCVec_CcCapture captures;
    CcStmt *body; /* a block, or an expression statement for `=> expr` */
    bool is_unsafe;
    bool is_async;
} CcClosure;
typedef struct CcAwait {
#line 292 "cc/lower/ast.cch"
    CcExpr *a;
#line 292 "cc/lower/ast.cch"
} CcAwait;
typedef struct CcComptimeExpr {
#line 293 "cc/lower/ast.cch"
    CcExpr *a;
#line 293 "cc/lower/ast.cch"
} CcComptimeExpr; /* @comptime(e) */
typedef struct CcCreate {
    CCSlice var; /* name@(args): the declared name; empty for @create */
    CcExprList args;
} CcCreate;
typedef struct CcEmit {
#line 298 "cc/lower/ast.cch"
    CcTemplate tpl;
#line 298 "cc/lower/ast.cch"
    CcExprList args;
#line 298 "cc/lower/ast.cch"
} CcEmit; /* @emit(`...`, arena): every argument as written, and the template split out */
typedef struct CcVariantLit {
    CCSlice arm;
    CcExprList args;
} CcVariantLit;
typedef struct CcCallMode {
#line 303 "cc/lower/ast.cch"
    CCSlice mode;
#line 303 "cc/lower/ast.cch"
    CcExpr *a;
#line 303 "cc/lower/ast.cch"
} CcCallMode; /* @blocking e / @nonblocking e */
typedef struct CcRange {
#line 304 "cc/lower/ast.cch"
    CcExpr *lo;
#line 304 "cc/lower/ast.cch"
    CcExpr *hi;
#line 304 "cc/lower/ast.cch"
} CcRange; /* lo..hi */
typedef struct CcPpExpr {
#line 305 "cc/lower/ast.cch"
    uint32_t tok;
#line 305 "cc/lower/ast.cch"
} CcPpExpr; /* a preprocessor line in an argument list */
typedef struct CcTypeArg {
#line 306 "cc/lower/ast.cch"
    CcType *type;
#line 306 "cc/lower/ast.cch"
} CcTypeArg; /* a type in argument position */


typedef enum { CcExprK_ident, CcExprK_number, CcExprK_chr, CcExprK_string, CcExprK_paren, CcExprK_unary, CcExprK_binary, CcExprK_assign, CcExprK_ternary, CcExprK_call, CcExprK_index, CcExprK_member, CcExprK_cast, CcExprK_sizeof_type, CcExprK_compound, CcExprK_generic_sel, CcExprK_stmt_expr, CcExprK_comma, CcExprK_ufcs, CcExprK_type_scoped, CcExprK_generic_fn, CcExprK_unwrap, CcExprK_unwrap_body, CcExprK_unwrap_or, CcExprK_unwrap_destroy, CcExprK_template, CcExprK_slice_lit, CcExprK_scratch, CcExprK_closure, CcExprK_await_, CcExprK_comptime, CcExprK_create, CcExprK_emit, CcExprK_variant_lit, CcExprK_call_mode, CcExprK_range, CcExprK_pp, CcExprK_type_arg } CcExprKKind;
typedef struct CcExprK { CcExprKKind kind; union { CCSlice ident; CcLiteral number; CcLiteral chr; CcLiteral string; CcUnary paren; CcUnary unary; CcBinary binary; CcBinary assign; CcTernary ternary; CcCall call; CcIndexExpr index; CcMember member; CcCast cast; CcSizeofType sizeof_type; CcCompound compound; CcGenericSel generic_sel; CcStmtExpr stmt_expr; CcComma comma; CcUfcs ufcs; CcTypeScoped type_scoped; CcGenericFn generic_fn; CcUnwrap unwrap; CcUnwrapBody unwrap_body; CcUnwrapOr unwrap_or; CcUnwrapDestroy unwrap_destroy; CcTemplate template; CcSliceLit slice_lit; CcScratch scratch; CcClosure closure; CcAwait await_; CcComptimeExpr comptime; CcCreate create; CcEmit emit; CcVariantLit variant_lit; CcCallMode call_mode; CcRange range; CcPpExpr pp; CcTypeArg type_arg; } u; } CcExprK;
#line 308 "cc/lower/ast.cch"

#line 348 "cc/lower/ast.cch"

struct CcExpr {
    CcSpan span;
    CcExprK k;
};

/* ---- Initializers ----------------------------------------------------- */

typedef struct CcDesignator {
    CCSlice field; /* `.field`; empty for an index designator */
    CcExpr *index; /* `[i]` */
    CcExpr *index_hi; /* `[lo ... hi]` */
} CcDesignator;


#ifndef CC_HEADER_VEC_CCVec_CcDesignator
#define CC_HEADER_VEC_CCVec_CcDesignator
/* generic CCVec_CcDesignator */

#ifdef CC_HAS_CCSLICE_CcDesignator
CC_VEC_DECL_ARENA_TSLICE(CcDesignator, CCVec_CcDesignator, CCSlice_CcDesignator)
#else
CC_VEC_DECL_ARENA(CcDesignator, CCVec_CcDesignator)
#endif
static inline CCVec_CcDesignator cc__CCVec_CcDesignator_new(CCArena __a) {
    return CCVec_CcDesignator_init(__a, 0);
}
#define CCVec_CcDesignator_new(ar) cc__CCVec_CcDesignator_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDesignator (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDesignator = { .name = "CCVec_CcDesignator", .mangled = "CCVec_CcDesignator", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDesignator)), .align = (uint32_t)(_Alignof(CCVec_CcDesignator)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDesignator(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDesignator);
}
#endif
#line 362 "cc/lower/ast.cch"

#line 362 "cc/lower/ast.cch"
struct CcInit {
    CcSpan span;
    CCVec_CcDesignator designators; /* empty for positional */
    CcExpr *expr; /* scalar, or NULL when `items` is the `{ ... }` list */
    CcInitList items;
    bool is_list;
    bool is_pp;
    uint32_t pp_tok;
};

/* ---- Statements ------------------------------------------------------- */

typedef struct CcExprStmt {
#line 374 "cc/lower/ast.cch"
    CcExpr *e;
#line 374 "cc/lower/ast.cch"
    CcStmt *body;
#line 374 "cc/lower/ast.cch"
} CcExprStmt; /* e == NULL for `;`; body: the block of a macro loop `FOREACH(...) { }` / `try { }`, else NULL */
typedef struct CcDeclStmt {
#line 375 "cc/lower/ast.cch"
    CcDecl *d;
#line 375 "cc/lower/ast.cch"
} CcDeclStmt;
typedef struct CcBlock {
#line 376 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 376 "cc/lower/ast.cch"
} CcBlock;
typedef struct CcIf {
#line 377 "cc/lower/ast.cch"
    CcExpr *cond;
#line 377 "cc/lower/ast.cch"
    CcStmt *then;
#line 377 "cc/lower/ast.cch"
    CcStmt *els;
#line 377 "cc/lower/ast.cch"
} CcIf; /* els may be NULL */
typedef struct CcWhile {
#line 378 "cc/lower/ast.cch"
    CcExpr *cond;
#line 378 "cc/lower/ast.cch"
    CcStmt *body;
#line 378 "cc/lower/ast.cch"
} CcWhile; /* also do-while */
typedef struct CcFor {
    CcDecl *init_decl; /* one of init_decl / init_expr, or neither */
    CcExpr *init_expr;
    CcExpr *cond;
    CcExpr *step;
    CcStmt *body;
    CcStmtList more; /* `for (int i = 0, j = n; ...)`: the declarations after the first, as decl statements */
} CcFor;
typedef struct CcSwitch {
#line 387 "cc/lower/ast.cch"
    CcExpr *subject;
#line 387 "cc/lower/ast.cch"
    CcStmt *body;
#line 387 "cc/lower/ast.cch"
    bool is_variant;
#line 387 "cc/lower/ast.cch"
} CcSwitch; /* @switch sets is_variant */
typedef struct CcCase {
    CcExpr *lo;
    CcExpr *hi;
    CCSlice arm; /* `.arm` */
    CCSlice bind; /* `(bind)` */
    bool is_default;
    CcStmt *inner; /* the labelled statement, or NULL */
} CcCase;
typedef struct CcReturn {
#line 396 "cc/lower/ast.cch"
    CcExpr *value;
#line 396 "cc/lower/ast.cch"
} CcReturn; /* NULL for bare return */
typedef struct CcGoto {
#line 397 "cc/lower/ast.cch"
    CCSlice label;
#line 397 "cc/lower/ast.cch"
    CcExpr *target;
#line 397 "cc/lower/ast.cch"
} CcGoto; /* target: GNU `goto *e;`, label empty */
typedef struct CcLabel {
#line 398 "cc/lower/ast.cch"
    CCSlice name;
#line 398 "cc/lower/ast.cch"
    CcStmt *inner;
#line 398 "cc/lower/ast.cch"
} CcLabel;
typedef struct CcAsm {
#line 399 "cc/lower/ast.cch"
    CcSpan tokens;
#line 399 "cc/lower/ast.cch"
} CcAsm;
/* Concurrent-C */
typedef struct CcDefer {
#line 401 "cc/lower/ast.cch"
    CCSlice name;
#line 401 "cc/lower/ast.cch"
    char on;
#line 401 "cc/lower/ast.cch"
    CcStmt *body;
#line 401 "cc/lower/ast.cch"
} CcDefer; /* on: 0 always, 'o' ok, 'e' err */
typedef struct CcCancelDefer {
#line 402 "cc/lower/ast.cch"
    CCSlice name;
#line 402 "cc/lower/ast.cch"
} CcCancelDefer;
typedef struct CcErrhandler {
#line 403 "cc/lower/ast.cch"
    CcType *err_type;
#line 403 "cc/lower/ast.cch"
    CCSlice binder;
#line 403 "cc/lower/ast.cch"
    CcStmt *body;
#line 403 "cc/lower/ast.cch"
} CcErrhandler;
typedef struct CcErrFwd {
    CcExpr *err;
    bool delegate;
#line 406 "cc/lower/ast.cch"
    /* written `@errhandler(e);`: the delegation spelling, which
                                 * an `@err` body may use and nothing else may */
} CcErrFwd;
typedef struct CcUnwrapStmt {
#line 409 "cc/lower/ast.cch"
    CcExpr *e;
#line 409 "cc/lower/ast.cch"
} CcUnwrapStmt; /* e !>;  e !> body; */
typedef struct CcForIn {
    CCSlice bind;
    CCSlice bind2;
    CcExprList iterables; /* one or two; a `range` node for lo..hi */
    bool by_ref;
    bool by_ref2; /* `@for (a, &b in xs, ys)`: the second binder is by reference */
    bool is_at_for;
    CcStmt *body;
    CcExpr *tail; /* `} !>` / `} !>(e) body` after the block: the walk's Result, unwrapped; NULL otherwise */
} CcForIn;
typedef struct CcParallelArm {
    CcSpan span;
    CCSlice target; /* `a = expr;`; empty for `expr !>;` and @serial */
    CcExpr *expr; /* NULL for @serial */
    CcStmt *serial; /* the @serial block */
    bool unwrap;
} CcParallelArm;

#ifndef CC_HEADER_VEC_CCVec_CcParallelArm
#define CC_HEADER_VEC_CCVec_CcParallelArm
/* generic CCVec_CcParallelArm */

#ifdef CC_HAS_CCSLICE_CcParallelArm
CC_VEC_DECL_ARENA_TSLICE(CcParallelArm, CCVec_CcParallelArm, CCSlice_CcParallelArm)
#else
CC_VEC_DECL_ARENA(CcParallelArm, CCVec_CcParallelArm)
#endif
static inline CCVec_CcParallelArm cc__CCVec_CcParallelArm_new(CCArena __a) {
    return CCVec_CcParallelArm_init(__a, 0);
}
#define CCVec_CcParallelArm_new(ar) cc__CCVec_CcParallelArm_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcParallelArm (serdes) */
static const cc_type_info __cc_ti_CCVec_CcParallelArm = { .name = "CCVec_CcParallelArm", .mangled = "CCVec_CcParallelArm", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcParallelArm)), .align = (uint32_t)(_Alignof(CCVec_CcParallelArm)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcParallelArm(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcParallelArm);
}
#endif
#line 427 "cc/lower/ast.cch"

#line 427 "cc/lower/ast.cch"
typedef struct CcParallel {
    CCVec_CcParallelArm arms;
    bool spawn;
    CcExpr *pred;
    CcExpr *seq;
    CcExpr *wait;
#line 434 "cc/lower/ast.cch"
    CCSlice worker;
    CcExprList cache;
    CCSlice bind; /* `CCParallel h = ...` */
    CcType *bind_type;
    CcExpr *target; /* `lvalue = @parallel { ... }`: the assigned join target, or NULL */
    CcExpr *tail; /* `!>.wait()!>` chain after the block, or NULL */
} CcParallel;
typedef struct CcParallelFor {
    CcForIn loop;
    bool spawn; /* `@parallel spawn for`: as written; the lowering decides whether it is allowed */
    CcExpr *pred; /* `@parallel (pred) for`: likewise */
    CcExpr *seq;
    CcExpr *wait;
    CCSlice worker;
    CcExprList cache;
    CCSlice bind; /* `CCParallel h = @parallel ... for`: the join name, else empty */
    CcType *bind_type;
    CcExpr *target; /* `lvalue = @parallel ... for`: the assigned join target, or NULL */
    CcExpr *tail; /* `!>.wait()!>` chain after the body, or NULL */
} CcParallelFor;
typedef struct CcParallelDest {
#line 454 "cc/lower/ast.cch"
    CcExpr *dest;
#line 454 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 454 "cc/lower/ast.cch"
} CcParallelDest; /* @parallel(h) { } */
typedef struct CcStage {
#line 455 "cc/lower/ast.cch"
    CcExpr *gate;
#line 455 "cc/lower/ast.cch"
    CcExprList args;
#line 455 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 455 "cc/lower/ast.cch"
} CcStage;
typedef struct CcWithDeadline {
#line 456 "cc/lower/ast.cch"
    CcExpr *deadline;
#line 456 "cc/lower/ast.cch"
    CCSlice as;
#line 456 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 456 "cc/lower/ast.cch"
} CcWithDeadline;
typedef struct CcWith {
#line 457 "cc/lower/ast.cch"
    CCSlice key;
#line 457 "cc/lower/ast.cch"
    CcExpr *value;
#line 457 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 457 "cc/lower/ast.cch"
} CcWith; /* @with(arena = a) { } */
typedef struct CcClosing {
    CcExprList channels;
    CcStmtList stmts;
    CcExpr *spawn; /* the spawn call form */
} CcClosing;
typedef struct CcSpawnBlock {
#line 463 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 463 "cc/lower/ast.cch"
    bool is_nursery;
#line 463 "cc/lower/ast.cch"
    CcExprList closing;
#line 463 "cc/lower/ast.cch"
} CcSpawnBlock;
typedef struct CcModeBlock {
#line 464 "cc/lower/ast.cch"
    CCSlice mode;
#line 464 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 464 "cc/lower/ast.cch"
} CcModeBlock; /* @nonblocking { } */
typedef struct CcComptimeIf {
#line 465 "cc/lower/ast.cch"
    CcExpr *cond;
#line 465 "cc/lower/ast.cch"
    CcStmtList then;
#line 465 "cc/lower/ast.cch"
    CcStmtList els;
#line 465 "cc/lower/ast.cch"
} CcComptimeIf;
typedef struct CcComptimeFor {
#line 466 "cc/lower/ast.cch"
    CCSlice bind;
#line 466 "cc/lower/ast.cch"
    CcExpr *over;
#line 466 "cc/lower/ast.cch"
    CcStmtList stmts;
#line 466 "cc/lower/ast.cch"
} CcComptimeFor;


typedef enum { CcStmtK_expr, CcStmtK_decl, CcStmtK_block, CcStmtK_if_, CcStmtK_while_, CcStmtK_do_, CcStmtK_for_, CcStmtK_switch_, CcStmtK_case_, CcStmtK_return_, CcStmtK_break_, CcStmtK_continue_, CcStmtK_goto_, CcStmtK_label, CcStmtK_asm_, CcStmtK_defer, CcStmtK_cancel_defer, CcStmtK_errhandler, CcStmtK_err_fwd, CcStmtK_unwrap, CcStmtK_for_in, CcStmtK_parallel, CcStmtK_parallel_for, CcStmtK_parallel_dest, CcStmtK_serial, CcStmtK_stage, CcStmtK_with_deadline, CcStmtK_with, CcStmtK_closing, CcStmtK_spawn_block, CcStmtK_mode_block, CcStmtK_unsafe, CcStmtK_comptime_if, CcStmtK_comptime_block, CcStmtK_comptime_for } CcStmtKKind;
typedef struct CcStmtK { CcStmtKKind kind; union { CcExprStmt expr; CcDeclStmt decl; CcBlock block; CcIf if_; CcWhile while_; CcWhile do_; CcFor for_; CcSwitch switch_; CcCase case_; CcReturn return_; CcGoto goto_; CcLabel label; CcAsm asm_; CcDefer defer; CcCancelDefer cancel_defer; CcErrhandler errhandler; CcErrFwd err_fwd; CcUnwrapStmt unwrap; CcForIn for_in; CcParallel parallel; CcParallelFor parallel_for; CcParallelDest parallel_dest; CcBlock serial; CcStage stage; CcWithDeadline with_deadline; CcWith with; CcClosing closing; CcSpawnBlock spawn_block; CcModeBlock mode_block; CcBlock unsafe; CcComptimeIf comptime_if; CcBlock comptime_block; CcComptimeFor comptime_for; } u; } CcStmtK;
#line 468 "cc/lower/ast.cch"

#line 505 "cc/lower/ast.cch"

struct CcStmt {
    CcSpan span;
    CcStmtK k;
};

/* ---- Declarations ----------------------------------------------------- */

typedef struct CcVarDecl {
    CcType *type;
    CCSlice name;
    CcInit *init;
    bool destroy;
    CcStmt *destroy_body;
    bool detach;
    bool init_is_decl;
#line 520 "cc/lower/ast.cch"
    /* a decl-form `.create` overload: the initializer IS the whole
                                   declaration (it declares the variable), so nothing prints `T name =` */
} CcVarDecl;
typedef struct CcFuncDecl {
    CcType *type; /* the func type: ret + params */
    CCSlice name;
    CcStmt *body; /* NULL for a prototype */
    bool destroy; /* `@auto(src) name(args) @destroy;`: constructor sugar the parser classes as a function */
    bool detach;
} CcFuncDecl;
typedef struct CcTypedefDecl {
#line 530 "cc/lower/ast.cch"
    CcType *type;
#line 530 "cc/lower/ast.cch"
    CCSlice name;
#line 530 "cc/lower/ast.cch"
} CcTypedefDecl;
typedef struct CcTaggedDecl {
#line 531 "cc/lower/ast.cch"
    CcType *type;
#line 531 "cc/lower/ast.cch"
} CcTaggedDecl; /* struct/union/enum definition or forward, alone */
typedef struct CcStaticAssert {
#line 532 "cc/lower/ast.cch"
    CcExpr *cond;
#line 532 "cc/lower/ast.cch"
    uint32_t msg_tok;
#line 532 "cc/lower/ast.cch"
} CcStaticAssert;
typedef struct CcPpDecl {
    uint32_t tok;
    CcSpan skipped; /* a `#if 0` / `__cplusplus` region kept verbatim, unparsed; empty otherwise */
} CcPpDecl;
typedef struct CcViewItem {
    CcSpan span;
    CCSlice name;
    bool deny;
    CcType *cast;
} CcViewItem;

#ifndef CC_HEADER_VEC_CCVec_CcViewItem
#define CC_HEADER_VEC_CCVec_CcViewItem
/* generic CCVec_CcViewItem */

#ifdef CC_HAS_CCSLICE_CcViewItem
CC_VEC_DECL_ARENA_TSLICE(CcViewItem, CCVec_CcViewItem, CCSlice_CcViewItem)
#else
CC_VEC_DECL_ARENA(CcViewItem, CCVec_CcViewItem)
#endif
static inline CCVec_CcViewItem cc__CCVec_CcViewItem_new(CCArena __a) {
    return CCVec_CcViewItem_init(__a, 0);
}
#define CCVec_CcViewItem_new(ar) cc__CCVec_CcViewItem_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcViewItem (serdes) */
static const cc_type_info __cc_ti_CCVec_CcViewItem = { .name = "CCVec_CcViewItem", .mangled = "CCVec_CcViewItem", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcViewItem)), .align = (uint32_t)(_Alignof(CCVec_CcViewItem)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcViewItem(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcViewItem);
}
#endif
#line 543 "cc/lower/ast.cch"

#line 543 "cc/lower/ast.cch"
typedef struct CcHookEntry {
    CcSpan span;
    CCSlice key;
    CcExpr *value;
    CcStmt *body;
    CCVec_CcViewItem items;
} CcHookEntry;

#ifndef CC_HEADER_VEC_CCVec_CcHookEntry
#define CC_HEADER_VEC_CCVec_CcHookEntry
/* generic CCVec_CcHookEntry */

#ifdef CC_HAS_CCSLICE_CcHookEntry
CC_VEC_DECL_ARENA_TSLICE(CcHookEntry, CCVec_CcHookEntry, CCSlice_CcHookEntry)
#else
CC_VEC_DECL_ARENA(CcHookEntry, CCVec_CcHookEntry)
#endif
static inline CCVec_CcHookEntry cc__CCVec_CcHookEntry_new(CCArena __a) {
    return CCVec_CcHookEntry_init(__a, 0);
}
#define CCVec_CcHookEntry_new(ar) cc__CCVec_CcHookEntry_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcHookEntry (serdes) */
static const cc_type_info __cc_ti_CCVec_CcHookEntry = { .name = "CCVec_CcHookEntry", .mangled = "CCVec_CcHookEntry", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcHookEntry)), .align = (uint32_t)(_Alignof(CCVec_CcHookEntry)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcHookEntry(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcHookEntry);
}
#endif
#line 550 "cc/lower/ast.cch"

#line 550 "cc/lower/ast.cch"
typedef struct CcTypehooks {
#line 550 "cc/lower/ast.cch"
    CcType *target;
#line 550 "cc/lower/ast.cch"
    CCVec_CcHookEntry entries;
#line 550 "cc/lower/ast.cch"
} CcTypehooks;
typedef struct CcTypeview {
    CCSlice view; /* empty for the unnamed view */
    CcType *target; /* may be a glob: `Fam_*` */
    CCVec_CcHookEntry entries;
} CcTypeview;
typedef struct CcVariantArm {
    CcSpan span;
    CCSlice name;
    CcType *payload;
    CcSpan payload_span; /* the tokens of the type-name after the colon */
    CCVec_CcParam fields;
} CcVariantArm;

#ifndef CC_HEADER_VEC_CCVec_CcVariantArm
#define CC_HEADER_VEC_CCVec_CcVariantArm
/* generic CCVec_CcVariantArm */

#ifdef CC_HAS_CCSLICE_CcVariantArm
CC_VEC_DECL_ARENA_TSLICE(CcVariantArm, CCVec_CcVariantArm, CCSlice_CcVariantArm)
#else
CC_VEC_DECL_ARENA(CcVariantArm, CCVec_CcVariantArm)
#endif
static inline CCVec_CcVariantArm cc__CCVec_CcVariantArm_new(CCArena __a) {
    return CCVec_CcVariantArm_init(__a, 0);
}
#define CCVec_CcVariantArm_new(ar) cc__CCVec_CcVariantArm_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcVariantArm (serdes) */
static const cc_type_info __cc_ti_CCVec_CcVariantArm = { .name = "CCVec_CcVariantArm", .mangled = "CCVec_CcVariantArm", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcVariantArm)), .align = (uint32_t)(_Alignof(CCVec_CcVariantArm)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcVariantArm(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcVariantArm);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CCSlice
#define CC_HEADER_VEC_CCVec_CCSlice
/* generic CCVec_CCSlice */

#ifdef CC_HAS_CCSLICE_CCSlice
CC_VEC_DECL_ARENA_TSLICE(CCSlice, CCVec_CCSlice, CCSlice_CCSlice)
#else
CC_VEC_DECL_ARENA(CCSlice, CCVec_CCSlice)
#endif
static inline CCVec_CCSlice cc__CCVec_CCSlice_new(CCArena __a) {
    return CCVec_CCSlice_init(__a, 0);
}
#define CCVec_CCSlice_new(ar) cc__CCVec_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CCSlice (serdes) */
static const cc_type_info __cc_ti_CCVec_CCSlice = { .name = "CCVec_CCSlice", .mangled = "CCVec_CCSlice", .id = 0, .size = (uint32_t)(sizeof(CCVec_CCSlice)), .align = (uint32_t)(_Alignof(CCVec_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CCSlice(void) {
    cc_type_info_register(&__cc_ti_CCVec_CCSlice);
}
#endif
#line 563 "cc/lower/ast.cch"

#line 563 "cc/lower/ast.cch"
typedef struct CcVariantDecl {
#line 563 "cc/lower/ast.cch"
    CCSlice name;
#line 563 "cc/lower/ast.cch"
    CCVec_CcVariantArm arms;
#line 563 "cc/lower/ast.cch"
    bool packed;
#line 563 "cc/lower/ast.cch"
} CcVariantDecl;
typedef struct CcGrammarDecl {
#line 564 "cc/lower/ast.cch"
    CCSlice name;
#line 564 "cc/lower/ast.cch"
    CCSlice engine;
#line 564 "cc/lower/ast.cch"
    CCSlice body;
#line 564 "cc/lower/ast.cch"
} CcGrammarDecl; /* fenced body, opaque */
typedef struct CcFactoryDecl {
    CCSlice name;
    CcExpr *arity;
    bool extend;
    CcStmt *body;
} CcFactoryDecl;
typedef struct CcComptimeFn {
#line 571 "cc/lower/ast.cch"
    CcFuncDecl fn;
#line 571 "cc/lower/ast.cch"
} CcComptimeFn;
typedef struct CcComptimeDeclIf {
#line 572 "cc/lower/ast.cch"
    CcExpr *cond;
#line 572 "cc/lower/ast.cch"
    CcDeclList then;
#line 572 "cc/lower/ast.cch"
    CcDeclList els;
#line 572 "cc/lower/ast.cch"
} CcComptimeDeclIf;
typedef struct CcScopedTypeDecl {
#line 573 "cc/lower/ast.cch"
    CCSlice name;
#line 573 "cc/lower/ast.cch"
    CcType *type;
#line 573 "cc/lower/ast.cch"
} CcScopedTypeDecl; /* @scoped type Name::[T]; */
typedef struct CcPragmaCc {
#line 574 "cc/lower/ast.cch"
    CCSlice name;
#line 574 "cc/lower/ast.cch"
    CCSlice value;
#line 574 "cc/lower/ast.cch"
} CcPragmaCc; /* #pragma(@parallel) off */
typedef struct CcLinkDecl {
#line 575 "cc/lower/ast.cch"
    CCSlice lib;
#line 575 "cc/lower/ast.cch"
} CcLinkDecl;
typedef struct CcTaskDoc {
#line 576 "cc/lower/ast.cch"
    CcSpan comment;
#line 576 "cc/lower/ast.cch"
} CcTaskDoc;
typedef struct CcMacroCall {
#line 577 "cc/lower/ast.cch"
    CcExpr *call;
#line 577 "cc/lower/ast.cch"
    bool semi;
#line 577 "cc/lower/ast.cch"
} CcMacroCall; /* NAME(args) at file scope */
typedef struct CcTopStmt {
#line 578 "cc/lower/ast.cch"
    CcStmt *s;
#line 578 "cc/lower/ast.cch"
} CcTopStmt; /* a statement at file scope (.shcc) */


typedef enum { CcDeclK_var, CcDeclK_func, CcDeclK_typedef_, CcDeclK_tagged, CcDeclK_static_assert_, CcDeclK_pp, CcDeclK_empty, CcDeclK_typehooks, CcDeclK_typeview, CcDeclK_variant, CcDeclK_grammar, CcDeclK_factory, CcDeclK_comptime_fn, CcDeclK_comptime_block, CcDeclK_comptime_if, CcDeclK_scoped_type, CcDeclK_pragma_cc, CcDeclK_link, CcDeclK_task_doc, CcDeclK_macro_call, CcDeclK_stmt, CcDeclK_raw } CcDeclKKind;
typedef struct CcDeclK { CcDeclKKind kind; union { CcVarDecl var; CcFuncDecl func; CcTypedefDecl typedef_; CcTaggedDecl tagged; CcStaticAssert static_assert_; CcPpDecl pp; CcTypehooks typehooks; CcTypeview typeview; CcVariantDecl variant; CcGrammarDecl grammar; CcFactoryDecl factory; CcComptimeFn comptime_fn; CcBlock comptime_block; CcComptimeDeclIf comptime_if; CcScopedTypeDecl scoped_type; CcPragmaCc pragma_cc; CcLinkDecl link; CcTaskDoc task_doc; CcMacroCall macro_call; CcTopStmt stmt; CCSlice raw; } u; } CcDeclK;
#line 580 "cc/lower/ast.cch"

#line 604 "cc/lower/ast.cch"

struct CcDecl {
    CcSpan span;
    uint32_t specs; /* CC_SPEC_* */
    CCVec_CcAttr attrs;
    CcDeclK k;
};

/* ---- Translation unit ------------------------------------------------- */

typedef struct CcUnit {
    CCArena arena; /* owns the tape, every node, every list, every name */
    CcTape tape;
    CcDeclList decls;
    bool has_shebang;
    CCVec_CCSlice typedef_names; /* file-scope typedef names, for the declaration/expression ambiguity */
    CCVec_CCSlice assumed_types; /* identifiers parsed as type names on faith; the index confirms them */
} CcUnit;
typedef CcUnit *CcUnitRef; /* beside the definition: a pointer typedef names its pointee to the extractor */

/* ---- Constructors and accessors --------------------------------------- */

/* Every constructor allocates in `a` and takes the span of the construct. */
CcType *cc_type_named(CCSlice name, CcSpan span, CCArena a);
CcType *cc_type_pointer(CcType *pointee, CcSpan span, CCArena a);
CcType *cc_type_result(CcType *value, CcType *err, bool optional, CcSpan span, CCArena a);
CcExpr *cc_expr_ident(CCSlice name, CcSpan span, CCArena a);
CcExpr *cc_expr_call(CcExpr *callee, CcSpan span, CCArena a); /* args pushed after: e->call.args.push(x) */
CcExpr *cc_expr_member(CcExpr *a, CCSlice name, bool arrow, CcSpan span, CCArena arena);
CcExpr *cc_expr_unary(CcOp op, CcExpr *a, CcSpan span, CCArena arena);
CcExpr *cc_expr_binary(CcOp op, CcExpr *a, CcExpr *b, CcSpan span, CCArena arena);
CcStmt *cc_stmt_expr(CcExpr *e, CcSpan span, CCArena a);
CcStmt *cc_stmt_block(CcSpan span, CCArena a);
CcStmt *cc_stmt_if(CcExpr *cond, CcStmt *then, CcStmt *els, CcSpan span, CCArena a);
CcStmt *cc_stmt_return(CcExpr *value, CcSpan span, CCArena a);
CcStmt *cc_stmt_goto(CCSlice label, CcSpan span, CCArena a);
CcStmt *cc_stmt_label(CCSlice name, CcStmt *inner, CcSpan span, CCArena a);
CcDecl *cc_decl_var(CcType *type, CCSlice name, CcInit *init, CcSpan span, CCArena a);

/* Kind names in the user's vocabulary, for diagnostics: "unwrap", "@parallel for". */
CCSlice CcExpr_kind_name(const CcExpr *e);
CCSlice CcStmt_kind_name(const CcStmt *s);
CCSlice CcDecl_kind_name(const CcDecl *d);
CCSlice CcType_kind_name(const CcType *t);

/* t.is_named("CCArena"), t.is_pointer(), t.is_result(): the questions the
 * index and the lowerings ask most; each is one `@switch` in ast.ccs. */
bool CcType_is_named(const CcType *t, const char *name);
bool CcType_is_pointer(const CcType *t);
bool CcType_is_result(const CcType *t);
bool CcType_is_void(const CcType *t);

/* u.loc(span): user coordinates of a span's first token. */
CcLoc CcUnit_loc(const CcUnit *u, CcSpan span);
/* u.text(span): the source bytes a span covers, without leading trivia. */
CCSlice CcUnit_text(const CcUnit *u, CcSpan span);

/* Passes that only read the tree take this face. */

typedef CcUnit CcUnit_Restrict_Read;
#line 662 "cc/lower/ast.cch"


#endif
