#line 1 "cc/lower/print.cch"
#pragma once
#line 1 "cc/lower/print.cch"
/* Printer: CcUnit → C text with `#line` at every change, plus a source map.
 *
 * Identity mode replays every token with its trivia and must reproduce the
 * input byte for byte (the M1 gate). Lowered mode prints nodes; wherever
 * the next line's user line differs from the one implied by the previous
 * line, a `#line N "path"` is emitted first, and every emitted line is
 * recorded as (emit line → user path, line, column delta) so host
 * diagnostics map back. Long constructs print one operand per line; there
 * are no one-line statement expressions.
 *
 * Lifetimes: the product and the map live in the arena the caller passes,
 * which must outlive the host compile that reads them. */

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 13 "cc/lower/print.cch"

#line 13 "cc/lower/print.cch"
#ifndef CC_LOWER_PRINT_CCH
#define CC_LOWER_PRINT_CCH

#include "index.h"
#line 15 "cc/lower/print.cch"



#include <ccc/cc_result.h>

#line 17 "cc/lower/print.cch"

#line 17 "cc/lower/print.cch"
typedef struct CcSrcMapEntry {
    uint32_t emit_line;
    CCSlice path;
    uint32_t line;
    int32_t col_delta; /* emit col - user col for text copied verbatim; 0 when unknown */
} CcSrcMapEntry;


#ifndef CC_HEADER_VEC_CCVec_CcSrcMapEntry
#define CC_HEADER_VEC_CCVec_CcSrcMapEntry
/* generic CCVec_CcSrcMapEntry */

#ifdef CC_HAS_CCSLICE_CcSrcMapEntry
CC_VEC_DECL_ARENA_TSLICE(CcSrcMapEntry, CCVec_CcSrcMapEntry, CCSlice_CcSrcMapEntry)
#else
CC_VEC_DECL_ARENA(CcSrcMapEntry, CCVec_CcSrcMapEntry)
#endif
static inline CCVec_CcSrcMapEntry cc__CCVec_CcSrcMapEntry_new(CCArena __a) {
    return CCVec_CcSrcMapEntry_init(__a, 0);
}
#define CCVec_CcSrcMapEntry_new(ar) cc__CCVec_CcSrcMapEntry_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcSrcMapEntry (serdes) */
static const cc_type_info __cc_ti_CCVec_CcSrcMapEntry = { .name = "CCVec_CcSrcMapEntry", .mangled = "CCVec_CcSrcMapEntry", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcSrcMapEntry)), .align = (uint32_t)(_Alignof(CCVec_CcSrcMapEntry)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcSrcMapEntry(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcSrcMapEntry);
}
#endif
#line 24 "cc/lower/print.cch"

#line 24 "cc/lower/print.cch"
typedef struct CcSrcMap {
    CCVec_CcSrcMapEntry entries; /* ascending emit_line */
} CcSrcMap;
/* map.user_loc(emit_line, emit_col) */
CcLoc CcSrcMap_user_loc(const CcSrcMap *m, uint32_t emit_line, uint32_t emit_col);

typedef struct CcPrintOpts {
    bool identity; /* replay tokens verbatim */
    bool line_directives; /* honour #pragma(@linenumbers): off drops #line, keeps the map */
    CCSlice path; /* spelling for #line: what the host compiler can open */
    bool header_mode; /* printing a lowered .cch as .h */
    bool header_owned; /* a module face: its unit compiles every body that is not static inline */
} CcPrintOpts;

typedef struct CcProduct {
    CCString text;
    CcSrcMap map;
} CcProduct;

/* Print the unit. Every problem the printer finds (a token no node
 * reaches, a gap or an overlap between top-level spans, a node with an
 * invalid span) is an error on `ds`, at the token that caused it. Identity
 * mode fails, at the first byte that differs, rather than passing off text
 * that is not the input; lowered mode returns the product beside its
 * diagnostics, so the driver decides. */

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcProduct_CcDiag_DEFINED
#define CCResult_CcProduct_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcProduct_CcDiag, CcProduct, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 49 "cc/lower/print.cch"

#line 49 "cc/lower/print.cch"
CCResult_CcProduct_CcDiag cc_print_unit(const CcUnit *u, const CcIndex *ix, CcPrintOpts opts, CcDiags *ds, CCArena a);

/* Pieces, for tests and for lowerings that need a spelling: t.spell(name,
 * tape, a). Literal tokens are read from `tape`, the one the node's span
 * indexes (the unit's, or a template slot's own). */
CCString CcType_spell(const CcType *t, CCSlice declarator, const CcTape *tape, CCArena a); /* "int (*name)(void)" */
CCString CcExpr_spell(const CcExpr *e, const CcTape *tape, CCArena a);
CCString CcStmt_spell(const CcStmt *s, const CcTape *tape, CCArena a);

#endif
