#line 1 "cc/lower/ccparse.ccs"

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 1 "cc/lower/ccparse.ccs"

#line 1 "cc/lower/ccparse.ccs"
/* ccparse: the clean lowerer's parser as a tool, in Concurrent-C.
 *
 *   ccparse [--check] FILE...          `ok FILE (N decls)` or the diagnostics
 *   ccparse --dump FILE...             the tree, in the reference tool's format
 *   ccparse --known-types LIST FILE... extra typedef names, one per line (repeatable)
 *   ccparse --collect-types OUT FILE.. append every file-scope typedef name seen to OUT
 *   ccparse --mode source|header|script
 *   ccparse --quiet                    only print files with diagnostics
 * Output is byte-identical to out/cc/bin/ccparse (the C11 reference). */

#include "lower.h"
#line 10 "cc/lower/ccparse.ccs"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>


#ifndef CC_HEADER_VEC_CCVec_CCSlice
#define CC_HEADER_VEC_CCVec_CCSlice
/* generic CCVec_CCSlice */

#ifdef CC_HAS_CCSLICE_CCSlice
CC_VEC_DECL_ARENA_TSLICE(CCSlice, CCVec_CCSlice, CCSlice_CCSlice)
#else
CC_VEC_DECL_ARENA(CCSlice, CCVec_CCSlice)
#endif
static inline CCVec_CCSlice cc__CCVec_CCSlice_new(CCArena __a) {
    return CCVec_CCSlice_init(__a, 0);
}
#define CCVec_CCSlice_new(ar) cc__CCVec_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CCSlice (serdes) */
static const cc_type_info __cc_ti_CCVec_CCSlice = { .name = "CCVec_CCSlice", .mangled = "CCVec_CCSlice", .id = 0, .size = (uint32_t)(sizeof(CCVec_CCSlice)), .align = (uint32_t)(_Alignof(CCVec_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CCSlice(void) {
    cc_type_info_register(&__cc_ti_CCVec_CCSlice);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcDiag
#define CC_HEADER_VEC_CCVec_CcDiag
/* generic CCVec_CcDiag */

#ifdef CC_HAS_CCSLICE_CcDiag
CC_VEC_DECL_ARENA_TSLICE(CcDiag, CCVec_CcDiag, CCSlice_CcDiag)
#else
CC_VEC_DECL_ARENA(CcDiag, CCVec_CcDiag)
#endif
static inline CCVec_CcDiag cc__CCVec_CcDiag_new(CCArena __a) {
    return CCVec_CcDiag_init(__a, 0);
}
#define CCVec_CcDiag_new(ar) cc__CCVec_CcDiag_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDiag (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDiag = { .name = "CCVec_CcDiag", .mangled = "CCVec_CcDiag", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDiag)), .align = (uint32_t)(_Alignof(CCVec_CcDiag)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDiag(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDiag);
}
#endif
#line 16 "cc/lower/ccparse.ccs"

#line 16 "cc/lower/ccparse.ccs"
static CCSlice read_whole_file(const char *path, CCArena a, bool *ok) {
    FILE *fp = fopen(path, "rb");
    long n;
    char *buf;
    *ok = false;
    if (!fp)
#line 21 "cc/lower/ccparse.ccs"
        return CC_SLICE_LIT("");
    fseek(fp, 0, SEEK_END);
    n = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    if (n < 0)
#line 25 "cc/lower/ccparse.ccs"
        n = 0;
    buf = cc_arena_alloc(a, (size_t)(n) + 1, 1);
    if (n > 0 && fread(buf, 1, (size_t)(n), fp) != (size_t)(n)) {
#line 27 "cc/lower/ccparse.ccs"
        fclose(fp);
#line 27 "cc/lower/ccparse.ccs"
        return CC_SLICE_LIT("");
#line 27 "cc/lower/ccparse.ccs"
    }
    buf[n] = 0;
    fclose(fp);
    *ok = true;
    return cc_slice_from_buffer(buf, (size_t)(n));
}

static CCSlice source_of(CCSlice path, void *ctx, bool *physical) {
    (void)(path);
    *physical = true;
    return *(CCSlice *)(ctx);
}

static CcUnitMode mode_of(const char *path, const char *override) {
    size_t n = strlen(path);
    if (override) {
        if (!strcmp(override, "header"))
#line 43 "cc/lower/ccparse.ccs"
            return CC_UNIT_HEADER;
        if (!strcmp(override, "script"))
#line 44 "cc/lower/ccparse.ccs"
            return CC_UNIT_SCRIPT;
        return CC_UNIT_SOURCE;
    }
    if (n >= 4 && !strcmp(path + n - 4, ".cch"))
#line 47 "cc/lower/ccparse.ccs"
        return CC_UNIT_HEADER;
    if (n >= 5 && !strcmp(path + n - 5, ".shcc"))
#line 48 "cc/lower/ccparse.ccs"
        return CC_UNIT_SCRIPT;
    return CC_UNIT_SOURCE;
}

/* Known type names: read into the tool's arena, one per line, `#` lines ignored. */
static void load_known(const char *path, CCVec_CCSlice *known, CCArena a) {
    bool ok;
    CCSlice text = read_whole_file(path, a, &ok);
    size_t i = 0;
    if (!ok) {
#line 57 "cc/lower/ccparse.ccs"
        fprintf(stderr, "ccparse: cannot open %s: %s\n", path, strerror(errno));
#line 57 "cc/lower/ccparse.ccs"
        exit(2);
#line 57 "cc/lower/ccparse.ccs"
    }
    while (i < text.len) {
        size_t s = i;
        size_t e;
        while (i < text.len && text.ptr[i] != '\n')
#line 61 "cc/lower/ccparse.ccs"
            i++;
        e = i;
        if (i < text.len)
#line 63 "cc/lower/ccparse.ccs"
            i++;
        while (e > s && (text.ptr[e - 1] == '\r' || text.ptr[e - 1] == ' ' || text.ptr[e - 1] == '\t'))
#line 64 "cc/lower/ccparse.ccs"
            e--;
        while (s < e && (text.ptr[s] == ' ' || text.ptr[s] == '\t'))
#line 65 "cc/lower/ccparse.ccs"
            s++;
        if (e > s && text.ptr[s] != '#')
#line 66 "cc/lower/ccparse.ccs"
            CCVec_CCSlice_push(known, cc_slice_from_buffer((char *)(text.ptr) + s, e - s));
    }
}

int main(int argc, char **argv) {
    int __cc_retval;
#line 71 "cc/lower/ccparse.ccs"
    int __cc_defer_on_1 = 0;
#line 71 "cc/lower/ccparse.ccs"
    CCArena tool = cc_arena_heap(megabytes(8));
#line 71 "cc/lower/ccparse.ccs"
    __cc_defer_on_1 = 1;
    CCVec_CCSlice known = CCVec_CCSlice_new(tool);
    const char *collect = NULL;
    const char *mode_override = NULL;
    bool dump = false;
    bool quiet = false;
    int rc = 0;
    int nfiles = 0;
    int i;
    for (i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--dump")) {
#line 81 "cc/lower/ccparse.ccs"
            dump = true;
#line 81 "cc/lower/ccparse.ccs"
            continue;
#line 81 "cc/lower/ccparse.ccs"
        }
        if (!strcmp(argv[i], "--check"))
#line 82 "cc/lower/ccparse.ccs"
            continue;
        if (!strcmp(argv[i], "--quiet")) {
#line 83 "cc/lower/ccparse.ccs"
            quiet = true;
#line 83 "cc/lower/ccparse.ccs"
            continue;
#line 83 "cc/lower/ccparse.ccs"
        }
        if (!strcmp(argv[i], "--known-types") && i + 1 < argc) {
#line 84 "cc/lower/ccparse.ccs"
            load_known(argv[++i], &known, tool);
#line 84 "cc/lower/ccparse.ccs"
            continue;
#line 84 "cc/lower/ccparse.ccs"
        }
        if (!strcmp(argv[i], "--collect-types") && i + 1 < argc) {
#line 85 "cc/lower/ccparse.ccs"
            collect = argv[++i];
#line 85 "cc/lower/ccparse.ccs"
            continue;
#line 85 "cc/lower/ccparse.ccs"
        }
        if (!strcmp(argv[i], "--mode") && i + 1 < argc) {
#line 86 "cc/lower/ccparse.ccs"
            mode_override = argv[++i];
#line 86 "cc/lower/ccparse.ccs"
            continue;
#line 86 "cc/lower/ccparse.ccs"
        }
        if (argv[i][0] == '-' && argv[i][1]) {
#line 87 "cc/lower/ccparse.ccs"
            fprintf(stderr, "ccparse: unknown option %s\n", argv[i]);
#line 87 "cc/lower/ccparse.ccs"
            {
#line 87 "cc/lower/ccparse.ccs"
                __cc_retval = 2;
#line 87 "cc/lower/ccparse.ccs"
                goto __cc_cleanup;
#line 87 "cc/lower/ccparse.ccs"
            }
#line 87 "cc/lower/ccparse.ccs"
        }
        nfiles++;
        {
            int __cc_defer_on_2 = 0;
#line 90 "cc/lower/ccparse.ccs"
            CCArena a = cc_arena_heap(megabytes(64));
#line 90 "cc/lower/ccparse.ccs"
            __cc_defer_on_2 = 1;
            CcDiags ds = CcDiags_new(a);
            CcParseOpts opts;
            CcUnit *u;
            bool ok;
            const char *path = argv[i];
            CCSlice src = read_whole_file(path, a, &ok);
            if (!ok) {
#line 97 "cc/lower/ccparse.ccs"
                fprintf(stderr, "ccparse: cannot read %s: %s\n", path, strerror(errno));
#line 97 "cc/lower/ccparse.ccs"
                rc = 2;
#line 97 "cc/lower/ccparse.ccs"
                {
#line 90 "cc/lower/ccparse.ccs"
                    if (__cc_defer_on_2) {
#line 90 "cc/lower/ccparse.ccs"
                        {
#line 90 "cc/lower/ccparse.ccs"
                            cc_arena_destroy(&a);
#line 90 "cc/lower/ccparse.ccs"
                        }
#line 90 "cc/lower/ccparse.ccs"
                    }
#line 97 "cc/lower/ccparse.ccs"
                    continue;
#line 97 "cc/lower/ccparse.ccs"
                }
#line 97 "cc/lower/ccparse.ccs"
            }
            opts.mode = mode_of(path, mode_override);
            opts.known_types = known;
            u = cc_parse_unit(cc_slice_from_buffer((char *)(path), strlen(path)), src, opts, &ds, a);
            if (dump)
#line 101 "cc/lower/ccparse.ccs"
                CcUnit_dump(u, stdout);
            {
                CCVec_CcDiag *items = &ds.items;
                size_t nd = CCVec_CcDiag_len(items);
                if (nd) {
                    CcDiags_print(&ds, stdout, source_of, &src);
                    if (CcDiags_has_errors(&ds))
#line 107 "cc/lower/ccparse.ccs"
                        rc = 1;
                } else if (!quiet) {
                    CcDeclList *dl = &u->decls;
                    size_t n = CCVec_CcDeclRef_len(dl);
                    printf("ok %s (%zu decls)\n", path, n);
                }
            }
            if (collect) {
                CCVec_CCSlice *names = &u->typedef_names;
                size_t k;
                size_t nn = CCVec_CCSlice_len(names);
                if (nn) {
                    FILE *out = fopen(collect, "a");
                    if (!out) {
#line 120 "cc/lower/ccparse.ccs"
                        fprintf(stderr, "ccparse: cannot append to %s: %s\n", collect, strerror(errno));
#line 120 "cc/lower/ccparse.ccs"
                        {
#line 120 "cc/lower/ccparse.ccs"
                            __cc_retval = 2;
#line 90 "cc/lower/ccparse.ccs"
                            if (__cc_defer_on_2) {
#line 90 "cc/lower/ccparse.ccs"
                                {
#line 90 "cc/lower/ccparse.ccs"
                                    cc_arena_destroy(&a);
#line 90 "cc/lower/ccparse.ccs"
                                }
#line 90 "cc/lower/ccparse.ccs"
                            }
#line 120 "cc/lower/ccparse.ccs"
                            goto __cc_cleanup;
#line 120 "cc/lower/ccparse.ccs"
                        }
#line 120 "cc/lower/ccparse.ccs"
                    }
                    for (k = 0; k < nn; k++) {
                        CCSlice nm = *CCVec_CCSlice_get_ptr(names, k);
                        fprintf(out, "%.*s\n", (int)(nm.len), nm.ptr);
                    }
                    fclose(out);
                }
            }
            fflush(stdout);
#line 128 "cc/lower/ccparse.ccs"
            {
#line 90 "cc/lower/ccparse.ccs"
                if (__cc_defer_on_2) {
#line 90 "cc/lower/ccparse.ccs"
                    {
#line 90 "cc/lower/ccparse.ccs"
                        cc_arena_destroy(&a);
#line 90 "cc/lower/ccparse.ccs"
                    }
#line 90 "cc/lower/ccparse.ccs"
                }
#line 90 "cc/lower/ccparse.ccs"
            }
#line 129 "cc/lower/ccparse.ccs"
        }
    }
    if (!nfiles) {
        fprintf(stderr, "usage: ccparse [--check|--dump] [--known-types LIST]... [--collect-types OUT] [--mode M] FILE...\n");
        {
#line 133 "cc/lower/ccparse.ccs"
            __cc_retval = 2;
#line 133 "cc/lower/ccparse.ccs"
            goto __cc_cleanup;
#line 133 "cc/lower/ccparse.ccs"
        }
    }
    {
#line 135 "cc/lower/ccparse.ccs"
        __cc_retval = rc;
#line 135 "cc/lower/ccparse.ccs"
        goto __cc_cleanup;
#line 135 "cc/lower/ccparse.ccs"
    }
#line 135 "cc/lower/ccparse.ccs"
    __cc_cleanup:;
#line 135 "cc/lower/ccparse.ccs"
    {
#line 71 "cc/lower/ccparse.ccs"
        if (__cc_defer_on_1) {
#line 71 "cc/lower/ccparse.ccs"
            {
#line 71 "cc/lower/ccparse.ccs"
                cc_arena_destroy(&tool);
#line 71 "cc/lower/ccparse.ccs"
            }
#line 71 "cc/lower/ccparse.ccs"
        }
#line 135 "cc/lower/ccparse.ccs"
        return __cc_retval;
#line 135 "cc/lower/ccparse.ccs"
    }
}
