#!/usr/bin/env bash
# Hard-go probe: shadow-lower real stdlib cc_exec.cch and compare the C
# surface to production lower_headers (out/include/ccc/cc_exec.h).
#
# Exit 0 when the API surface matches after normalizing guard style / banner.
# Also host-cc compiles a tiny TU against the shadow product.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SRC="$ROOT/cc/include/ccc/cc_exec.cch"
PROD="$ROOT/out/include/ccc/cc_exec.h"
SHADOW_SH="$ROOT/cc/shadow/shadow_lower.sh"
TMP="${TMPDIR:-/tmp}/cc_serdes_exec_$$"
mkdir -p "$TMP"

if [[ ! -f "$PROD" ]]; then
  echo "FAIL: missing production $PROD (build headers first)"
  exit 1
fi

"$SHADOW_SH" "$SRC" -o "$TMP/cc_exec.shadow.h"

python3 - "$TMP/cc_exec.shadow.h" "$PROD" "$TMP" <<'PY'
import pathlib, re, sys
sh_path, pr_path, tmp = map(pathlib.Path, sys.argv[1:4])

def norm(text: str, *, shadow: bool) -> str:
    out = []
    for ln in text.splitlines():
        s = ln.rstrip()
        if shadow and s.startswith("/* generated by"):
            continue
        if s == "#pragma once":
            continue
        if re.match(r"#ifndef\s+CC_EXEC_H\b", s):
            continue
        if re.match(r"#define\s+CC_EXEC_H\b", s):
            continue
        if s.startswith("#endif") and ("CC_EXEC" in s or s == "#endif"):
            continue
        # Provenance markers — compare C surface, not #line ledger.
        if re.match(r"\s*#line\s", s):
            continue
        # Shadow injects <stddef.h>; production pulls it via compat.
        if shadow and s == "#include <stddef.h>":
            continue
        out.append(s)
    # Collapse runs of blank lines to one; trim ends.
    flat = []
    blank = False
    for s in out:
        if not s.strip():
            if not blank:
                flat.append("")
            blank = True
        else:
            flat.append(s)
            blank = False
    while flat and not flat[0].strip():
        flat.pop(0)
    while flat and not flat[-1].strip():
        flat.pop()
    return "\n".join(flat) + "\n"

ns = norm(sh_path.read_text(), shadow=True)
np = norm(pr_path.read_text(), shadow=False)
(tmp / "shadow.norm.h").write_text(ns)
(tmp / "prod.norm.h").write_text(np)
if ns != np:
    print("FAIL: normalized shadow vs production cc_exec.h surface differs")
    import subprocess
    subprocess.run(["diff", "-u", str(tmp / "prod.norm.h"), str(tmp / "shadow.norm.h")])
    sys.exit(1)
print("diff_stdlib_exec: normalized C surface matches production cc_exec.h")
PY

# Host-consumable: compile a tiny TU with the shadow header.
cat > "$TMP/use.c" <<'EOF'
#include "cc_exec.h"
int main(void) {
    CCExecStats st;
    (void)st.workers;
    (void)cc_exec_init;
    (void)cc_exec_destroy;
    return 0;
}
EOF
cp "$TMP/cc_exec.shadow.h" "$TMP/cc_exec.h"
cc -std=c11 -I"$TMP" -I"$ROOT/out/include" -c "$TMP/use.c" -o "$TMP/use.o"
echo "diff_stdlib_exec: host cc -c OK"

# Keep a golden beside the experiment for smoke expect_golden path.
cp "$TMP/cc_exec.shadow.h" "$ROOT/cc/shadow/shadow/cc_exec.h.golden"
rm -rf "$TMP"
