#!/usr/bin/env bash
# Hard-go follow-on: shadow-lower real stdlib cc_nursery.cch vs production.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SRC="$ROOT/cc/include/ccc/cc_nursery.cch"
PROD="$ROOT/out/include/ccc/cc_nursery.h"
SHADOW_SH="$ROOT/cc/shadow/shadow_lower.sh"
TMP="${TMPDIR:-/tmp}/cc_serdes_nursery_$$"
mkdir -p "$TMP"

if [[ ! -f "$PROD" ]]; then
  echo "FAIL: missing production $PROD (build headers first)"
  exit 1
fi

"$SHADOW_SH" "$SRC" -o "$TMP/cc_nursery.shadow.h"

python3 - "$TMP/cc_nursery.shadow.h" "$PROD" "$TMP" <<'PY'
import pathlib, re, sys
sh_path, pr_path, tmp = map(pathlib.Path, sys.argv[1:4])

def strip_comptime_ifdef(text: str) -> str:
    """Historical: drop #ifdef CC_COMPTIME_SCAN…#endif (none left in nursery)."""
    out = []
    i = 0
    lines = text.splitlines()
    while i < len(lines):
        s = lines[i]
        if re.match(r"\s*#ifdef\s+CC_COMPTIME_SCAN\b", s):
            i += 1
            while i < len(lines) and not re.match(r"\s*#endif\b", lines[i]):
                i += 1
            if i < len(lines):
                i += 1
            continue
        out.append(s)
        i += 1
    return "\n".join(out) + "\n"

def norm(text: str, *, shadow: bool) -> str:
    text = strip_comptime_ifdef(text)
    out = []
    for ln in text.splitlines():
        s = ln.rstrip()
        if shadow and s.startswith("/* generated by"):
            continue
        if s == "#pragma once":
            continue
        if re.match(r"#ifndef\s+CC_NURSERY_H\b", s):
            continue
        if re.match(r"#define\s+CC_NURSERY_H\b", s):
            continue
        if s.startswith("#endif") and ("CC_NURSERY" in s or s == "#endif"):
            continue
        if re.match(r"\s*#line\s", s):
            continue
        if shadow and s == "#include <stddef.h>":
            continue
        out.append(s)
    flat = []
    blank = False
    for s in out:
        if not s.strip():
            if not blank:
                flat.append("")
            blank = True
            continue
        # Glue `if (cond)\n[{]\n stmt;` (shadow may split for #line safety).
        t = s.strip()
        if flat and flat[-1].lstrip().startswith("if (") and not flat[-1].rstrip().endswith(";"):
            if t == "{":
                flat[-1] = flat[-1].rstrip() + " {"
                blank = False
                continue
            if not t.startswith("if ") and t != "}":
                flat[-1] = flat[-1].rstrip() + " " + t
                blank = False
                continue
        flat.append(s)
        blank = False
    # Collapse `if (…) { return …; }` onto one line when body is a single return.
    joined = []
    i = 0
    while i < len(flat):
        s = flat[i]
        if (s.lstrip().startswith("if (") and s.rstrip().endswith("{")
                and i + 2 < len(flat)
                and flat[i + 1].lstrip().startswith("return ")
                and flat[i + 2].strip() == "}"):
            joined.append(s.rstrip() + " " + flat[i + 1].strip() + " }")
            i += 3
            continue
        joined.append(s)
        i += 1
    flat = joined
    while flat and not flat[0].strip():
        flat.pop(0)
    while flat and not flat[-1].strip():
        flat.pop()
    return "\n".join(flat) + "\n"

ns = norm(sh_path.read_text(), shadow=True)
np = norm(pr_path.read_text(), shadow=False)
(tmp / "shadow.norm.h").write_text(ns)
(tmp / "prod.norm.h").write_text(np)
if ns != np:
    print("FAIL: normalized shadow vs production cc_nursery.h surface differs")
    import subprocess
    subprocess.run(["diff", "-u", str(tmp / "prod.norm.h"), str(tmp / "shadow.norm.h")])
    sys.exit(1)
print("diff_stdlib_nursery: normalized C surface matches production")
PY

cat > "$TMP/use.c" <<'EOF'
#include "cc_nursery.h"
int main(void) {
    (void)cc_nursery_create;
    (void)cc_nursery_destroy;
    (void)cc_nursery_wait;
    return 0;
}
EOF
cp "$TMP/cc_nursery.shadow.h" "$TMP/cc_nursery.h"
cc -std=c11 -I"$TMP" -I"$ROOT/out/include" -c "$TMP/use.c" -o "$TMP/use.o"
echo "diff_stdlib_nursery: host cc -c OK"
cp "$TMP/cc_nursery.shadow.h" "$ROOT/cc/shadow/shadow/cc_nursery.h.golden"
rm -rf "$TMP"
