#!/usr/bin/env bash
# Hard-go follow-on: shadow-lower real stdlib cc_async_runtime.cch vs production.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SRC="$ROOT/cc/include/ccc/cc_async_runtime.cch"
PROD="$ROOT/out/include/ccc/cc_async_runtime.h"
SHADOW_SH="$ROOT/cc/shadow/shadow_lower.sh"
TMP="${TMPDIR:-/tmp}/cc_serdes_async_rt_$$"
mkdir -p "$TMP"

if [[ ! -f "$PROD" ]]; then
  echo "FAIL: missing production $PROD (build headers first)"
  exit 1
fi

"$SHADOW_SH" "$SRC" -o "$TMP/cc_async_runtime.shadow.h"

python3 - "$TMP/cc_async_runtime.shadow.h" "$PROD" "$TMP" <<'PY'
import pathlib, re, sys
sh_path, pr_path, tmp = map(pathlib.Path, sys.argv[1:4])

def norm(text: str, *, shadow: bool) -> str:
    out = []
    for ln in text.splitlines():
        s = ln.rstrip()
        if shadow and s.startswith("/* generated by"):
            continue
        if s == "#pragma once":
            continue
        if re.match(r"#ifndef\s+CC_ASYNC_RUNTIME_H\b", s):
            continue
        if re.match(r"#define\s+CC_ASYNC_RUNTIME_H\b", s):
            continue
        if s.startswith("#endif") and ("CC_ASYNC_RUNTIME" in s or s == "#endif"):
            continue
        if re.match(r"\s*#line\s", s):
            continue
        if shadow and s == "#include <stddef.h>":
            continue
        out.append(s)
    flat = []
    blank = False
    for s in out:
        if not s.strip():
            if not blank:
                flat.append("")
            blank = True
        else:
            flat.append(s)
            blank = False
    while flat and not flat[0].strip():
        flat.pop(0)
    while flat and not flat[-1].strip():
        flat.pop()
    return "\n".join(flat) + "\n"

ns = norm(sh_path.read_text(), shadow=True)
np = norm(pr_path.read_text(), shadow=False)
(tmp / "shadow.norm.h").write_text(ns)
(tmp / "prod.norm.h").write_text(np)
if ns != np:
    print("FAIL: normalized shadow vs production cc_async_runtime.h surface differs")
    import subprocess
    subprocess.run(["diff", "-u", str(tmp / "prod.norm.h"), str(tmp / "shadow.norm.h")])
    sys.exit(1)
print("diff_stdlib_async_runtime: normalized C surface matches production")
PY

cat > "$TMP/use.c" <<'EOF'
#include "cc_async_runtime.h"
int main(void) {
    (void)cc_async_runtime_init;
    (void)cc_async_runtime_backend_name;
    (void)cc_async_runtime_shutdown;
    return 0;
}
EOF
cp "$TMP/cc_async_runtime.shadow.h" "$TMP/cc_async_runtime.h"
cc -std=c11 -I"$TMP" -I"$ROOT/out/include" -c "$TMP/use.c" -o "$TMP/use.o"
echo "diff_stdlib_async_runtime: host cc -c OK"
cp "$TMP/cc_async_runtime.shadow.h" "$ROOT/cc/shadow/shadow/cc_async_runtime.h.golden"
rm -rf "$TMP"
