#line 1 "cc/lower/ccindex.ccs"

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 1 "cc/lower/ccindex.ccs"

#line 1 "cc/lower/ccindex.ccs"
/* ccindex: exercise the declaration index on real files, in Concurrent-C.
 *
 *   ccindex [-I dir]... --dump FILE            every symbol, type info, hook and Result spec
 *   ccindex [-I dir]... --resolve FILE Type m  the callee for `x.m()` on a receiver of type Type
 *   ccindex [-I dir]... --gaps FILE...         every UFCS call site in the files, classified by
 *                                              how the index resolves it (markdown on stdout)
 *   ccindex [-I dir]... --sites FILE           one line per UFCS site with its resolution
 *
 * The default include directory is cc/include (run from the repository
 * root). Diagnostics from the index and the parser print to stderr.
 * Output is byte-identical to out/cc/bin/ccindex (the C11 reference). */

#include "lower.h"
#line 12 "cc/lower/ccindex.ccs"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define SL(s) (int)(s).len, (const char*)(s).ptr


#ifndef CC_HEADER_VEC_CCVec_CCSlice
#define CC_HEADER_VEC_CCVec_CCSlice
/* generic CCVec_CCSlice */

#ifdef CC_HAS_CCSLICE_CCSlice
CC_VEC_DECL_ARENA_TSLICE(CCSlice, CCVec_CCSlice, CCSlice_CCSlice)
#else
CC_VEC_DECL_ARENA(CCSlice, CCVec_CCSlice)
#endif
static inline CCVec_CCSlice cc__CCVec_CCSlice_new(CCArena __a) {
    return CCVec_CCSlice_init(__a, 0);
}
#define CCVec_CCSlice_new(ar) cc__CCVec_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CCSlice (serdes) */
static const cc_type_info __cc_ti_CCVec_CCSlice = { .name = "CCVec_CCSlice", .mangled = "CCVec_CCSlice", .id = 0, .size = (uint32_t)(sizeof(CCVec_CCSlice)), .align = (uint32_t)(_Alignof(CCVec_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CCSlice(void) {
    cc_type_info_register(&__cc_ti_CCVec_CCSlice);
}
#endif
#line 20 "cc/lower/ccindex.ccs"

#line 20 "cc/lower/ccindex.ccs"

#include <ccc/cc_result.h>

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcMethodptr_CcDiag_DEFINED
#define CCResult_CcMethodptr_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcMethodptr_CcDiag, CcMethod *, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 20 "cc/lower/ccindex.ccs"

#line 20 "cc/lower/ccindex.ccs"
typedef struct Session {
    CCArena arena;
    CcDiags ds;
    CcIndex *ix;
    CcUnit *unit;
    CCSlice src;
} Session;

static CcNameList g_include_dirs;

static CCSlice read_whole_file(const char *path, CCArena a, bool *ok) {
    FILE *fp = fopen(path, "rb");
    long n;
    char *buf;
    *ok = false;
    if (!fp)
#line 35 "cc/lower/ccindex.ccs"
        return CC_SLICE_LIT("");
    fseek(fp, 0, SEEK_END);
    n = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    if (n < 0)
#line 39 "cc/lower/ccindex.ccs"
        n = 0;
    buf = cc_arena_alloc(a, (size_t)(n) + 1, 1);
    if (n > 0 && fread(buf, 1, (size_t)(n), fp) != (size_t)(n)) {
#line 41 "cc/lower/ccindex.ccs"
        fclose(fp);
#line 41 "cc/lower/ccindex.ccs"
        return CC_SLICE_LIT("");
#line 41 "cc/lower/ccindex.ccs"
    }
    buf[n] = 0;
    fclose(fp);
    *ok = true;
    return cc_slice_from_buffer(buf, (size_t)(n));
}

static CcUnitMode mode_for(const char *path) {
    size_t n = strlen(path);
    if (n > 4 && strcmp(path + n - 4, ".cch") == 0)
#line 50 "cc/lower/ccindex.ccs"
        return CC_UNIT_HEADER;
    if (n > 5 && strcmp(path + n - 5, ".shcc") == 0)
#line 51 "cc/lower/ccindex.ccs"
        return CC_UNIT_SCRIPT;
    return CC_UNIT_SOURCE;
}

/* Parse `text` as a unit with the index's typedef names, on a scratch sink. */
static CcUnit *parse_probe(Session *s, const char *label, CCSlice text, CcUnitMode mode, CcDiags *scratch) {
    CcParseOpts po;
    po.mode = mode;
    po.known_types = CcIndex_known_types(s->ix);
    return cc_parse_unit(cstr_slice(label), text, po, scratch, s->arena);
}

static bool session_open(Session *s, const char *path, CCArena a) {
    bool ok;
    CCSlice pathsl = cstr_slice(path);
    CcParseOpts po;
    s->arena = a;
    s->ds = CcDiags_new(a);
    s->ix = cc_index_new(g_include_dirs, cc_slice_empty(), &s->ds, a);
    s->src = read_whole_file(path, a, &ok);
    if (!ok) {
        fprintf(stderr, "ccindex: %s: %s\n", path, strerror(errno));
        return false;
    }
    po.mode = mode_for(path);
    po.known_types = CCVec_CCSlice_new(a);
    {
        /* the include scan lexes on a scratch sink; the parse reports */
        CcDiags scratch = CcDiags_new(a);
        CcTape tape = cc_lex(pathsl, s->src, &scratch, a);
        CcIndex_preload_includes(s->ix, &tape, po);
    }
    po.known_types = CcIndex_known_types(s->ix);
    s->unit = cc_parse_unit(pathsl, s->src, po, &s->ds, a);
    CcIndex_add_unit(s->ix, s->unit, po.mode == CC_UNIT_HEADER);
    return true;
}

static CCSlice session_source(CCSlice path, void *ctx, bool *physical) {
    (void)(path);
    (void)(ctx);
    *physical = true;
    return cc_slice_empty();
}

static void session_close(Session *s) {
    CcDiags_print(&s->ds, stderr, session_source, NULL);
}

static const char *sym_kind_name(CcSymKind k) {
    switch (k) {
        case CC_SYM_FUNC:
#line 102 "cc/lower/ccindex.ccs"
            return "func";
        case CC_SYM_VAR:
#line 103 "cc/lower/ccindex.ccs"
            return "var";
        case CC_SYM_TYPE:
#line 104 "cc/lower/ccindex.ccs"
            return "type";
        case CC_SYM_ENUMERATOR:
#line 105 "cc/lower/ccindex.ccs"
            return "enumerator";
        case CC_SYM_MACRO:
#line 106 "cc/lower/ccindex.ccs"
            return "macro";
    }
    return "?";
}

static CCSlice unit_label(const CcUnit *u) {
    return u && u->tape.path.len ? u->tape.path : CC_SLICE_LIT("?");
}

/* The symbol of any kind with this name, or NULL. */
/* ---- --dump ------------------------------------------------------------ */

/* "ret(p1, p2, ...)" for a function symbol. */
static CCSlice func_canon(Session *s, CcSym *sym, CcFuncType fn) {
    CCString sb = cc_string_new();
    CcParamList params = fn.params;
    size_t k;
    size_t n = CCVec_CcParam_len(&params);
    (void)(sym);
    cc_string_push_slice(&sb, CcIndex_canon(s->ix, fn.ret), s->arena);
    cc_string_push_char(&sb, '(', s->arena);
    for (k = 0; k < n; k++) {
        CcParam *p = CCVec_CcParam_get_ptr(&params, k);
        if (k)
#line 129 "cc/lower/ccindex.ccs"
            cc_string_push_cstr(&sb, ", ", s->arena);
        if (!p->type)
#line 130 "cc/lower/ccindex.ccs"
            cc_string_push_cstr(&sb, "...", s->arena);
#line 130 "cc/lower/ccindex.ccs"
        else {
            CCSlice pc = CcIndex_canon(s->ix, p->type);
#line 131 "cc/lower/ccindex.ccs"
            cc_string_push_slice(&sb, pc, s->arena);
#line 131 "cc/lower/ccindex.ccs"
        }
    }
    if (fn.variadic) {
        if (n)
#line 134 "cc/lower/ccindex.ccs"
            cc_string_push_cstr(&sb, ", ", s->arena);
        cc_string_push_cstr(&sb, "...", s->arena);
    }
    cc_string_push_char(&sb, ')', s->arena);
    return cc_string_persist_slice(s->arena, &sb);
}

static CCSlice sym_canon(Session *s, CcSym *sym) {
    if (sym->type) {
        if (sym->kind == CC_SYM_FUNC) {
            switch ((sym->type->k).kind) {
                case CcTypeK_func: {
#line 145 "cc/lower/ccindex.ccs"
                    CcFuncType fn = (sym->type->k).u.func;
#line 145 "cc/lower/ccindex.ccs"
                    return func_canon(s, sym, fn);
#line 145 "cc/lower/ccindex.ccs"
                }
                default:
#line 146 "cc/lower/ccindex.ccs"
                    break;
            }
        }
        return CcIndex_canon(s->ix, sym->type);
    }
    if (sym->kind == CC_SYM_MACRO && sym->macro)
#line 151 "cc/lower/ccindex.ccs"
        return cstr_slice(sym->macro->function_like ? "function-like" : "object-like");
    return CC_SLICE_LIT("-");
}

static void dump_symbols(Session *s) {
    CcIndex *ix = s->ix;
    CcSymList *symv = &ix->syms;
    size_t i;
    /* canon() on a symbol's type may register a Result spec whose expansion
     * appends symbols: the bound is re-read, as the reference does */
    printf("# symbols (%zu)\n", CCVec_CcSymRef_len(symv));
    for (i = 0; i < CCVec_CcSymRef_len(symv); i++) {
        CcSym *sym = *CCVec_CcSymRef_get_ptr(symv, i);
        CcLoc loc = CcSym_loc(sym);
        CCSlice canon = sym_canon(s, sym);
        printf("%s %.*s : %.*s (%.*s:%u)%s%s\n", sym_kind_name(sym->kind), SL(sym->name), SL(canon), loc.path.len ? (int)(loc.path.len) : 1, loc.path.len ? loc.path.ptr : "?", loc.line, sym->kind == CC_SYM_FUNC && CcSym_noreturn(sym) ? " [noreturn]" : "", sym->is_definition && sym->kind == CC_SYM_FUNC ? " [definition]" : "");
#line 170 "cc/lower/ccindex.ccs"
    }
}

static void dump_hook_regs(Session *s) {
    CcHookRegList *hookv = &s->ix->hooks;
    size_t i;
    size_t n = CCVec_CcHookRegRef_len(hookv);
    printf("# typehooks (%zu)\n", n);
    for (i = 0; i < n; i++) {
        CcHookReg *h = *CCVec_CcHookRegRef_get_ptr(hookv, i);
        printf("@typehooks on %.*s", SL(h->subject));
        if (h->create_fn.len)
#line 181 "cc/lower/ccindex.ccs"
            printf(" create=%.*s%s%.*s", SL(h->create_fn), h->create_fn2.len ? "," : "", SL(h->create_fn2));
        if (h->pre_destroy_fn.len)
#line 182 "cc/lower/ccindex.ccs"
            printf(" pre_destroy=%.*s", SL(h->pre_destroy_fn));
        if (h->destroy_fn.len)
#line 183 "cc/lower/ccindex.ccs"
            printf(" destroy=%.*s", SL(h->destroy_fn));
        if (h->ufcs_fn.len) {
            CcUfcsRuleList *rulev = &h->rules;
            size_t r = CCVec_CcUfcsRule_len(rulev);
            printf(" ufcs=%.*s", SL(h->ufcs_fn));
            if (h->ufcs_prefix.len)
#line 188 "cc/lower/ccindex.ccs"
                printf(" [prefix %.*s%s]", SL(h->ufcs_prefix), h->ufcs_prefix_by_value ? " by-value" : "");
            if (h->ufcs_rejects)
#line 189 "cc/lower/ccindex.ccs"
                printf(" [rejects]");
            if (h->ufcs_opaque)
#line 190 "cc/lower/ccindex.ccs"
                printf(" [opaque]");
            while (r--) {
                CcUfcsRule *rule = CCVec_CcUfcsRule_get_ptr(rulev, r);
                printf(" %.*s->%.*s%s", SL(rule->method), SL(rule->callee), rule->by_value ? "(v)" : "");
            }
        }
        if (h->has_len)
#line 196 "cc/lower/ccindex.ccs"
            printf(" len");
        if (h->has_access)
#line 197 "cc/lower/ccindex.ccs"
            printf(" access");
        if (h->has_cast)
#line 198 "cc/lower/ccindex.ccs"
            printf(" cast");
        if (h->has_niche)
#line 199 "cc/lower/ccindex.ccs"
            printf(" niche");
        if (h->has_sink)
#line 200 "cc/lower/ccindex.ccs"
            printf(" ufcs_sink");
        printf("\n");
    }
}

static void dump_type_infos(Session *s) {
    CcTypeInfoList *infov = &s->ix->types;
    size_t i;
    printf("# types (%zu)\n", CCVec_CcTypeInfoRef_len(infov));
    for (i = 0; i < CCVec_CcTypeInfoRef_len(infov); i++) {
        CcTypeInfo *t = *CCVec_CcTypeInfoRef_get_ptr(infov, i);
        CcMethodList ms = CcIndex_methods_of(s->ix, t);
        size_t k;
        size_t nm = CCVec_CcMethodRef_len(&ms);
        printf("type %.*s", SL(t->name));
        if (t->family.len)
#line 215 "cc/lower/ccindex.ccs"
            printf(" family=%.*s", SL(t->family));
        if (t->hooks)
#line 216 "cc/lower/ccindex.ccs"
            printf(" hooks=%.*s", SL(t->hooks->subject));
        if (t->create_fn.len)
#line 217 "cc/lower/ccindex.ccs"
            printf(" create=%.*s", SL(t->create_fn));
        if (t->pre_destroy_fn.len)
#line 218 "cc/lower/ccindex.ccs"
            printf(" pre_destroy=%.*s", SL(t->pre_destroy_fn));
        if (t->destroy_fn.len)
#line 219 "cc/lower/ccindex.ccs"
            printf(" destroy=%.*s", SL(t->destroy_fn));
        if (t->ufcs_registered_by.len)
#line 220 "cc/lower/ccindex.ccs"
            printf(" registered=%.*s", SL(t->ufcs_registered_by));
        if (t->is_result)
#line 221 "cc/lower/ccindex.ccs"
            printf(" result%s%s", t->result_optional ? " optional" : "", t->result_from_header ? " header-declared" : "");
        printf("\n");
        for (k = 0; k < nm; k++) {
            CcMethod *m = *CCVec_CcMethodRef_get_ptr(&ms, k);
            printf("    .%.*s -> %.*s%s [%.*s] %.*s\n", SL(m->method), SL(m->callee), m->recv_by_ptr ? "(&recv)" : "(recv)", SL(m->source), SL(m->origin));
#line 227 "cc/lower/ccindex.ccs"
        }
    }
}

static void dump_result_specs(Session *s) {
    CcIndex *ix = s->ix;
    CcTypeInfoList *specv = &ix->result_specs;
    CcTypeInfoList *infov = &ix->types;
    size_t i;
    printf("# result specs used by the unit (%zu)\n", CCVec_CcTypeInfoRef_len(specv));
    for (i = 0; i < CCVec_CcTypeInfoRef_len(specv); i++) {
        CcTypeInfo *t = *CCVec_CcTypeInfoRef_get_ptr(specv, i);
        CCSlice v = t->result_value ? CcIndex_canon(ix, t->result_value) : CC_SLICE_LIT("void");
        CCSlice e = t->result_err ? CcIndex_canon(ix, t->result_err) : CC_SLICE_LIT("?");
        printf("%.*s : %.*s !> %.*s%s : ", SL(t->name), SL(v), SL(e), t->result_optional ? " (?> discardable)" : "");
        if (t->result_from_header) {
            CCSlice ul = unit_label(t->result_decl_unit);
            printf("declared in header %.*s:%u\n", SL(ul), t->result_decl_line);
        } else if (t->result_decl_unit) {
            CCSlice ul = unit_label(t->result_decl_unit);
            printf("declared in the unit %.*s:%u\n", SL(ul), t->result_decl_line);
        } else {
            printf("TU must emit the spec\n");
        }
    }
    printf("# result specs declared by headers\n");
    for (i = 0; i < CCVec_CcTypeInfoRef_len(infov); i++) {
        CcTypeInfo *t = *CCVec_CcTypeInfoRef_get_ptr(infov, i);
        if (t->is_result && t->result_from_header) {
            CCSlice ul = unit_label(t->result_decl_unit);
            printf("%.*s (%.*s:%u)\n", SL(t->name), SL(ul), t->result_decl_line);
        }
    }
}

static void dump_index(Session *s) {
    CcIndex *ix = s->ix;
    CcUnitList *unitv = &ix->units;
    CcIntList *hdrv = &ix->unit_is_header;
    size_t i;
    size_t n = CCVec_CcUnitRef_len(unitv);
    printf("# units (%zu)\n", n);
    for (i = 0; i < n; i++) {
        CCSlice ul = unit_label(*CCVec_CcUnitRef_get_ptr(unitv, i));
        printf("  %s %.*s\n", *CCVec_int_get_ptr(hdrv, i) ? "header" : "unit  ", SL(ul));
    }
    printf("# expansions: %u (parse errors inside them: %u)\n", ix->n_expansions, ix->n_expansion_errors);
    dump_symbols(s);
    dump_hook_regs(s);
    dump_type_infos(s);
    dump_result_specs(s);
}

/* ---- receiver typing for UFCS sites: typing.cch ------------------------ */

typedef struct Site {
    CCSlice type; /* canonical receiver type; empty when unknown */
    CCSlice method;
    CCSlice source; /* resolution source; empty when unresolved */
    CCSlice callee;
    CCSlice reason; /* diagnostic when unresolved */
    CCSlice file;
    uint32_t line;
    CCSlice recv_kind; /* expression kind of the receiver */
} Site;
typedef Site *SiteRef;

#ifndef CC_HEADER_VEC_CCVec_SiteRef
#define CC_HEADER_VEC_CCVec_SiteRef
/* generic CCVec_SiteRef */

#ifdef CC_HAS_CCSLICE_SiteRef
CC_VEC_DECL_ARENA_TSLICE(SiteRef, CCVec_SiteRef, CCSlice_SiteRef)
#else
CC_VEC_DECL_ARENA(SiteRef, CCVec_SiteRef)
#endif
static inline CCVec_SiteRef cc__CCVec_SiteRef_new(CCArena __a) {
    return CCVec_SiteRef_init(__a, 0);
}
#define CCVec_SiteRef_new(ar) cc__CCVec_SiteRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_SiteRef (serdes) */
static const cc_type_info __cc_ti_CCVec_SiteRef = { .name = "CCVec_SiteRef", .mangled = "CCVec_SiteRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_SiteRef)), .align = (uint32_t)(_Alignof(CCVec_SiteRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_SiteRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_SiteRef);
}
#endif
#line 293 "cc/lower/ccindex.ccs"

#line 293 "cc/lower/ccindex.ccs"
typedef CCVec_SiteRef SiteList;

/* The walker's callback: one Site per UFCS node, into the list in `env`. */
static void record_site(Walker *w, CcExpr *e, CcUfcs uf, CcType *rt, CcMethod *m, CCSlice tn, CCSlice reason) {
    SiteList *sitev = (SiteList *)(w->env);
    Site *site = cc_arena_alloc(w->arena, sizeof(Site), _Alignof(Site));
    CcLoc loc;
    memset(site, 0, sizeof(*site));
    loc = CcTape_loc(&w->unit->tape, e->span.first);
    site->method = uf.method;
    site->file = loc.path;
    site->line = loc.line;
    site->recv_kind = uf.recv ? CcExpr_kind_name(uf.recv) : CC_SLICE_LIT("?expr");
    if (rt) {
        site->type = tn;
        if (m) {
            site->source = m->source;
            site->callee = m->callee;
        } else {
            site->reason = reason;
        }
    }
    CCVec_SiteRef_push(sitev, site);
}

/* ---- --sites / --gaps -------------------------------------------------- */

typedef struct Count {
    CCSlice key;
    CCSlice key2;
    bool has_key2;
    size_t n;
    bool in_non_fail; /* at least one site outside an expected-failure test */
} Count;
typedef Count *CountRef;

#ifndef CC_HEADER_VEC_CCVec_CountRef
#define CC_HEADER_VEC_CCVec_CountRef
/* generic CCVec_CountRef */

#ifdef CC_HAS_CCSLICE_CountRef
CC_VEC_DECL_ARENA_TSLICE(CountRef, CCVec_CountRef, CCSlice_CountRef)
#else
CC_VEC_DECL_ARENA(CountRef, CCVec_CountRef)
#endif
static inline CCVec_CountRef cc__CCVec_CountRef_new(CCArena __a) {
    return CCVec_CountRef_init(__a, 0);
}
#define CCVec_CountRef_new(ar) cc__CCVec_CountRef_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CountRef (serdes) */
static const cc_type_info __cc_ti_CCVec_CountRef = { .name = "CCVec_CountRef", .mangled = "CCVec_CountRef", .id = 0, .size = (uint32_t)(sizeof(CCVec_CountRef)), .align = (uint32_t)(_Alignof(CCVec_CountRef)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CountRef(void) {
    cc_type_info_register(&__cc_ti_CCVec_CountRef);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcDiag
#define CC_HEADER_VEC_CCVec_CcDiag
/* generic CCVec_CcDiag */

#ifdef CC_HAS_CCSLICE_CcDiag
CC_VEC_DECL_ARENA_TSLICE(CcDiag, CCVec_CcDiag, CCSlice_CcDiag)
#else
CC_VEC_DECL_ARENA(CcDiag, CCVec_CcDiag)
#endif
static inline CCVec_CcDiag cc__CCVec_CcDiag_new(CCArena __a) {
    return CCVec_CcDiag_init(__a, 0);
}
#define CCVec_CcDiag_new(ar) cc__CCVec_CcDiag_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDiag (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDiag = { .name = "CCVec_CcDiag", .mangled = "CCVec_CcDiag", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDiag)), .align = (uint32_t)(_Alignof(CCVec_CcDiag)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDiag(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDiag);
}
#endif
#line 328 "cc/lower/ccindex.ccs"

#line 328 "cc/lower/ccindex.ccs"
typedef CCVec_CountRef CountList;

static CCSlice agg_copy(CCArena a, CCSlice s) {
    char *out = cc_arena_alloc(a, s.len + 1, 1);
    if (s.len)
#line 332 "cc/lower/ccindex.ccs"
        memcpy(out, s.ptr, s.len);
    out[s.len] = 0;
    return cc_slice_from_buffer(out, s.len);
}

static Count *count_add(CCArena a, CountList *list, CCSlice key, CCSlice key2, bool has_key2) {
    size_t i;
    size_t n = CCVec_CountRef_len(list);
    Count *c;
    for (i = 0; i < n; i++) {
        c = *CCVec_CountRef_get_ptr(list, i);
        if (slice_eq(c->key, key) && ((!has_key2 && !c->has_key2) || (has_key2 && c->has_key2 && slice_eq(c->key2, key2)))) {
            c->n++;
            return c;
        }
    }
    c = cc_arena_alloc(a, sizeof(Count), _Alignof(Count));
    memset(c, 0, sizeof(*c));
    c->key = agg_copy(a, key);
    c->key2 = has_key2 ? agg_copy(a, key2) : cc_slice_empty();
    c->has_key2 = has_key2;
    c->n = 1;
    CCVec_CountRef_push(list, c);
    return c;
}

static int slice_cmp(CCSlice a, CCSlice b) {
    size_t n = a.len < b.len ? a.len : b.len;
    int c = n ? memcmp(a.ptr, b.ptr, n) : 0;
    if (c)
#line 361 "cc/lower/ccindex.ccs"
        return c;
    if (a.len != b.len)
#line 362 "cc/lower/ccindex.ccs"
        return a.len < b.len ? -1 : 1;
    return 0;
}

static int count_cmp(const void *pa, const void *pb) {
    const Count *a = *(Count *const *)(pa);
    const Count *b = *(Count *const *)(pb);
    if (a->n != b->n)
#line 369 "cc/lower/ccindex.ccs"
        return a->n < b->n ? 1 : -1;
    {
        int c = slice_cmp(a->key, b->key);
        if (c)
#line 372 "cc/lower/ccindex.ccs"
            return c;
    }
    if (!a->has_key2 || !b->has_key2)
#line 374 "cc/lower/ccindex.ccs"
        return 0;
    return slice_cmp(a->key2, b->key2);
}

/* The counts sorted by (n desc, key, key2): a copy of the list. */
static CountList count_sorted(CCArena a, CountList *list) {
    CountList arr = CCVec_CountRef_new(a);
    size_t i;
    size_t n = CCVec_CountRef_len(list);
    for (i = 0; i < n; i++) {
#line 383 "cc/lower/ccindex.ccs"
        Count *c = *CCVec_CountRef_get_ptr(list, i);
#line 383 "cc/lower/ccindex.ccs"
        CCVec_CountRef_push(&arr, c);
#line 383 "cc/lower/ccindex.ccs"
    }
    if (n > 1)
#line 384 "cc/lower/ccindex.ccs"
        qsort(CCVec_CountRef_data(&arr), n, sizeof(CountRef), count_cmp);
    return arr;
}

/* The `parse errors on its own lines` check: an error whose path is the file. */
static bool has_own_errors(Session *s, const char *path) {
    CCVec_CcDiag *itemv = &s->ds.items;
    size_t d;
    size_t n = CCVec_CcDiag_len(itemv);
    CCSlice p = cstr_slice(path);
    for (d = 0; d < n; d++) {
        CcDiag *dg = CCVec_CcDiag_get_ptr(itemv, d);
        if (dg->sev == CC_SEV_ERROR && dg->at.path.len && slice_eq(dg->at.path, p))
#line 396 "cc/lower/ccindex.ccs"
            return true;
    }
    return false;
}

static bool ends_with(const char *s, const char *suffix) {
    size_t n = strlen(s);
    size_t m = strlen(suffix);
    return n > m && strcmp(s + n - m, suffix) == 0;
}

typedef struct Gaps {
    CCArena agg;
    CountList by_source;
    CountList unresolved;
    CountList unknown_methods;
    CountList unknown_recv;
    CountList reasons;
    size_t total;
#line 414 "cc/lower/ccindex.ccs"
    size_t n_resolved;
#line 414 "cc/lower/ccindex.ccs"
    size_t n_unresolved;
#line 414 "cc/lower/ccindex.ccs"
    size_t n_unknown;
#line 414 "cc/lower/ccindex.ccs"
    size_t n_files;
#line 414 "cc/lower/ccindex.ccs"
    size_t n_parse_err_files;
} Gaps;

static void print_site(Site *site, const char *path) {
    CCSlice file = site->file.len ? site->file : cstr_slice(path);
    CCSlice type = site->type.len ? site->type : CC_SLICE_LIT("?");
    printf("%.*s:%u %.*s.%.*s -> ", SL(file), site->line, SL(type), SL(site->method));
    if (site->source.len)
#line 421 "cc/lower/ccindex.ccs"
        printf("%.*s [%.*s]\n", SL(site->callee), SL(site->source));
#line 421 "cc/lower/ccindex.ccs"
    else if (site->reason.len)
        printf("UNRESOLVED %.*s\n", SL(site->reason));
#line 422 "cc/lower/ccindex.ccs"
    else
        printf("UNRESOLVED receiver type unknown\n");
}

static void count_site(Gaps *g, Site *site, const char *path) {
    g->total++;
    if (site->source.len) {
        g->n_resolved++;
        count_add(g->agg, &g->by_source, site->source, cc_slice_empty(), false);
    } else if (site->type.len) {
        Count *c;
        bool is_fail = ends_with(path, "_fail.ccs");
        g->n_unresolved++;
        c = count_add(g->agg, &g->unresolved, site->type, site->method, true);
        if (!is_fail)
#line 436 "cc/lower/ccindex.ccs"
            c->in_non_fail = true;
        if (site->reason.len)
#line 437 "cc/lower/ccindex.ccs"
            count_add(g->agg, &g->reasons, site->reason, cc_slice_empty(), false);
    } else {
        g->n_unknown++;
        count_add(g->agg, &g->unknown_methods, site->method, cc_slice_empty(), false);
        count_add(g->agg, &g->unknown_recv, site->recv_kind, cc_slice_empty(), false);
    }
}

static void print_gaps(Gaps *g) {
    CountList arr;
    size_t k;
    size_t n;
    printf("Files: %zu (%zu with parse errors on their own lines). UFCS call sites: %zu.\n\n", g->n_files, g->n_parse_err_files, g->total);
    printf("| Outcome | Sites |\n|---|---|\n");
    arr = count_sorted(g->agg, &g->by_source);
    n = CCVec_CountRef_len(&arr);
    for (k = 0; k < n; k++) {
#line 453 "cc/lower/ccindex.ccs"
        Count *c = *CCVec_CountRef_get_ptr(&arr, k);
#line 453 "cc/lower/ccindex.ccs"
        printf("| resolved: %.*s | %zu |\n", SL(c->key), c->n);
#line 453 "cc/lower/ccindex.ccs"
    }
    printf("| resolved (all sources) | %zu |\n", g->n_resolved);
    printf("| unresolved, receiver type known | %zu |\n", g->n_unresolved);
    printf("| receiver type unknown | %zu |\n\n", g->n_unknown);
    printf("### Unresolved with a known receiver type\n\n");
    printf("(Type, method) pairs no declaration, hook or registration names. A pair whose every site is in a `*_fail.ccs` test is a diagnostic the test expects.\n\n| Receiver type | Method | Sites | Only in `_fail` tests |\n|---|---|---|---|\n");
    arr = count_sorted(g->agg, &g->unresolved);
    n = CCVec_CountRef_len(&arr);
    for (k = 0; k < n; k++) {
        Count *c = *CCVec_CountRef_get_ptr(&arr, k);
        printf("| `%.*s` | `%.*s` | %zu | %s |\n", SL(c->key), SL(c->key2), c->n, c->in_non_fail ? "" : "yes");
    }
    printf("\n### Receiver type unknown\n\nBy receiver expression kind:\n\n| Receiver kind | Sites |\n|---|---|\n");
    arr = count_sorted(g->agg, &g->unknown_recv);
    n = CCVec_CountRef_len(&arr);
    for (k = 0; k < n; k++) {
#line 468 "cc/lower/ccindex.ccs"
        Count *c = *CCVec_CountRef_get_ptr(&arr, k);
#line 468 "cc/lower/ccindex.ccs"
        printf("| %.*s | %zu |\n", SL(c->key), c->n);
#line 468 "cc/lower/ccindex.ccs"
    }
    printf("\nMost frequent methods on untyped receivers:\n\n| Method | Sites |\n|---|---|\n");
    arr = count_sorted(g->agg, &g->unknown_methods);
    n = CCVec_CountRef_len(&arr);
    for (k = 0; k < n && k < 40; k++) {
#line 472 "cc/lower/ccindex.ccs"
        Count *c = *CCVec_CountRef_get_ptr(&arr, k);
#line 472 "cc/lower/ccindex.ccs"
        printf("| `%.*s` | %zu |\n", SL(c->key), c->n);
#line 472 "cc/lower/ccindex.ccs"
    }
}

static void usage(void) {
    fprintf(stderr, "usage: ccindex [-I dir] --dump FILE | --resolve FILE Type method | --sites FILE | --gaps FILE...\n");
}

static int run_dump(const char *path) {
    int __cc_retval;
#line 480 "cc/lower/ccindex.ccs"
    int __cc_defer_on_1 = 0;
#line 480 "cc/lower/ccindex.ccs"
    CCArena a = cc_arena_heap(megabytes(256));
#line 480 "cc/lower/ccindex.ccs"
    __cc_defer_on_1 = 1;
    Session s;
    if (!session_open(&s, path, a)) {
#line 482 "cc/lower/ccindex.ccs"
        __cc_retval = 1;
#line 482 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 482 "cc/lower/ccindex.ccs"
    }
    dump_index(&s);
    session_close(&s);
    {
#line 485 "cc/lower/ccindex.ccs"
        __cc_retval = 0;
#line 485 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 485 "cc/lower/ccindex.ccs"
    }
#line 485 "cc/lower/ccindex.ccs"
    __cc_cleanup:;
#line 485 "cc/lower/ccindex.ccs"
    {
#line 480 "cc/lower/ccindex.ccs"
        if (__cc_defer_on_1) {
#line 480 "cc/lower/ccindex.ccs"
            {
#line 480 "cc/lower/ccindex.ccs"
                cc_arena_destroy(&a);
#line 480 "cc/lower/ccindex.ccs"
            }
#line 480 "cc/lower/ccindex.ccs"
        }
#line 485 "cc/lower/ccindex.ccs"
        return __cc_retval;
#line 485 "cc/lower/ccindex.ccs"
    }
}

/* A type spelling (`Vec::[int]`, `char[:]`, `int!>(CCError)`): parsed as a declaration. */
static CcTypeInfo *resolve_type_arg(Session *s, const char *spelling, bool *ok) {
    CCString sb = cc_string_new();
    CcDiags scratch = CcDiags_new(s->arena);
    CcUnit *u;
    CcDeclList *declv;
    CcType *t = NULL;
    *ok = false;
    cc_string_push_cstr(&sb, spelling, s->arena);
    cc_string_push_cstr(&sb, " __cc_probe;\n", s->arena);
    u = parse_probe(s, "<type>", cc_string_persist_slice(s->arena, &sb), CC_UNIT_HEADER, &scratch);
    declv = &u->decls;
    if (CCVec_CcDeclRef_len(declv) == 1)
#line 500 "cc/lower/ccindex.ccs"
        t = cc__decl_type_of(*CCVec_CcDeclRef_get_ptr(declv, 0));
    if (scratch.n_errors || !t) {
        CcDiags_print(&scratch, stderr, session_source, NULL);
        fprintf(stderr, "ccindex: cannot read the type '%s'\n", spelling);
        return NULL;
    }
    *ok = true;
    return CcIndex_type_get(s->ix, CcIndex_canon(s->ix, peel(t)));
}

static int run_resolve(const char *path, const char *type_arg, const char *method) {
    int __cc_retval;
#line 511 "cc/lower/ccindex.ccs"
    int __cc_defer_on_1 = 0;
#line 511 "cc/lower/ccindex.ccs"
    CCArena a = cc_arena_heap(megabytes(256));
#line 511 "cc/lower/ccindex.ccs"
    __cc_defer_on_1 = 1;
    Session s;
    CcTypeInfo *info;
    int rc;
    if (!session_open(&s, path, a)) {
#line 515 "cc/lower/ccindex.ccs"
        __cc_retval = 1;
#line 515 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 515 "cc/lower/ccindex.ccs"
    }
    if (strpbrk(type_arg, ":[*!? ")) {
        bool ok;
        info = resolve_type_arg(&s, type_arg, &ok);
        if (!ok) {
#line 519 "cc/lower/ccindex.ccs"
            __cc_retval = 2;
#line 519 "cc/lower/ccindex.ccs"
            goto __cc_cleanup;
#line 519 "cc/lower/ccindex.ccs"
        }
    } else {
        info = CcIndex_type_get(s.ix, cstr_slice(type_arg));
    }
    {
        CCResult_CcMethodptr_CcDiag r = CcIndex_method_recv(s.ix, info, cstr_slice(method), 0u, a);
        if (CCResult_CcMethodptr_CcDiag_is_ok(r)) {
            CcMethod *m = CCResult_CcMethodptr_CcDiag_value(r);
            printf("%s.%s -> %.*s(%srecv, ...) [%.*s] %.*s\n", type_arg, method, SL(m->callee), m->recv_by_ptr ? "&" : "", SL(m->source), SL(m->origin));
#line 529 "cc/lower/ccindex.ccs"
            rc = 0;
        } else {
            CcDiag d = CCResult_CcMethodptr_CcDiag_error(r);
            printf("error: %.*s\n", SL(d.msg));
            rc = 1;
        }
    }
    session_close(&s);
    {
#line 537 "cc/lower/ccindex.ccs"
        __cc_retval = rc;
#line 537 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 537 "cc/lower/ccindex.ccs"
    }
#line 537 "cc/lower/ccindex.ccs"
    __cc_cleanup:;
#line 537 "cc/lower/ccindex.ccs"
    {
#line 511 "cc/lower/ccindex.ccs"
        if (__cc_defer_on_1) {
#line 511 "cc/lower/ccindex.ccs"
            {
#line 511 "cc/lower/ccindex.ccs"
                cc_arena_destroy(&a);
#line 511 "cc/lower/ccindex.ccs"
            }
#line 511 "cc/lower/ccindex.ccs"
        }
#line 537 "cc/lower/ccindex.ccs"
        return __cc_retval;
#line 537 "cc/lower/ccindex.ccs"
    }
}

static int run_sites(int argc, char **argv, int i, bool gaps) {
    int __cc_retval;
#line 541 "cc/lower/ccindex.ccs"
    int __cc_defer_on_1 = 0;
#line 541 "cc/lower/ccindex.ccs"
    CCArena agg = cc_arena_heap(megabytes(16));
#line 541 "cc/lower/ccindex.ccs"
    __cc_defer_on_1 = 1;
    Gaps g;
    memset(&g, 0, sizeof g);
    g.agg = agg;
    g.by_source = CCVec_CountRef_new(agg);
    g.unresolved = CCVec_CountRef_new(agg);
    g.unknown_methods = CCVec_CountRef_new(agg);
    g.unknown_recv = CCVec_CountRef_new(agg);
    g.reasons = CCVec_CountRef_new(agg);
    for (; i < argc; i++) {
        int __cc_defer_on_2 = 0;
#line 551 "cc/lower/ccindex.ccs"
        CCArena a = cc_arena_heap(megabytes(256));
#line 551 "cc/lower/ccindex.ccs"
        __cc_defer_on_2 = 1;
        Session s;
        Walker w;
        SiteList sites;
        SiteList *sitev;
        size_t k;
        size_t ns;
        if (!session_open(&s, argv[i], a)) {
#line 551 "cc/lower/ccindex.ccs"
            if (__cc_defer_on_2) {
#line 551 "cc/lower/ccindex.ccs"
                {
#line 551 "cc/lower/ccindex.ccs"
                    cc_arena_destroy(&a);
#line 551 "cc/lower/ccindex.ccs"
                }
#line 551 "cc/lower/ccindex.ccs"
            }
#line 558 "cc/lower/ccindex.ccs"
            continue;
#line 558 "cc/lower/ccindex.ccs"
        }
        g.n_files++;
        memset(&w, 0, sizeof w);
        w.arena = a;
        w.ix = s.ix;
        w.unit = s.unit;
        sites = CCVec_SiteRef_new(a);
        w.on_ufcs = record_site;
        w.env = &sites;
        tw_unit(&w);
        if (has_own_errors(&s, argv[i])) {
            g.n_parse_err_files++;
            fprintf(stderr, "parse errors on its own lines: %s\n", argv[i]);
        }
        sitev = &sites;
        ns = CCVec_SiteRef_len(sitev);
        for (k = 0; k < ns; k++) {
            Site *site = *CCVec_SiteRef_get_ptr(sitev, k);
            if (!gaps)
#line 576 "cc/lower/ccindex.ccs"
                print_site(site, argv[i]);
            count_site(&g, site, argv[i]);
        }
        /* parse diagnostics are noise for the gap table */
        if (!gaps)
#line 580 "cc/lower/ccindex.ccs"
            session_close(&s);
#line 579 "cc/lower/ccindex.ccs"
        /* parse diagnostics are noise for the gap table */
        {
#line 551 "cc/lower/ccindex.ccs"
            if (__cc_defer_on_2) {
#line 551 "cc/lower/ccindex.ccs"
                {
#line 551 "cc/lower/ccindex.ccs"
                    cc_arena_destroy(&a);
#line 551 "cc/lower/ccindex.ccs"
                }
#line 551 "cc/lower/ccindex.ccs"
            }
#line 551 "cc/lower/ccindex.ccs"
        }
#line 581 "cc/lower/ccindex.ccs"
    }
    if (gaps)
#line 582 "cc/lower/ccindex.ccs"
        print_gaps(&g);
    {
#line 583 "cc/lower/ccindex.ccs"
        __cc_retval = 0;
#line 583 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 583 "cc/lower/ccindex.ccs"
    }
#line 583 "cc/lower/ccindex.ccs"
    __cc_cleanup:;
#line 583 "cc/lower/ccindex.ccs"
    {
#line 541 "cc/lower/ccindex.ccs"
        if (__cc_defer_on_1) {
#line 541 "cc/lower/ccindex.ccs"
            {
#line 541 "cc/lower/ccindex.ccs"
                cc_arena_destroy(&agg);
#line 541 "cc/lower/ccindex.ccs"
            }
#line 541 "cc/lower/ccindex.ccs"
        }
#line 583 "cc/lower/ccindex.ccs"
        return __cc_retval;
#line 583 "cc/lower/ccindex.ccs"
    }
}

int main(int argc, char **argv) {
    int __cc_retval;
#line 587 "cc/lower/ccindex.ccs"
    int __cc_defer_on_1 = 0;
#line 587 "cc/lower/ccindex.ccs"
    CCArena tool = cc_arena_heap(megabytes(1));
#line 587 "cc/lower/ccindex.ccs"
    __cc_defer_on_1 = 1;
    int i = 1;
    const char *mode = NULL;
    bool custom_dirs = false;
    g_include_dirs = CCVec_CCSlice_new(tool);
    CCVec_CCSlice_push(&g_include_dirs, CC_SLICE_LIT("cc/include"));
    while (i < argc && argv[i][0] == '-' && strcmp(argv[i], "--dump") && strcmp(argv[i], "--resolve") && strcmp(argv[i], "--gaps") && strcmp(argv[i], "--sites")) {
#line 595 "cc/lower/ccindex.ccs"
        if (strcmp(argv[i], "-I") == 0 && i + 1 < argc && CCVec_CCSlice_len(&g_include_dirs) < 15) {
            if (!custom_dirs) {
#line 596 "cc/lower/ccindex.ccs"
                CCVec_CCSlice_clear(&g_include_dirs);
#line 596 "cc/lower/ccindex.ccs"
                custom_dirs = true;
#line 596 "cc/lower/ccindex.ccs"
            }
            CCVec_CCSlice_push(&g_include_dirs, cstr_slice(argv[i + 1]));
            i += 2;
        } else {
            fprintf(stderr, "ccindex: unknown option %s\n", argv[i]);
            {
#line 601 "cc/lower/ccindex.ccs"
                __cc_retval = 2;
#line 601 "cc/lower/ccindex.ccs"
                goto __cc_cleanup;
#line 601 "cc/lower/ccindex.ccs"
            }
        }
    }
    if (i < argc)
#line 604 "cc/lower/ccindex.ccs"
        mode = argv[i++];
    if (!mode) {
#line 605 "cc/lower/ccindex.ccs"
        usage();
#line 605 "cc/lower/ccindex.ccs"
        {
#line 605 "cc/lower/ccindex.ccs"
            __cc_retval = 2;
#line 605 "cc/lower/ccindex.ccs"
            goto __cc_cleanup;
#line 605 "cc/lower/ccindex.ccs"
        }
#line 605 "cc/lower/ccindex.ccs"
    }
    if (strcmp(mode, "--dump") == 0 && i < argc) {
#line 606 "cc/lower/ccindex.ccs"
        __cc_retval = run_dump(argv[i]);
#line 606 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 606 "cc/lower/ccindex.ccs"
    }
    if (strcmp(mode, "--resolve") == 0 && i + 2 < argc) {
#line 607 "cc/lower/ccindex.ccs"
        __cc_retval = run_resolve(argv[i], argv[i + 1], argv[i + 2]);
#line 607 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 607 "cc/lower/ccindex.ccs"
    }
    if ((strcmp(mode, "--sites") == 0 || strcmp(mode, "--gaps") == 0) && i < argc) {
#line 608 "cc/lower/ccindex.ccs"
        __cc_retval = run_sites(argc, argv, i, strcmp(mode, "--gaps") == 0);
#line 608 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 608 "cc/lower/ccindex.ccs"
    }
    usage();
    {
#line 610 "cc/lower/ccindex.ccs"
        __cc_retval = 2;
#line 610 "cc/lower/ccindex.ccs"
        goto __cc_cleanup;
#line 610 "cc/lower/ccindex.ccs"
    }
#line 610 "cc/lower/ccindex.ccs"
    __cc_cleanup:;
#line 610 "cc/lower/ccindex.ccs"
    {
#line 587 "cc/lower/ccindex.ccs"
        if (__cc_defer_on_1) {
#line 587 "cc/lower/ccindex.ccs"
            {
#line 587 "cc/lower/ccindex.ccs"
                cc_arena_destroy(&tool);
#line 587 "cc/lower/ccindex.ccs"
            }
#line 587 "cc/lower/ccindex.ccs"
        }
#line 610 "cc/lower/ccindex.ccs"
        return __cc_retval;
#line 610 "cc/lower/ccindex.ccs"
    }
}
