#line 1 "cc/lower/cclower.ccs"

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 1 "cc/lower/cclower.ccs"

#line 1 "cc/lower/cclower.ccs"
/* cclower: drives the printer over real files, in Concurrent-C.
 *
 *   cclower --identity [--known-types F] FILE...
 *       Lex, parse and print in identity mode; compare with the input.
 *       Prints `ok FILE` or `MISMATCH FILE at byte N (line L)` plus the
 *       diagnostics; exits non-zero on any mismatch, uncovered token or
 *       parse error.
 *   cclower --print [--known-types F] [--no-line] [--header] [-o OUT] FILE
 *       Lowered-mode print with `#line` to OUT (or stdout) and the source
 *       map beside it as OUT.map (`emit_line path line col_delta` per
 *       line). The printed text is checked against the map: every emitted
 *       line has an entry, and the host compiler's attribution (from the
 *       `#line` directives) agrees with it.
 *   cclower --is-plain-c [--known-types F] FILE
 *       Exit 0 when the tree has no Concurrent-C node kinds.
 *
 * The parse mode follows the extension: .cch is header mode, .shcc script
 * mode, everything else source mode. Output is byte-identical to
 * out/cc/bin/cclower (the C11 reference). */

#include "lower.h"
#line 20 "cc/lower/cclower.ccs"

#include <errno.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#ifndef CC_HEADER_VEC_CCVec_CCSlice
#define CC_HEADER_VEC_CCVec_CCSlice
/* generic CCVec_CCSlice */

#ifdef CC_HAS_CCSLICE_CCSlice
CC_VEC_DECL_ARENA_TSLICE(CCSlice, CCVec_CCSlice, CCSlice_CCSlice)
#else
CC_VEC_DECL_ARENA(CCSlice, CCVec_CCSlice)
#endif
static inline CCVec_CCSlice cc__CCVec_CCSlice_new(CCArena __a) {
    return CCVec_CCSlice_init(__a, 0);
}
#define CCVec_CCSlice_new(ar) cc__CCVec_CCSlice_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CCSlice (serdes) */
static const cc_type_info __cc_ti_CCVec_CCSlice = { .name = "CCVec_CCSlice", .mangled = "CCVec_CCSlice", .id = 0, .size = (uint32_t)(sizeof(CCVec_CCSlice)), .align = (uint32_t)(_Alignof(CCVec_CCSlice)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CCSlice(void) {
    cc_type_info_register(&__cc_ti_CCVec_CCSlice);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcDiag
#define CC_HEADER_VEC_CCVec_CcDiag
/* generic CCVec_CcDiag */

#ifdef CC_HAS_CCSLICE_CcDiag
CC_VEC_DECL_ARENA_TSLICE(CcDiag, CCVec_CcDiag, CCSlice_CcDiag)
#else
CC_VEC_DECL_ARENA(CcDiag, CCVec_CcDiag)
#endif
static inline CCVec_CcDiag cc__CCVec_CcDiag_new(CCArena __a) {
    return CCVec_CcDiag_init(__a, 0);
}
#define CCVec_CcDiag_new(ar) cc__CCVec_CcDiag_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcDiag (serdes) */
static const cc_type_info __cc_ti_CCVec_CcDiag = { .name = "CCVec_CcDiag", .mangled = "CCVec_CcDiag", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcDiag)), .align = (uint32_t)(_Alignof(CCVec_CcDiag)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcDiag(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcDiag);
}
#endif
#ifndef CC_HEADER_VEC_CCVec_CcSrcMapEntry
#define CC_HEADER_VEC_CCVec_CcSrcMapEntry
/* generic CCVec_CcSrcMapEntry */

#ifdef CC_HAS_CCSLICE_CcSrcMapEntry
CC_VEC_DECL_ARENA_TSLICE(CcSrcMapEntry, CCVec_CcSrcMapEntry, CCSlice_CcSrcMapEntry)
#else
CC_VEC_DECL_ARENA(CcSrcMapEntry, CCVec_CcSrcMapEntry)
#endif
static inline CCVec_CcSrcMapEntry cc__CCVec_CcSrcMapEntry_new(CCArena __a) {
    return CCVec_CcSrcMapEntry_init(__a, 0);
}
#define CCVec_CcSrcMapEntry_new(ar) cc__CCVec_CcSrcMapEntry_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcSrcMapEntry (serdes) */
static const cc_type_info __cc_ti_CCVec_CcSrcMapEntry = { .name = "CCVec_CcSrcMapEntry", .mangled = "CCVec_CcSrcMapEntry", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcSrcMapEntry)), .align = (uint32_t)(_Alignof(CCVec_CcSrcMapEntry)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcSrcMapEntry(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcSrcMapEntry);
}
#endif
#line 27 "cc/lower/cclower.ccs"

#line 27 "cc/lower/cclower.ccs"

#include <ccc/cc_result.h>

#line 1 "<cc:result-specs>"
#ifndef CCResult_CcProduct_CcDiag_DEFINED
#define CCResult_CcProduct_CcDiag_DEFINED 1
#ifdef CC_DECL_RESULT_SPEC
CC_DECL_RESULT_SPEC(CCResult_CcProduct_CcDiag, CcProduct, CcDiag)
#else
#error "Result types need <ccc/cc_result.cch> (or the prelude)"
#endif
#endif
#line 27 "cc/lower/cclower.ccs"

#line 27 "cc/lower/cclower.ccs"
typedef CCVec_CCSlice CcNameList;

/* ---- files ------------------------------------------------------------ */

static CCSlice read_whole_file(const char *path, CCArena a, bool *ok) {
    FILE *fp = fopen(path, "rb");
    long n;
    char *buf;
    *ok = false;
    if (!fp)
#line 36 "cc/lower/cclower.ccs"
        return CC_SLICE_LIT("");
    fseek(fp, 0, SEEK_END);
    n = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    if (n < 0)
#line 40 "cc/lower/cclower.ccs"
        n = 0;
    buf = cc_arena_alloc(a, (size_t)(n) + 1, 1);
    if (n > 0 && fread(buf, 1, (size_t)(n), fp) != (size_t)(n)) {
#line 42 "cc/lower/cclower.ccs"
        fclose(fp);
#line 42 "cc/lower/cclower.ccs"
        return CC_SLICE_LIT("");
#line 42 "cc/lower/cclower.ccs"
    }
    buf[n] = 0;
    fclose(fp);
    *ok = true;
    return cc_slice_from_buffer(buf, (size_t)(n));
}

#line 51 "cc/lower/cclower.ccs"
/* Known type names: whitespace-separated, `#`-prefixed words ignored. */
static void read_known_types(const char *path, CcNameList *known, CCArena a) {
    bool ok;
    CCSlice text = read_whole_file(path, a, &ok);
    size_t i = 0;
    if (!ok) {
#line 56 "cc/lower/cclower.ccs"
        fprintf(stderr, "cclower: cannot read %s: %s\n", path, strerror(errno));
#line 56 "cc/lower/cclower.ccs"
        exit(2);
#line 56 "cc/lower/cclower.ccs"
    }
    while (i < text.len) {
        size_t j;
        while (i < text.len && (text.ptr[i] == ' ' || text.ptr[i] == '\t' || text.ptr[i] == '\r' || text.ptr[i] == '\n'))
#line 59 "cc/lower/cclower.ccs"
            i++;
        if (i >= text.len)
#line 60 "cc/lower/cclower.ccs"
            break;
        j = i;
        while (j < text.len && !(text.ptr[j] == ' ' || text.ptr[j] == '\t' || text.ptr[j] == '\r' || text.ptr[j] == '\n'))
#line 62 "cc/lower/cclower.ccs"
            j++;
        if (text.ptr[i] != '#')
#line 63 "cc/lower/cclower.ccs"
            CCVec_CCSlice_push(known, cc_slice_from_buffer((char *)(text.ptr) + i, j - i));
        i = j;
    }
}

static CcUnitMode mode_for(const char *path) {
    size_t n = strlen(path);
    if (n >= 4 && strcmp(path + n - 4, ".cch") == 0)
#line 70 "cc/lower/cclower.ccs"
        return CC_UNIT_HEADER;
    if (n >= 5 && strcmp(path + n - 5, ".shcc") == 0)
#line 71 "cc/lower/cclower.ccs"
        return CC_UNIT_SCRIPT;
    return CC_UNIT_SOURCE;
}

typedef struct Loaded {
    CCArena arena;
    CcDiags ds;
    CcUnit *unit;
    CCSlice src;
    const char *path;
    CcLowerer lw; /* --lower: the lowerer, for the headers it recorded */
    bool lowered;
    CcIndex *ix; /* --lower: the index, shared with the headers lowered for this unit */
    CcLowerOpts lo;
} Loaded;

/* The text a caret snippet is cut from.
 *
 * A diagnostic names the file the user can open, which is not always the
 * file the tool read: a unit that went through the compile-time stage is
 * lowered from a copy under the cache, and that copy carries a `#line`
 * back to the original. Cutting the snippet from the copy by the user's
 * line number points at the wrong line — the closer the copy is to the
 * original, the more convincingly wrong. So the snippet comes from the
 * named file when it can be read, and from what was lowered otherwise. */
static CCSlice source_of(CCSlice path, void *ctx, bool *physical) {
    Loaded *L = (Loaded *)(ctx);
    CCSlice mine = L->src;
    bool ok = false;
    CCSlice text;
    const char *p;
    *physical = true;
    if (!path.len)
#line 103 "cc/lower/cclower.ccs"
        return mine;
    if (L->path && cc_slice_eq_cstr(&path, L->path))
#line 104 "cc/lower/cclower.ccs"
        return mine;
    {
        CCString s = cc_string_new();
        cc_string_push_slice(&s, path, L->arena);
        p = cc_string_cstr(&s, L->arena);
        if (!p)
#line 109 "cc/lower/cclower.ccs"
            return mine;
        text = read_whole_file(p, L->arena, &ok);
    }
    if (!ok)
#line 112 "cc/lower/cclower.ccs"
        return mine;
    *physical = false;
    return text;
}

/* --root DIR: the repository root quoted `.cch` includes are made relative to;
 * --h-root DIR: where their lowered `.h` files go (`DIR/<rel>.h`). */
static CCSlice g_root;
/* --schema-variants FILE: tagged unions a `@grammar(schema)` declared. The
 * engine emits their C into the source this tool lowers, so the index has
 * the types; what nothing in that text says is that they are tagged
 * unions. One line each: the name, then its arms, void arms marked `=void`. */
static const char *g_schema_variants = NULL;
/* --instantiate FILE: the monomorphs `@comptime { cc_instantiate_*(...) }`
 * asked for. The request is the only use — the body names the instance by
 * its mangled name alone — and blanking took it out of the source before
 * this tool read it. One line each: the family, then its type spellings. */
static const char *g_instantiate = NULL;
/* --factories FILE: the families a `@comptime { cc_generic_register(...) }`
 * bound to a handler. The call is in a block, and blanking took the blocks
 * out of the source before this tool read it, so the binding a factory run
 * needs arrives here instead. One line each: the family, its handler, then
 * `extend` for a handler that appends to a family rather than defining it. */
static const char *g_factories = NULL;
static const char *g_h_root;
/* --modules FILE: the module faces the driver staged (spec 1.7), one per
 * line as the face, a tab, then the stage that holds its module unit: a
 * `#line` to the face, then the face with its members spliced in. A face
 * on disk is not its module; the `.h` the includer reads is extracted
 * from the whole, and it opens with the link marker naming the C the
 * driver compiles once. */
static const char *g_modules = NULL;
static CcNameList g_module_faces;
static CcNameList g_module_stages;

static void read_modules(const char *path, CCArena a) {
    bool ok;
    CCSlice text = read_whole_file(path, a, &ok);
    size_t i = 0;
    if (!ok) {
#line 151 "cc/lower/cclower.ccs"
        fprintf(stderr, "cclower: cannot read %s: %s\n", path, strerror(errno));
#line 151 "cc/lower/cclower.ccs"
        exit(2);
#line 151 "cc/lower/cclower.ccs"
    }
    while (i < text.len) {
        size_t j = i;
        size_t tab = 0;
        while (j < text.len && text.ptr[j] != '\n') {
            if (text.ptr[j] == '\t' && !tab)
#line 156 "cc/lower/cclower.ccs"
                tab = j;
            j++;
        }
        if (tab > i && tab + 1 < j) {
            char *face = cc_arena_alloc(a, tab - i + 1, 1);
            char *stage = cc_arena_alloc(a, j - tab, 1);
            CCSlice fs;
            CCSlice ss;
            memcpy(face, text.ptr + i, tab - i);
            face[tab - i] = 0;
            memcpy(stage, text.ptr + tab + 1, j - tab - 1);
            stage[j - tab - 1] = 0;
            fs = cc_slice_from_buffer(face, tab - i);
            ss = cc_slice_from_buffer(stage, j - tab - 1);
            CCVec_CCSlice_push(&g_module_faces, fs);
            CCVec_CCSlice_push(&g_module_stages, ss);
        }
        i = j < text.len ? j + 1 : j;
    }
}

/* The stage of a module face, NUL-terminated, or NULL for an interface face. */
static const char *module_stage_for(const char *h_c) {
    size_t n = CCVec_CCSlice_len(&g_module_faces);
    size_t i;
    for (i = 0; i < n; i++) {
        CCSlice f = *CCVec_CCSlice_get_ptr(&g_module_faces, i);
        if (cc_slice_eq_cstr(&f, h_c)) {
            CCSlice st = *CCVec_CCSlice_get_ptr(&g_module_stages, i);
            return (const char *)(st.ptr);
        }
    }
    return NULL;
}

/* mkdir -p for the directory part of `path`. */
static bool mkdir_parents(const char *path) {
    char buf[4096];
    size_t n = strlen(path);
    size_t i;
    if (n >= sizeof(buf))
#line 196 "cc/lower/cclower.ccs"
        return false;
    memcpy(buf, path, n + 1);
    for (i = 1; i < n; i++) {
        if (buf[i] != '/')
#line 199 "cc/lower/cclower.ccs"
            continue;
        buf[i] = 0;
        if (mkdir(buf, 0777) != 0 && errno != EEXIST)
#line 201 "cc/lower/cclower.ccs"
            return false;
        buf[i] = '/';
    }
    return true;
}

static bool load(Loaded *L, const char *path, CcNameList known, CCArena a) {
    CcParseOpts opts;
    bool ok;
    L->arena = a;
    L->ds = CcDiags_new(a);
    L->path = path;
    L->src = read_whole_file(path, a, &ok);
    if (!ok) {
        fprintf(stderr, "cclower: cannot read %s: %s\n", path, strerror(errno));
        return false;
    }
    opts.mode = mode_for(path);
    opts.known_types = known;
    L->unit = cc_parse_unit(cc_slice_from_buffer((char *)(path), strlen(path)), L->src, opts, &L->ds, a);
    return true;
}

static void print_diags(Loaded *L) {
    CcDiags *ds = &L->ds;
    CCVec_CcDiag *items = &ds->items;
    if (CCVec_CcDiag_len(items))
#line 227 "cc/lower/cclower.ccs"
        CcDiags_print(ds, stderr, source_of, L);
}

/* Byte offset of physical (line, col) in `src`. */
static size_t byte_of(CCSlice src, uint32_t line, uint32_t col) {
    size_t i = 0;
    uint32_t ln = 1;
    while (ln < line && i < src.len) {
        if (src.ptr[i] == '\n')
#line 235 "cc/lower/cclower.ccs"
            ln++;
        i++;
    }
    if (col)
#line 238 "cc/lower/cclower.ccs"
        i += col - 1;
    if (i > src.len)
#line 239 "cc/lower/cclower.ccs"
        i = src.len;
    return i;
}

/* ---- --identity ---------------------------------------------------------- */

static int run_identity(const char *path, CcNameList known) {
    int __cc_retval;
#line 246 "cc/lower/cclower.ccs"
    int __cc_defer_on_1 = 0;
#line 246 "cc/lower/cclower.ccs"
    CCArena a = cc_arena_heap(megabytes(256));
#line 246 "cc/lower/cclower.ccs"
    __cc_defer_on_1 = 1;
    Loaded L;
    CcPrintOpts po;
    int rc = 0;
    uint32_t n_parse_errors;
    if (!load(&L, path, known, a)) {
#line 251 "cc/lower/cclower.ccs"
        __cc_retval = 1;
#line 251 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 251 "cc/lower/cclower.ccs"
    }
    n_parse_errors = L.ds.n_errors;
    po.identity = true;
    po.line_directives = false;
    po.path = cc_slice_empty();
    po.header_mode = false;
    po.header_owned = false;
    CcProduct prod;
#line 258 "cc/lower/cclower.ccs"
    {
#line 258 "cc/lower/cclower.ccs"
        __typeof__(cc_print_unit(L.unit, NULL, po, &L.ds, a)) __r = cc_print_unit(L.unit, NULL, po, &L.ds, a);
#line 258 "cc/lower/cclower.ccs"
        if (!__r.ok) {
#line 258 "cc/lower/cclower.ccs"
            CcDiag e = __r.u.error;
#line 258 "cc/lower/cclower.ccs"
            {
                uint32_t pline = e.phys_line ? e.phys_line : e.at.line;
                size_t at = byte_of(L.src, pline, e.at.col);
                printf("MISMATCH %s at byte %zu (line %u)\n", path, at, (unsigned int)(pline));
                print_diags(&L);
                {
#line 263 "cc/lower/cclower.ccs"
                    __cc_retval = 1;
#line 263 "cc/lower/cclower.ccs"
                    goto __cc_cleanup;
#line 263 "cc/lower/cclower.ccs"
                }
            }
#line 264 "cc/lower/cclower.ccs"
        }
#line 258 "cc/lower/cclower.ccs"
        prod = __r.u.value;
#line 258 "cc/lower/cclower.ccs"
    }
#line 265 "cc/lower/cclower.ccs"
    (void)(prod);
    if (L.ds.n_errors) {
        printf("%s %s (%u parse error(s), %u printer error(s))\n", n_parse_errors ? "PARSE-ERROR" : "UNCOVERED", path, (unsigned int)(n_parse_errors), (unsigned int)(L.ds.n_errors - n_parse_errors));
#line 270 "cc/lower/cclower.ccs"
        rc = 1;
    } else {
        printf("ok %s\n", path);
    }
    print_diags(&L);
    {
#line 275 "cc/lower/cclower.ccs"
        __cc_retval = rc;
#line 275 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 275 "cc/lower/cclower.ccs"
    }
#line 275 "cc/lower/cclower.ccs"
    __cc_cleanup:;
#line 275 "cc/lower/cclower.ccs"
    {
#line 246 "cc/lower/cclower.ccs"
        if (__cc_defer_on_1) {
#line 246 "cc/lower/cclower.ccs"
            {
#line 246 "cc/lower/cclower.ccs"
                cc_arena_destroy(&a);
#line 246 "cc/lower/cclower.ccs"
            }
#line 246 "cc/lower/cclower.ccs"
        }
#line 275 "cc/lower/cclower.ccs"
        return __cc_retval;
#line 275 "cc/lower/cclower.ccs"
    }
}

/* ---- --is-plain-c -------------------------------------------------------- */

typedef struct Plain {
    CCSlice first_what;
    uint32_t first_tok;
} Plain;

static void plain_note(Plain *pl, CCSlice what, uint32_t tok) {
    if (pl->first_what.len)
#line 286 "cc/lower/cclower.ccs"
        return;
    pl->first_what = what;
    pl->first_tok = tok;
}

/* A statement at file scope (.shcc) is a Concurrent-C form here, though
 * the printer prints it as C. */
static bool decl_is_top_stmt(const CcDecl *d) {
    return d->k.kind == CcDeclK_stmt;
}

static bool plain_decl(CcDecl *d, void *env) {
    if (decl_is_cc(d) || decl_is_top_stmt(d))
#line 298 "cc/lower/cclower.ccs"
        plain_note((Plain *)(env), CcDecl_kind_name(d), d->span.first);
    return true;
}
static bool plain_stmt(CcStmt *s, void *env) {
    if (stmt_is_cc(s))
#line 302 "cc/lower/cclower.ccs"
        plain_note((Plain *)(env), CcStmt_kind_name(s), s->span.first);
    return true;
}
static bool plain_expr(CcExpr *e, void *env) {
    if (expr_is_cc(e))
#line 306 "cc/lower/cclower.ccs"
        plain_note((Plain *)(env), CcExpr_kind_name(e), e->span.first);
    return true;
}

/* A function type's parameters (a view of the list header), else empty. */
static CcParamList type_func_params(CcType *t) {
    CcParamList empty;
    memset(&empty, 0, sizeof(empty));
    switch ((t->k).kind) {
        case CcTypeK_func: {
#line 315 "cc/lower/cclower.ccs"
            CcFuncType fn = (t->k).u.func;
#line 315 "cc/lower/cclower.ccs"
            return fn.params;
#line 315 "cc/lower/cclower.ccs"
        }
        default:
#line 316 "cc/lower/cclower.ccs"
            return empty;
    }
}

static bool plain_type(CcType *t, void *env) {
    Plain *pl = (Plain *)(env);
    CcParamList params;
    size_t n;
    size_t i;
    if (type_is_cc(t))
#line 325 "cc/lower/cclower.ccs"
        plain_note(pl, CcType_kind_name(t), t->span.first);
    params = type_func_params(t);
    n = CCVec_CcParam_len(&params);
    for (i = 0; i < n; i++) {
        const CcParam *pa = CCVec_CcParam_get_ptr(&params, i);
        if (pa->default_value)
#line 330 "cc/lower/cclower.ccs"
            plain_note(pl, CC_SLICE_LIT("parameter default"), pa->span.first);
    }
    return true;
}

static int run_is_plain_c(const char *path, CcNameList known) {
    int __cc_retval;
#line 336 "cc/lower/cclower.ccs"
    int __cc_defer_on_1 = 0;
#line 336 "cc/lower/cclower.ccs"
    CCArena a = cc_arena_heap(megabytes(256));
#line 336 "cc/lower/cclower.ccs"
    __cc_defer_on_1 = 1;
    Loaded L;
    Plain pl;
    CcVisitor v;
    int rc;
    if (!load(&L, path, known, a)) {
#line 341 "cc/lower/cclower.ccs"
        __cc_retval = 2;
#line 341 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 341 "cc/lower/cclower.ccs"
    }
    pl.first_what = cc_slice_empty();
    pl.first_tok = 0;
    v.type = plain_type;
    v.expr = plain_expr;
    v.stmt = plain_stmt;
    v.decl = plain_decl;
    v.env = &pl;
    CcUnit_walk(L.unit, v);
    if (L.unit->has_shebang)
#line 350 "cc/lower/cclower.ccs"
        plain_note(&pl, CC_SLICE_LIT("#!ccc"), 0);
    if (L.ds.n_errors) {
        printf("parse-error %s\n", path);
        print_diags(&L);
        rc = 2;
    } else if (pl.first_what.len) {
        const CcTape *tape = &L.unit->tape;
        CcLoc loc = CcTape_loc(tape, pl.first_tok);
        printf("cc %s (%.*s at line %u)\n", path, (int)(pl.first_what.len), pl.first_what.ptr, (unsigned int)(loc.line));
        rc = 1;
    } else {
        printf("plain %s\n", path);
        rc = 0;
    }
    {
#line 364 "cc/lower/cclower.ccs"
        __cc_retval = rc;
#line 364 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 364 "cc/lower/cclower.ccs"
    }
#line 364 "cc/lower/cclower.ccs"
    __cc_cleanup:;
#line 364 "cc/lower/cclower.ccs"
    {
#line 336 "cc/lower/cclower.ccs"
        if (__cc_defer_on_1) {
#line 336 "cc/lower/cclower.ccs"
            {
#line 336 "cc/lower/cclower.ccs"
                cc_arena_destroy(&a);
#line 336 "cc/lower/cclower.ccs"
            }
#line 336 "cc/lower/cclower.ccs"
        }
#line 364 "cc/lower/cclower.ccs"
        return __cc_retval;
#line 364 "cc/lower/cclower.ccs"
    }
}

/* ---- --print --------------------------------------------------------------- */

/* Parse `#line N "path"` / `# N "path"` at the start of a line. Returns
 * true and fills line/path (path is an arena copy, or empty when absent). */
static bool parse_line_directive(const char *s, size_t n, unsigned int *line, CCSlice *path, bool *has_path, CCArena a) {
    size_t i = 0;
#line 372 "cc/lower/cclower.ccs"
    size_t j;
    unsigned int v = 0;
    while (i < n && (s[i] == ' ' || s[i] == '\t'))
#line 374 "cc/lower/cclower.ccs"
        i++;
    if (i >= n || s[i] != '#')
#line 375 "cc/lower/cclower.ccs"
        return false;
    i++;
    while (i < n && (s[i] == ' ' || s[i] == '\t'))
#line 377 "cc/lower/cclower.ccs"
        i++;
    if (i + 4 <= n && memcmp(s + i, "line", 4) == 0) {
        i += 4;
        if (i >= n || !(s[i] == ' ' || s[i] == '\t'))
#line 380 "cc/lower/cclower.ccs"
            return false;
        while (i < n && (s[i] == ' ' || s[i] == '\t'))
#line 381 "cc/lower/cclower.ccs"
            i++;
    }
    if (i >= n || s[i] < '0' || s[i] > '9')
#line 383 "cc/lower/cclower.ccs"
        return false;
    while (i < n && s[i] >= '0' && s[i] <= '9') {
#line 384 "cc/lower/cclower.ccs"
        v = v * 10 + (unsigned int)(s[i] - '0');
#line 384 "cc/lower/cclower.ccs"
        i++;
#line 384 "cc/lower/cclower.ccs"
    }
    while (i < n && (s[i] == ' ' || s[i] == '\t'))
#line 385 "cc/lower/cclower.ccs"
        i++;
    *line = v;
    *has_path = false;
    if (i < n && s[i] == '"') {
        char *buf = cc_arena_alloc(a, n + 1, 1);
        size_t k = 0;
        for (j = i + 1; j < n && s[j] != '"'; j++) {
            if (s[j] == '\\' && j + 1 < n)
#line 392 "cc/lower/cclower.ccs"
                j++;
            buf[k++] = s[j];
        }
        buf[k] = 0;
        *path = cc_slice_from_buffer(buf, k);
        *has_path = true;
    }
    return true;
}

/* Check the printed text against its map: one entry per line and, when
 * directives are on, the host's attribution equals the map's. Returns the
 * number of problems. */
static int verify_map(CCSlice text, CcSrcMap *map, bool directives, FILE *err, CCArena a) {
    CCVec_CcSrcMapEntry *ents = &map->entries;
    size_t n_ents = CCVec_CcSrcMapEntry_len(ents);
    size_t i = 0;
#line 408 "cc/lower/cclower.ccs"
    size_t lineno = 1;
#line 408 "cc/lower/cclower.ccs"
    size_t n_lines = 0;
    int problems = 0;
    CCSlice host_path = cc_slice_empty();
    bool host_has_path = false;
    unsigned int host_line = 0;
    const char *s = text.ptr;
    size_t len = text.len;
    while (i < len) {
        size_t j = i;
        const CcSrcMapEntry *e;
        unsigned int dl;
        CCSlice dp;
        bool has_dp;
        while (j < len && s[j] != '\n')
#line 421 "cc/lower/cclower.ccs"
            j++;
        n_lines++;
        if (lineno > n_ents || CCVec_CcSrcMapEntry_get_ptr(ents, lineno - 1)->emit_line != lineno) {
            fprintf(err, "map: emitted line %zu has no source map entry\n", lineno);
            problems++;
            e = NULL;
        } else {
            e = CCVec_CcSrcMapEntry_get_ptr(ents, lineno - 1);
        }
        if (parse_line_directive(s + i, j - i, &dl, &dp, &has_dp, a)) {
            host_line = dl;
            if (has_dp) {
#line 432 "cc/lower/cclower.ccs"
                host_path = dp;
#line 432 "cc/lower/cclower.ccs"
                host_has_path = true;
#line 432 "cc/lower/cclower.ccs"
            }
        } else {
            if (directives && host_line && e) {
                CCSlice ep = e->path;
                if (host_line != e->line || !host_has_path || !cc_slice_eq(&host_path, ep)) {
                    fprintf(err, "map: emitted line %zu is attributed to %.*s:%u by the host but to %.*s:%u by the map\n", lineno, host_has_path ? (int)(host_path.len) : 1, host_has_path ? host_path.ptr : "?", host_line, ep.len ? (int)(ep.len) : 1, ep.len ? ep.ptr : "?", (unsigned int)(e->line));
#line 440 "cc/lower/cclower.ccs"
                    problems++;
                }
            }
            if (host_line)
#line 443 "cc/lower/cclower.ccs"
                host_line++;
        }
        lineno++;
        i = j < len ? j + 1 : j;
    }
    if (n_ents != n_lines) {
        fprintf(err, "map: %u entries for %zu emitted lines\n", (unsigned int)(n_ents), n_lines);
        problems++;
    }
    return problems;
}

static bool write_product(const char *out_path, CCSlice text, CcSrcMap *map, CCArena a) {
    FILE *fp = fopen(out_path, "wb");
    CCVec_CcSrcMapEntry *ents = &map->entries;
    size_t n = CCVec_CcSrcMapEntry_len(ents);
    size_t k;
    bool ok = true;
    const char *map_path;
    if (!fp) {
        fprintf(stderr, "cclower: cannot write %s: %s\n", out_path, strerror(errno));
        ok = false;
    } else {
        fwrite(text.ptr, 1, text.len, fp);
        fclose(fp);
    }
    {
        CCString mp = cc_string_new();
#line 470 "cc/lower/cclower.ccs"
        cc__string_slot_push(&mp, (out_path), a);
#line 470 "cc/lower/cclower.ccs"
        cc_string_push_buffer(&mp, ".map", 4, a);
        map_path = cc_string_cstr(&mp, a);
    }
    fp = fopen(map_path, "wb");
    if (!fp) {
        fprintf(stderr, "cclower: cannot write %s: %s\n", map_path, strerror(errno));
        return false;
    }
    for (k = 0; k < n; k++) {
        const CcSrcMapEntry *e = CCVec_CcSrcMapEntry_get_ptr(ents, k);
        fprintf(fp, "%u ", (unsigned int)(e->emit_line));
        if (e->path.len)
#line 481 "cc/lower/cclower.ccs"
            fwrite(e->path.ptr, 1, e->path.len, fp);
#line 481 "cc/lower/cclower.ccs"
        else
            fputs("?", fp);
        fprintf(fp, " %u %d\n", (unsigned int)(e->line), (int)(e->col_delta));
    }
    fclose(fp);
    return ok;
}

/* --lower: parse with the index's typedef names, lower, print. */
/* `-I DIR` search path for the index (default: cc/include); lifetime: the tool arena */
static CcNameList g_include_dirs;

/* --quote-dir DIR: the directory quoted `.cch` includes resolve against,
 * when the unit being lowered is a stage the driver materialized from a
 * source that lives somewhere else. */
static const char *g_quote_dir = NULL;

static bool load_lowered(Loaded *L, const char *path, CcNameList known, CCArena a) {
    CcParseOpts opts;
    bool ok;
    CcIndex *ix;
    CcLowerOpts lo;
    CcLowerer lw;
    CCSlice pathsl = cc_slice_from_buffer((char *)(path), strlen(path));
    /* every field, not just the ones this function names: a `CcLowerOpts`
     * filled one field at a time hands the lowerer garbage for any field
     * added later, and reads of it are wild rather than merely wrong */
    memset(&lo, 0, sizeof lo);
    L->arena = a;
    L->ds = CcDiags_new(a);
    L->path = path;
    L->src = read_whole_file(path, a, &ok);
    if (!ok) {
        fprintf(stderr, "cclower: cannot read %s: %s\n", path, strerror(errno));
        return false;
    }
    {
        /* quoted includes resolve against the unit's own directory — or,
         * when the driver handed us a materialized stage of a unit that
         * lives elsewhere, against the directory the user wrote it in */
        size_t slash = pathsl.len;
        CCSlice qdir = cc_slice_empty();
        while (slash > 0 && pathsl.ptr[slash - 1] != '/')
#line 523 "cc/lower/cclower.ccs"
            slash--;
        if (slash)
#line 524 "cc/lower/cclower.ccs"
            qdir = cc_slice_from_buffer((char *)(pathsl.ptr), slash - 1);
        if (g_quote_dir)
#line 525 "cc/lower/cclower.ccs"
            qdir = cc_slice_from_buffer((char *)(g_quote_dir), strlen(g_quote_dir));
        ix = cc_index_new(g_include_dirs, qdir, &L->ds, a);
    }
    opts.mode = mode_for(path);
    opts.known_types = known;
    {
        CcDiags scratch = CcDiags_new(a);
        CcTape tape = cc_lex(pathsl, L->src, &scratch, a);
        CcIndex_preload_includes(ix, &tape, opts);
    }
    {
        CcNameList all = CCVec_CCSlice_new(a);
        CcNameList from_ix = CcIndex_known_types(ix);
        size_t i;
        size_t n = CCVec_CCSlice_len(&known);
        size_t m = CCVec_CCSlice_len(&from_ix);
        for (i = 0; i < n; i++) {
            CCSlice nm = *CCVec_CCSlice_get_ptr(&known, i);
            CCVec_CCSlice_push(&all, nm);
        }
        for (i = 0; i < m; i++) {
            CCSlice nm = *CCVec_CCSlice_get_ptr(&from_ix, i);
            CCVec_CCSlice_push(&all, nm);
        }
        opts.known_types = all;
    }
    L->unit = cc_parse_unit(pathsl, L->src, opts, &L->ds, a);
    CcIndex_add_unit(ix, L->unit, opts.mode == CC_UNIT_HEADER);
    if (CcDiags_has_errors(&L->ds))
#line 553 "cc/lower/cclower.ccs"
        return true; /* parse errors: print nothing but the diagnostics */
    lo.line_directives = true;
    if (g_schema_variants) {
        bool sv_ok = false;
        CCSlice sv = read_whole_file(g_schema_variants, a, &sv_ok);
        if (!sv_ok) {
#line 558 "cc/lower/cclower.ccs"
            fprintf(stderr, "cclower: cannot read %s: %s\n", g_schema_variants, strerror(errno));
#line 558 "cc/lower/cclower.ccs"
            exit(2);
#line 558 "cc/lower/cclower.ccs"
        }
        lo.schema_variants = sv;
    }
    if (g_instantiate) {
        bool iv_ok = false;
        CCSlice iv = read_whole_file(g_instantiate, a, &iv_ok);
        if (!iv_ok) {
#line 564 "cc/lower/cclower.ccs"
            fprintf(stderr, "cclower: cannot read %s: %s\n", g_instantiate, strerror(errno));
#line 564 "cc/lower/cclower.ccs"
            exit(2);
#line 564 "cc/lower/cclower.ccs"
        }
        lo.instantiate = iv;
    }
    if (g_factories) {
        bool fv_ok = false;
        CCSlice fv = read_whole_file(g_factories, a, &fv_ok);
        if (!fv_ok) {
#line 570 "cc/lower/cclower.ccs"
            fprintf(stderr, "cclower: cannot read %s: %s\n", g_factories, strerror(errno));
#line 570 "cc/lower/cclower.ccs"
            exit(2);
#line 570 "cc/lower/cclower.ccs"
        }
        lo.factories = fv;
    }
    {
        const char *strict = getenv("CC_STRICT_RESULT_UNWRAP");
        lo.strict_unhandled = !(strict && strcmp(strict, "0") == 0);
    }
    lo.repo_root = g_root;
    lw = cc_lowerer_new(L->unit, ix, lo, &L->ds);
    CcLowerer_lower_unit(&lw);
    L->lw = lw;
    L->lowered = true;
    L->ix = ix;
    L->lo = lo;
    return true;
}

static void note_headers(Loaded *L, CcNameList *more, CCArena keep);

/* A local header the unit includes, lowered in header mode with the unit's
 * own index (its registrations and known types are the header's context,
 * as they are when the host compiles the include) to `<h-root>/<rel>.h`.
 * Headers it includes in turn join `todo`. */
static int lower_header_with(Loaded *owner, CCSlice hpath, CcNameList known, bool line_directives, CcNameList *todo, CCArena keep) {
    CCArena a = owner->arena;
    CcIndex *ix = owner->ix;
    CcParseOpts opts;
    CcPrintOpts po;
    CcDiags ds = CcDiags_new(a);
    CcUnit *u;
    CcLowerer lw;
    Loaded H;
    bool ok;
    CCSlice rel;
    CCString out;
    const char *h_c = (const char *)(hpath.ptr); /* NUL-terminated by note_headers */
    const char *stage = module_stage_for(h_c);
    const char *read_from = stage ? stage : h_c;
    CCSlice text;
    int rc = 0;
    memset(&H, 0, sizeof(H));
    H.arena = a;
    H.path = h_c;
    H.src = read_whole_file(read_from, a, &ok);
    if (!ok) {
#line 614 "cc/lower/cclower.ccs"
        fprintf(stderr, "cclower: cannot read %s: %s\n", read_from, strerror(errno));
#line 614 "cc/lower/cclower.ccs"
        return 2;
#line 614 "cc/lower/cclower.ccs"
    }
    opts.mode = CC_UNIT_HEADER;
    {
        CcNameList all = CCVec_CCSlice_new(a);
        CcNameList from_ix = CcIndex_known_types(ix);
        size_t i;
        size_t n = CCVec_CCSlice_len(&known);
        size_t m = CCVec_CCSlice_len(&from_ix);
        for (i = 0; i < n; i++) {
#line 622 "cc/lower/cclower.ccs"
            CCSlice nm = *CCVec_CCSlice_get_ptr(&known, i);
#line 622 "cc/lower/cclower.ccs"
            CCVec_CCSlice_push(&all, nm);
#line 622 "cc/lower/cclower.ccs"
        }
        for (i = 0; i < m; i++) {
#line 623 "cc/lower/cclower.ccs"
            CCSlice nm = *CCVec_CCSlice_get_ptr(&from_ix, i);
#line 623 "cc/lower/cclower.ccs"
            CCVec_CCSlice_push(&all, nm);
#line 623 "cc/lower/cclower.ccs"
        }
        opts.known_types = all;
    }
    u = cc_parse_unit(hpath, H.src, opts, &ds, a);
    H.unit = u;
    H.ds = ds;
    if (CcDiags_has_errors(&ds)) {
#line 629 "cc/lower/cclower.ccs"
        print_diags(&H);
#line 629 "cc/lower/cclower.ccs"
        return 1;
#line 629 "cc/lower/cclower.ccs"
    }
    lw = cc_lowerer_new(u, ix, owner->lo, &H.ds);
    lw.header_mode = true;
    CcLowerer_lower_unit(&lw);
    H.lw = lw;
    H.lowered = true;
    note_headers(&H, todo, keep);
    if (CcDiags_has_errors(&H.ds)) {
#line 636 "cc/lower/cclower.ccs"
        print_diags(&H);
#line 636 "cc/lower/cclower.ccs"
        return 1;
#line 636 "cc/lower/cclower.ccs"
    }
    rel = cc_slice_from_buffer((char *)(hpath.ptr) + g_root.len + 1, hpath.len - g_root.len - 1 - 4);
    out = ({
#line 638 "cc/lower/cclower.ccs"
        CCString __cc_str_0 = cc_string_new();
#line 638 "cc/lower/cclower.ccs"
        cc__string_slot_push(&__cc_str_0, (g_h_root), a);
#line 638 "cc/lower/cclower.ccs"
        cc_string_push_buffer(&__cc_str_0, "/", 1, a);
#line 638 "cc/lower/cclower.ccs"
        cc__string_slot_push(&__cc_str_0, (rel), a);
#line 638 "cc/lower/cclower.ccs"
        cc_string_push_buffer(&__cc_str_0, ".h", 2, a);
#line 638 "cc/lower/cclower.ccs"
        __cc_str_0;
#line 638 "cc/lower/cclower.ccs"
    });
    {
        const char *out_c = cc_string_cstr(&out, a);
        if (!mkdir_parents(out_c)) {
#line 641 "cc/lower/cclower.ccs"
            fprintf(stderr, "cclower: cannot create the directory of %s\n", out_c);
#line 641 "cc/lower/cclower.ccs"
            return 2;
#line 641 "cc/lower/cclower.ccs"
        }
        po.identity = false;
        po.line_directives = line_directives;
        po.header_mode = true;
        po.header_owned = stage != NULL;
        po.path = hpath;
        CcProduct prod;
#line 647 "cc/lower/cclower.ccs"
        {
#line 647 "cc/lower/cclower.ccs"
            __typeof__(cc_print_unit(u, NULL, po, &H.ds, a)) __r = cc_print_unit(u, NULL, po, &H.ds, a);
#line 647 "cc/lower/cclower.ccs"
            if (!__r.ok) {
#line 647 "cc/lower/cclower.ccs"
                CcDiag e = __r.u.error;
#line 647 "cc/lower/cclower.ccs"
                {
                    fprintf(stderr, "cclower: %s: %.*s\n", h_c, (int)(e.msg.len), e.msg.ptr);
                    return 2;
                }
#line 650 "cc/lower/cclower.ccs"
            }
#line 647 "cc/lower/cclower.ccs"
            prod = __r.u.value;
#line 647 "cc/lower/cclower.ccs"
        }
#line 651 "cc/lower/cclower.ccs"
        text = cc_string_as_slice(&prod.text);
        if (stage) {
            /* the marker is line one; every mapped line moves down by it */
            CCString marked = cc_string_new();
            CCVec_CcSrcMapEntry *ents = &prod.map.entries;
            size_t ne = CCVec_CcSrcMapEntry_len(ents);
            size_t k;
            cc_string_push_cstr(&marked, "/" "*cc:link ", a);
            cc_string_push_slice(&marked, rel, a);
            cc_string_push_cstr(&marked, "_cch.c*" "/\n", a);
            cc_string_push_slice(&marked, text, a);
            text = cc_string_as_slice(&marked);
            for (k = 0; k < ne; k++) {
                CcSrcMapEntry *e = CCVec_CcSrcMapEntry_get_ptr(ents, k);
                e->emit_line += 1;
            }
        }
        if (!write_product(out_c, text, &prod.map, a))
#line 668 "cc/lower/cclower.ccs"
            rc = 2;
        print_diags(&H);
        if (H.ds.n_errors)
#line 670 "cc/lower/cclower.ccs"
            rc = 1;
    }
    return rc;
}

/* Every local header the unit recorded, and those they record, each once. */
static int lower_headers_of(Loaded *owner, CcNameList known, bool line_directives, CCArena keep) {
    CcNameList todo = CCVec_CCSlice_new(keep);
    CcNameList seen = CCVec_CCSlice_new(keep);
    int rc = 0;
    note_headers(owner, &todo, keep);
    for (;;) {
        size_t nt = CCVec_CCSlice_len(&todo);
        CCSlice h;
        size_t k;
        size_t ns = CCVec_CCSlice_len(&seen);
        bool dup = false;
        if (!nt)
#line 687 "cc/lower/cclower.ccs"
            break;
        h = *CCVec_CCSlice_get_ptr(&todo, nt - 1);
        CCVec_CCSlice_truncate(&todo, nt - 1);
        for (k = 0; k < ns; k++) {
            CCSlice sk = *CCVec_CCSlice_get_ptr(&seen, k);
            if (cc_slice_eq(&sk, h))
#line 692 "cc/lower/cclower.ccs"
                dup = true;
        }
        if (dup)
#line 694 "cc/lower/cclower.ccs"
            continue;
        CCVec_CCSlice_push(&seen, h);
        if (!(h.len > g_root.len && memcmp(h.ptr, g_root.ptr, g_root.len) == 0 && h.ptr[g_root.len] == '/'))
#line 696 "cc/lower/cclower.ccs"
            continue;
        rc |= lower_header_with(owner, h, known, line_directives, &todo, keep);
    }
    return rc;
}

/* Copies of the headers the lowering recorded, in the caller's arena. */
static void note_headers(Loaded *L, CcNameList *more, CCArena keep) {
    CCVec_CCSlice *hs = &L->lw.headers;
    size_t n = CCVec_CCSlice_len(hs);
    size_t i;
    if (!L->lowered || !more)
#line 707 "cc/lower/cclower.ccs"
        return;
    for (i = 0; i < n; i++) {
        CCSlice h = *CCVec_CCSlice_get_ptr(hs, i);
        char *copy = cc_arena_alloc(keep, h.len + 1, 1);
        CCSlice kept;
        memcpy(copy, h.ptr, h.len);
        copy[h.len] = 0;
        kept = cc_slice_from_buffer(copy, h.len);
        CCVec_CCSlice_push(more, kept);
    }
}

static int run_print(const char *path, CcNameList known, const char *out_path, bool line_directives, bool header_mode, bool lower, CcNameList *more_headers, CCArena keep) {
#line 721 "cc/lower/cclower.ccs"
    int __cc_retval;
#line 721 "cc/lower/cclower.ccs"
    int __cc_defer_on_1 = 0;
#line 721 "cc/lower/cclower.ccs"
    CCArena a = cc_arena_heap(megabytes(256));
#line 721 "cc/lower/cclower.ccs"
    __cc_defer_on_1 = 1;
    Loaded L;
    CcPrintOpts po;
    int rc = 0;
    int problems;
    uint32_t n_parse_errors;
    CCSlice text;
    memset(&L, 0, sizeof(L));
    if (lower) {
#line 729 "cc/lower/cclower.ccs"
        if (!load_lowered(&L, path, known, a)) {
#line 729 "cc/lower/cclower.ccs"
            __cc_retval = 2;
#line 729 "cc/lower/cclower.ccs"
            goto __cc_cleanup;
#line 729 "cc/lower/cclower.ccs"
        }
#line 729 "cc/lower/cclower.ccs"
    } else if (!load(&L, path, known, a)) {
        __cc_retval = 2;
#line 730 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 730 "cc/lower/cclower.ccs"
    }
    if (lower && CcDiags_has_errors(&L.ds)) {
#line 731 "cc/lower/cclower.ccs"
        print_diags(&L);
#line 731 "cc/lower/cclower.ccs"
        {
#line 731 "cc/lower/cclower.ccs"
            __cc_retval = 1;
#line 731 "cc/lower/cclower.ccs"
            goto __cc_cleanup;
#line 731 "cc/lower/cclower.ccs"
        }
#line 731 "cc/lower/cclower.ccs"
    }
    (void)(more_headers);
    if (lower && g_h_root && g_root.len)
#line 733 "cc/lower/cclower.ccs"
        rc |= lower_headers_of(&L, known, line_directives, keep);
    n_parse_errors = L.ds.n_errors;
    po.identity = false;
    po.line_directives = line_directives;
    po.header_mode = header_mode;
    po.header_owned = false;
    po.path = cc_slice_from_buffer((char *)(path), strlen(path));
    CcProduct prod;
#line 740 "cc/lower/cclower.ccs"
    {
#line 740 "cc/lower/cclower.ccs"
        __typeof__(cc_print_unit(L.unit, NULL, po, &L.ds, a)) __r = cc_print_unit(L.unit, NULL, po, &L.ds, a);
#line 740 "cc/lower/cclower.ccs"
        if (!__r.ok) {
#line 740 "cc/lower/cclower.ccs"
            CcDiag e = __r.u.error;
#line 740 "cc/lower/cclower.ccs"
            {
                fprintf(stderr, "cclower: %s: %.*s\n", path, (int)(e.msg.len), e.msg.ptr);
                {
#line 742 "cc/lower/cclower.ccs"
                    __cc_retval = 2;
#line 742 "cc/lower/cclower.ccs"
                    goto __cc_cleanup;
#line 742 "cc/lower/cclower.ccs"
                }
            }
#line 743 "cc/lower/cclower.ccs"
        }
#line 740 "cc/lower/cclower.ccs"
        prod = __r.u.value;
#line 740 "cc/lower/cclower.ccs"
    }
#line 744 "cc/lower/cclower.ccs"
    text = cc_string_as_slice(&prod.text);
    if (out_path) {
        if (!write_product(out_path, text, &prod.map, a))
#line 746 "cc/lower/cclower.ccs"
            rc = 2;
    } else {
        fwrite(text.ptr, 1, text.len, stdout);
    }
    problems = verify_map(text, &prod.map, line_directives, stderr, a);
    print_diags(&L);
    if (L.ds.n_errors) {
        fprintf(stderr, "cclower: %s: %u parse error(s), %u printer error(s)\n", path, (unsigned int)(n_parse_errors), (unsigned int)(L.ds.n_errors - n_parse_errors));
#line 755 "cc/lower/cclower.ccs"
        rc = 1;
    }
    if (problems) {
        fprintf(stderr, "cclower: %s: %d source map problem(s)\n", path, problems);
        rc = 1;
    }
    {
#line 761 "cc/lower/cclower.ccs"
        __cc_retval = rc;
#line 761 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 761 "cc/lower/cclower.ccs"
    }
#line 761 "cc/lower/cclower.ccs"
    __cc_cleanup:;
#line 761 "cc/lower/cclower.ccs"
    {
#line 721 "cc/lower/cclower.ccs"
        if (__cc_defer_on_1) {
#line 721 "cc/lower/cclower.ccs"
            {
#line 721 "cc/lower/cclower.ccs"
                cc_arena_destroy(&a);
#line 721 "cc/lower/cclower.ccs"
            }
#line 721 "cc/lower/cclower.ccs"
        }
#line 761 "cc/lower/cclower.ccs"
        return __cc_retval;
#line 761 "cc/lower/cclower.ccs"
    }
}

/* ---- main ---------------------------------------------------------------------- */

static void usage(void) {
    fprintf(stderr, "usage: cclower --identity [--known-types F] FILE...\n" "       cclower --print [--known-types F] [--no-line] [--header] [-o OUT] FILE\n" "       cclower --lower [--known-types F] [-I DIR]... [--root DIR --h-root DIR] [--modules F] [-o OUT] FILE\n" "       cclower --is-plain-c [--known-types F] FILE\n");
#line 772 "cc/lower/cclower.ccs"
    exit(2);
}

enum {
#line 775 "cc/lower/cclower.ccs"
    M_NONE,
#line 775 "cc/lower/cclower.ccs"
    M_IDENTITY,
#line 775 "cc/lower/cclower.ccs"
    M_PRINT,
#line 775 "cc/lower/cclower.ccs"
    M_PLAIN
#line 775 "cc/lower/cclower.ccs"
};

int main(int argc, char **argv) {
    int __cc_retval;
#line 778 "cc/lower/cclower.ccs"
    int __cc_defer_on_1 = 0;
#line 778 "cc/lower/cclower.ccs"
    CCArena tool = cc_arena_heap(megabytes(8));
#line 778 "cc/lower/cclower.ccs"
    __cc_defer_on_1 = 1;
    CcNameList known = CCVec_CCSlice_new(tool);
    int mode = M_NONE;
    const char *known_path = NULL;
    const char *out_path = NULL;
    bool line_directives = true;
    bool header_mode = false;
    bool lower = false;
    int i;
    int rc = 0;
    int n_files = 0;
    CcNameList todo = CCVec_CCSlice_new(tool);
    bool custom_dirs = false;
    g_include_dirs = CCVec_CCSlice_new(tool);
    CCVec_CCSlice_push(&g_include_dirs, CC_SLICE_LIT("cc/include"));
    g_module_faces = CCVec_CCSlice_new(tool);
    g_module_stages = CCVec_CCSlice_new(tool);
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-I") == 0 && i + 1 < argc) {
            CCSlice dir = cc_slice_from_buffer(argv[i + 1], strlen(argv[i + 1]));
            if (!custom_dirs) {
#line 798 "cc/lower/cclower.ccs"
                CCVec_CCSlice_clear(&g_include_dirs);
#line 798 "cc/lower/cclower.ccs"
                custom_dirs = true;
#line 798 "cc/lower/cclower.ccs"
            }
            CCVec_CCSlice_push(&g_include_dirs, dir);
            i++;
            continue;
        }
        if (strcmp(argv[i], "--root") == 0 && i + 1 < argc) {
#line 803 "cc/lower/cclower.ccs"
            g_root = cc_slice_from_buffer(argv[i + 1], strlen(argv[i + 1]));
#line 803 "cc/lower/cclower.ccs"
            i++;
#line 803 "cc/lower/cclower.ccs"
            continue;
#line 803 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--h-root") == 0 && i + 1 < argc) {
#line 804 "cc/lower/cclower.ccs"
            g_h_root = argv[i + 1];
#line 804 "cc/lower/cclower.ccs"
            i++;
#line 804 "cc/lower/cclower.ccs"
            continue;
#line 804 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--quote-dir") == 0 && i + 1 < argc) {
#line 805 "cc/lower/cclower.ccs"
            g_quote_dir = argv[i + 1];
#line 805 "cc/lower/cclower.ccs"
            i++;
#line 805 "cc/lower/cclower.ccs"
            continue;
#line 805 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--schema-variants") == 0 && i + 1 < argc) {
#line 806 "cc/lower/cclower.ccs"
            g_schema_variants = argv[i + 1];
#line 806 "cc/lower/cclower.ccs"
            i++;
#line 806 "cc/lower/cclower.ccs"
            continue;
#line 806 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--instantiate") == 0 && i + 1 < argc) {
#line 807 "cc/lower/cclower.ccs"
            g_instantiate = argv[i + 1];
#line 807 "cc/lower/cclower.ccs"
            i++;
#line 807 "cc/lower/cclower.ccs"
            continue;
#line 807 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--factories") == 0 && i + 1 < argc) {
#line 808 "cc/lower/cclower.ccs"
            g_factories = argv[i + 1];
#line 808 "cc/lower/cclower.ccs"
            i++;
#line 808 "cc/lower/cclower.ccs"
            continue;
#line 808 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--modules") == 0 && i + 1 < argc) {
#line 809 "cc/lower/cclower.ccs"
            g_modules = argv[i + 1];
#line 809 "cc/lower/cclower.ccs"
            i++;
#line 809 "cc/lower/cclower.ccs"
            continue;
#line 809 "cc/lower/cclower.ccs"
        }
        if (strcmp(argv[i], "--identity") == 0)
#line 810 "cc/lower/cclower.ccs"
            mode = M_IDENTITY;
#line 810 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "--print") == 0)
            mode = M_PRINT;
#line 811 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "--lower") == 0) {
            mode = M_PRINT;
#line 812 "cc/lower/cclower.ccs"
            lower = true;
#line 812 "cc/lower/cclower.ccs"
        } else if (strcmp(argv[i], "--is-plain-c") == 0)
            mode = M_PLAIN;
#line 813 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "--known-types") == 0 && i + 1 < argc)
            known_path = argv[++i];
#line 814 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "--quote-dir") == 0 && i + 1 < argc)
            i++;
#line 815 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc)
            out_path = argv[++i];
#line 816 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "--no-line") == 0)
            line_directives = false;
#line 817 "cc/lower/cclower.ccs"
        else if (strcmp(argv[i], "--header") == 0)
            header_mode = true;
#line 818 "cc/lower/cclower.ccs"
        else if (argv[i][0] == '-' && argv[i][1])
            usage();
    }
    if (mode == M_NONE)
#line 821 "cc/lower/cclower.ccs"
        usage();
    if (known_path)
#line 822 "cc/lower/cclower.ccs"
        read_known_types(known_path, &known, tool);
    if (g_modules)
#line 823 "cc/lower/cclower.ccs"
        read_modules(g_modules, tool);
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--known-types") == 0 || strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "-I") == 0 || strcmp(argv[i], "--root") == 0 || strcmp(argv[i], "--h-root") == 0 || strcmp(argv[i], "--schema-variants") == 0 || strcmp(argv[i], "--instantiate") == 0 || strcmp(argv[i], "--factories") == 0 || strcmp(argv[i], "--modules") == 0 || strcmp(argv[i], "--quote-dir") == 0) {
#line 831 "cc/lower/cclower.ccs"
            i++;
#line 831 "cc/lower/cclower.ccs"
            continue;
#line 831 "cc/lower/cclower.ccs"
        }
        if (argv[i][0] == '-' && argv[i][1])
#line 832 "cc/lower/cclower.ccs"
            continue;
        n_files++;
        switch (mode) {
            case M_IDENTITY:
#line 835 "cc/lower/cclower.ccs"
                rc |= run_identity(argv[i], known);
#line 835 "cc/lower/cclower.ccs"
                break;
            case M_PRINT:
#line 836 "cc/lower/cclower.ccs"
                rc |= run_print(argv[i], known, out_path, line_directives, header_mode, lower, &todo, tool);
#line 836 "cc/lower/cclower.ccs"
                break;
            case M_PLAIN:
#line 837 "cc/lower/cclower.ccs"
                rc |= run_is_plain_c(argv[i], known);
#line 837 "cc/lower/cclower.ccs"
                break;
            default:
#line 838 "cc/lower/cclower.ccs"
                break;
        }
        fflush(stdout);
    }
    if (!n_files)
#line 842 "cc/lower/cclower.ccs"
        usage();
    {
#line 843 "cc/lower/cclower.ccs"
        __cc_retval = rc;
#line 843 "cc/lower/cclower.ccs"
        goto __cc_cleanup;
#line 843 "cc/lower/cclower.ccs"
    }
#line 843 "cc/lower/cclower.ccs"
    __cc_cleanup:;
#line 843 "cc/lower/cclower.ccs"
    {
#line 778 "cc/lower/cclower.ccs"
        if (__cc_defer_on_1) {
#line 778 "cc/lower/cclower.ccs"
            {
#line 778 "cc/lower/cclower.ccs"
                cc_arena_destroy(&tool);
#line 778 "cc/lower/cclower.ccs"
            }
#line 778 "cc/lower/cclower.ccs"
        }
#line 843 "cc/lower/cclower.ccs"
        return __cc_retval;
#line 843 "cc/lower/cclower.ccs"
    }
}
