#line 1 "cc/lower/lex.cch"
#pragma once
#line 1 "cc/lower/lex.cch"
/* Lexer: bytes → tokens with byte-exact trivia.
 *
 * Every token carries the text it was lexed from and the trivia (spaces,
 * newlines, comments) before it, as slices of the source, so the token
 * stream reproduces the file byte for byte. Positions are physical (line
 * and column in the file as read) plus the `#line`-rebased logical line
 * the diagnostics use.
 *
 * Lifetimes: a `CcTape` and every slice in it live in the arena `cc_lex`
 * is given; the source text must outlive the tape (it is not copied). */

/* generated by Concurrent-C (ccc / cclower) */
#include <stddef.h>
#include <stdint.h>
#line 11 "cc/lower/lex.cch"

#line 11 "cc/lower/lex.cch"
#ifndef CC_LOWER_LEX_CCH
#define CC_LOWER_LEX_CCH

#include "diag.h"
#line 13 "cc/lower/lex.cch"


typedef enum CcTokKind {
    CC_TK_EOF,
    CC_TK_IDENT,
#line 17 "cc/lower/lex.cch"
    /* identifier or keyword: keywords are identifiers to the lexer */
    CC_TK_AT_WORD,
#line 18 "cc/lower/lex.cch"
    /* @parallel, @string, @scratch ... text includes the '@' */
    CC_TK_AT,
#line 19 "cc/lower/lex.cch"
    /* a lone '@' */
    CC_TK_NUMBER,
    CC_TK_CHAR,
    CC_TK_STRING,
    CC_TK_TEMPLATE,
#line 23 "cc/lower/lex.cch"
    /* a whole backtick literal; parts are split by the parser */
    CC_TK_PUNCT,
    CC_TK_PP,
#line 25 "cc/lower/lex.cch"
    /* a preprocessor line, whole, including continuations */
    CC_TK_ERROR /* an unterminated literal or a byte the lexer cannot place */
} CcTokKind;

typedef enum CcPunct {
    CC_P_NONE,
    /* C */
    CC_P_LBRACE,
#line 32 "cc/lower/lex.cch"
    CC_P_RBRACE,
#line 32 "cc/lower/lex.cch"
    CC_P_LPAREN,
#line 32 "cc/lower/lex.cch"
    CC_P_RPAREN,
#line 32 "cc/lower/lex.cch"
    CC_P_LBRACKET,
#line 32 "cc/lower/lex.cch"
    CC_P_RBRACKET,
    CC_P_SEMI,
#line 33 "cc/lower/lex.cch"
    CC_P_COMMA,
#line 33 "cc/lower/lex.cch"
    CC_P_DOT,
#line 33 "cc/lower/lex.cch"
    CC_P_ARROW,
#line 33 "cc/lower/lex.cch"
    CC_P_ELLIPSIS,
    CC_P_PLUS,
#line 34 "cc/lower/lex.cch"
    CC_P_MINUS,
#line 34 "cc/lower/lex.cch"
    CC_P_STAR,
#line 34 "cc/lower/lex.cch"
    CC_P_SLASH,
#line 34 "cc/lower/lex.cch"
    CC_P_PERCENT,
    CC_P_AMP,
#line 35 "cc/lower/lex.cch"
    CC_P_PIPE,
#line 35 "cc/lower/lex.cch"
    CC_P_CARET,
#line 35 "cc/lower/lex.cch"
    CC_P_TILDE,
#line 35 "cc/lower/lex.cch"
    CC_P_BANG,
    CC_P_LT,
#line 36 "cc/lower/lex.cch"
    CC_P_GT,
#line 36 "cc/lower/lex.cch"
    CC_P_LE,
#line 36 "cc/lower/lex.cch"
    CC_P_GE,
#line 36 "cc/lower/lex.cch"
    CC_P_EQEQ,
#line 36 "cc/lower/lex.cch"
    CC_P_NE,
    CC_P_ANDAND,
#line 37 "cc/lower/lex.cch"
    CC_P_OROR,
#line 37 "cc/lower/lex.cch"
    CC_P_SHL,
#line 37 "cc/lower/lex.cch"
    CC_P_SHR,
#line 37 "cc/lower/lex.cch"
    CC_P_INC,
#line 37 "cc/lower/lex.cch"
    CC_P_DEC,
    CC_P_ASSIGN,
#line 38 "cc/lower/lex.cch"
    CC_P_PLUS_ASSIGN,
#line 38 "cc/lower/lex.cch"
    CC_P_MINUS_ASSIGN,
#line 38 "cc/lower/lex.cch"
    CC_P_STAR_ASSIGN,
#line 38 "cc/lower/lex.cch"
    CC_P_SLASH_ASSIGN,
    CC_P_PERCENT_ASSIGN,
#line 39 "cc/lower/lex.cch"
    CC_P_AMP_ASSIGN,
#line 39 "cc/lower/lex.cch"
    CC_P_PIPE_ASSIGN,
#line 39 "cc/lower/lex.cch"
    CC_P_CARET_ASSIGN,
    CC_P_SHL_ASSIGN,
#line 40 "cc/lower/lex.cch"
    CC_P_SHR_ASSIGN,
#line 40 "cc/lower/lex.cch"
    CC_P_QUESTION,
#line 40 "cc/lower/lex.cch"
    CC_P_COLON,
#line 40 "cc/lower/lex.cch"
    CC_P_HASH,
#line 40 "cc/lower/lex.cch"
    CC_P_HASHHASH,
    /* Concurrent-C */
    CC_P_UNWRAP,
#line 42 "cc/lower/lex.cch"
    /* !> */
    CC_P_UNWRAP_OR,
#line 43 "cc/lower/lex.cch"
    /* ?> */
    CC_P_FAT_ARROW,
#line 44 "cc/lower/lex.cch"
    /* => */
    CC_P_COLONCOLON,
#line 45 "cc/lower/lex.cch"
    /* :: */
    CC_P_DOTDOT,
#line 46 "cc/lower/lex.cch"
    /* .. */
    CC_P_BACKTICK,
#line 47 "cc/lower/lex.cch"
    /* only inside a template part boundary */
    CC_P_DOLLAR
} CcPunct;

typedef struct CcToken {
    CcTokKind kind;
    CcPunct punct; /* when kind == CC_TK_PUNCT */
    CCSlice text; /* the token's bytes in the source */
    CCSlice lead; /* trivia before it: whitespace and comments, byte-exact */
    uint32_t line; /* physical line, 1-based */
    uint32_t col; /* physical column, 1-based, in bytes */
    bool at_line_start; /* only trivia precedes it on its line */
    bool after_space; /* lead is non-empty */
} CcToken;

/* tok.is(p), tok.is_ident("static"), tok.is_at("@parallel") */

#ifndef CC_HEADER_VEC_CCVec_CcToken
#define CC_HEADER_VEC_CCVec_CcToken
/* generic CCVec_CcToken */

#ifdef CC_HAS_CCSLICE_CcToken
CC_VEC_DECL_ARENA_TSLICE(CcToken, CCVec_CcToken, CCSlice_CcToken)
#else
CC_VEC_DECL_ARENA(CcToken, CCVec_CcToken)
#endif
static inline CCVec_CcToken cc__CCVec_CcToken_new(CCArena __a) {
    return CCVec_CcToken_init(__a, 0);
}
#define CCVec_CcToken_new(ar) cc__CCVec_CcToken_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcToken (serdes) */
static const cc_type_info __cc_ti_CCVec_CcToken = { .name = "CCVec_CcToken", .mangled = "CCVec_CcToken", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcToken)), .align = (uint32_t)(_Alignof(CCVec_CcToken)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcToken(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcToken);
}
#endif
#line 63 "cc/lower/lex.cch"

#line 63 "cc/lower/lex.cch"
bool CcToken_is(const CcToken *t, CcPunct p);
bool CcToken_is_ident(const CcToken *t, const char *word);
bool CcToken_is_at(const CcToken *t, const char *word);

/* A `#line N "path"` seen in the input, rebasing logical positions from
 * the physical line after it. The directive line itself belongs to the
 * position it names: nothing on the tape reads as the stage the directive
 * was prepended to. */
typedef struct CcLineMark {
    uint32_t dir_off; /* first byte of the directive */
    uint32_t off; /* first byte of the line after the directive */
    uint32_t phys_line; /* physical line of `off` */
    uint32_t logical_line;
    CCSlice path; /* empty: unchanged */
} CcLineMark;


#ifndef CC_HEADER_VEC_CCVec_CcLineMark
#define CC_HEADER_VEC_CCVec_CcLineMark
/* generic CCVec_CcLineMark */

#ifdef CC_HAS_CCSLICE_CcLineMark
CC_VEC_DECL_ARENA_TSLICE(CcLineMark, CCVec_CcLineMark, CCSlice_CcLineMark)
#else
CC_VEC_DECL_ARENA(CcLineMark, CCVec_CcLineMark)
#endif
static inline CCVec_CcLineMark cc__CCVec_CcLineMark_new(CCArena __a) {
    return CCVec_CcLineMark_init(__a, 0);
}
#define CCVec_CcLineMark_new(ar) cc__CCVec_CcLineMark_new(CC__ARENA_HANDLE(ar))

/* cc_type_info for CCVec_CcLineMark (serdes) */
static const cc_type_info __cc_ti_CCVec_CcLineMark = { .name = "CCVec_CcLineMark", .mangled = "CCVec_CcLineMark", .id = 0, .size = (uint32_t)(sizeof(CCVec_CcLineMark)), .align = (uint32_t)(_Alignof(CCVec_CcLineMark)), .kind = (uint16_t)(CC_TK_GENERIC_INST), .nfields = 0, .flags = (uint16_t)(CC_TF_ERASABLE), ._reserved = 0, .fields = NULL, .copy_fn = NULL, .drop_fn = NULL };
static __attribute__((constructor)) void cc__ti_reg_CCVec_CcLineMark(void) {
    cc_type_info_register(&__cc_ti_CCVec_CcLineMark);
}
#endif
#line 79 "cc/lower/lex.cch"

#line 79 "cc/lower/lex.cch"
typedef struct CcTape {
    CCSlice path; /* as given: the spelling diagnostics use */
    CCSlice src; /* the whole file; every token slice points into it */
    CCVec_CcToken toks; /* ends with one CC_TK_EOF whose lead is the trailing trivia */
    CCVec_CcLineMark marks;
    uint32_t n_errors; /* CC_TK_ERROR tokens; each also reported to the sink */
} CcTape;

/* Lex `src`. Every unplaceable byte is a CC_TK_ERROR token and a
 * diagnostic on `ds`; lexing continues so one file reports every error. */
CcTape cc_lex(CCSlice path, CCSlice src, CcDiags *ds, CCArena a);

/* tape.loc(i): user coordinates of token i, through the #line marks. */
CcLoc CcTape_loc(const CcTape *t, uint32_t i);
/* tape.line_text(phys_line): the physical line, for caret snippets. */
CCSlice CcTape_line_text(const CcTape *t, uint32_t phys_line);
/* tape.at(i): the token; i past the end is the EOF token. */
const CcToken *CcTape_at(const CcTape *t, uint32_t i);


typedef CcTape CcTape_Restrict_Read;
#line 98 "cc/lower/lex.cch"


#endif
